### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'start'

### ISSUE THREAD

**Issue by Jungled** [pwndbg/pwndbg#1001]
###  **Description**

this happens when I use the "bin" command to see the chunk...
I have tested on ubuntu 18.04.5 with gdb 8.1 and ubuntu  20.04.1 with gdb 9.2

### Steps to reproduce

1.load binary in gdb in x86-64 pc
2.breakpoint set
3.run
4.bins

```
Breakpoint 2, __GI_setlocale (category=6, locale=0x7f7f9eaa9464 "C") at setlocale.c:220
220	in setlocale.c
Exception occurred: context: 'NoneType' object has no attribute 'start' (<class 'AttributeError'>)
For more info invoke `set exception-verbose on` and rerun the command
or debug it by yourself with `set exception-debugger on`
pwndbg> bins
Exception occurred: tcachebins: 'NoneType' object has no attribute 'start' (<class 'AttributeError'>)
For more info invoke `set exception-verbose on` and rerun the command
or debug it by yourself with `set exception-debugger on`
fastbins
0x20: 0x0
0x30: 0x0
0x40: 0x0
0x50: 0x0
0x60: 0x0
0x70: 0x0
0x80: 0x0
Exception occurred: unsortedbin: 'NoneType' object has no attribute 'start' (<class 'AttributeError'>)
For more info invoke `set exception-verbose on` and rerun the command
or debug it by yourself with `set exception-debugger on`
smallbins
empty
largebins
empty
pwndbg> set exception-verbose on
Set whether to print a full stacktrace for exceptions raised in Pwndbg commands to True
pwndbg> c
Continuing.

Breakpoint 2, __GI_setlocale (category=6, locale=0x5586064ac070 "C.UTF-8@", 'C' <repeats 192 times>...) at setlocale.c:220
220	in setlocale.c
Traceback (most recent call last):
  File "/root/pwndbg/pwndbg/commands/__init__.py", line 131, in __call__
    return self.function(*args, **kwargs)
  File "/root/pwndbg/pwndbg/commands/__init__.py", line 225, in _OnlyWhenRunning
    return function(*a, **kw)
  File "/root/pwndbg/pwndbg/commands/context.py", line 268, in context
    with_banner=settings.get("banner_top", True)))
  File "/root/pwndbg/pwndbg/commands/context.py", line 358, in context_regs
    regs = get_regs()
  File "/root/pwndbg/pwndbg/commands/context.py", line 413, in get_regs
    desc = pwndbg.chain.format(value)
  File "/root/pwndbg/pwndbg/chain.py", line 97, in format
    symbol = pwndbg.symbol.get(link) or None
  File "/root/pwndbg/pwndbg/memoize.py", line 52, in __call__
    value = self.func(*args, **kwargs)
  File "/root/pwndbg/pwndbg/symbol.py", line 170, in get
    exe     = pwndbg.elf.exe()
  File "/root/pwndbg/pwndbg/proc.py", line 82, in wrapper
    return func(*a, **kw)
  File "/root/pwndbg/pwndbg/memoize.py", line 52, in __call__
    value = self.func(*args, **kwargs)
  File "/root/pwndbg/pwndbg/elf.py", line 182, in exe
    return load(e)
  File "/root/pwndbg/pwndbg/elf.py", line 220, in load
    return get_ehdr(pointer)[1]
  File "/root/pwndbg/pwndbg/elf.py", line 246, in get_ehdr
    if pwndbg.memory.read(vmmap.start, 4) == b'\x7fELF':
AttributeError: 'NoneType' object has no attribute 'start'

If that is an issue, you can report it on https://github.com/pwndbg/pwndbg/issues
(Please don't forget to search if it hasn't been reported before)
To generate the report and open a browser, you may run `bugreport --run-browser`

```

**### My setup**

Platform: ubuntu-18.04.5-desktop-amd64
Gdb: 8.1
Python 3.6.5 (default, Apr  1 2018, 05:46:30)
Pwndbg: Releases 2022.01.05

any help would be appreciated

**Comment by disconnect3d** [comment]
Interesting. What does `vmmap` return in your case if u execute it instead of `bins`?

**Comment by disconnect3d** [comment]
This should be fixed in the latest dev branch version. Please reopen or start another issue if it is not.
