### ISSUE TITLE
Exception at the beginning of GDB

### ISSUE THREAD

**Issue by gkso** [pwndbg/pwndbg#1006]
### Description

When using pwndbg with an aarch64-linux-gnu-gdb from the ARM toolchain, it throws the following exception at the beginning.

```
alan@alan-nuc:~/Work/optee$ toolchains/aarch64/bin/aarch64-linux-gnu-gdb
GNU gdb (GNU Toolchain for the A-profile Architecture 10.2-2020.11 (arm-10.16)) 10.1.90.20201028-git
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "--host=x86_64-pc-linux-gnu --target=aarch64-none-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://bugs.linaro.org/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
Traceback (most recent call last):
  File "/home/alan/Work/pwndbg/gdbinit.py", line 24, in <module>
    import pwndbg # isort:skip
  File "/home/alan/Work/pwndbg/pwndbg/__init__.py", line 7, in <module>
    import pwndbg.android
  File "/home/alan/Work/pwndbg/pwndbg/android.py", line 5, in <module>
    import pwndbg.color.message as message
  File "/home/alan/Work/pwndbg/pwndbg/color/__init__.py", line 4, in <module>
    import pwndbg.memoize
  File "/home/alan/Work/pwndbg/pwndbg/memoize.py", line 42
    print("Cannot memoize %r!", file=sys.stderr)
                                    ^
SyntaxError: invalid syntax

```

### Steps to reproduce

1. Install pwndbg.
2. Download the [ARM toolchain](https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-a/downloads) from this link: https://developer.arm.com/-/media/Files/downloads/gnu-a/10.2-2020.11/binrel/gcc-arm-10.2-2020.11-x86_64-aarch64-none-linux-gnu.tar.xz
3. Run aarch64-linux-gnu-gdb.

### My setup

- gdb version: GNU gdb (GNU Toolchain for the A-profile Architecture 10.2-2020.11 (arm-10.16)) 10.1.90.20201028-git
- python version: Python 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0] on linux
- pwndbg version: commit c11ac3710beb7c1df4d1970d17a0b7e5e2d17845
- Ubuntu 20.04

**Comment by disconnect3d** [comment]
Hey,

Does other GDB version work? This seems really weird as what is pointed out is not an invalid syntax. It sounds as if GDB maybe used Python 2, but you are saying Python 3.8 is used. Can you double check/confirm Python version by showing us the output of those two commands in your GDB: `pi import sys` and `pi print(sys.version)`?

**Comment by automatedbugreportingfacility** [comment]
@disconnect3d: Happens for me as well:

```
GNU gdb (GDB) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
Traceback (most recent call last):
  File "/home/name/Desktop/pwndbg/gdbinit.py", line 24, in <module>
    import pwndbg # isort:skip
  File "/home/name/Desktop/pwndbg/pwndbg/__init__.py", line 7, in <module>
    import pwndbg.android
  File "/home/name/Desktop/pwndbg/pwndbg/android.py", line 5, in <module>
    import pwndbg.color.message as message
  File "/home/name/Desktop/pwndbg/pwndbg/color/__init__.py", line 4, in <module>
    import pwndbg.memoize
  File "/home/name/Desktop/pwndbg/pwndbg/memoize.py", line 42
    print("Cannot memoize %r!", file=sys.stderr)
                                    ^
SyntaxError: invalid syntax

(gdb) pi import sys
(gdb) pi print(sys.version)
2.7.18 (default, Mar  8 2021, 13:02:45) 
[GCC 9.3.0]
```

When I comment out the line, it fails later:
```
Traceback (most recent call last):
  File "/home/name/Desktop/pwndbg/gdbinit.py", line 24, in <module>
    import pwndbg # isort:skip
  File "/home/name/Desktop/pwndbg/pwndbg/__init__.py", line 7, in <module>
    import pwndbg.android
  File "/home/name/Desktop/pwndbg/pwndbg/android.py", line 7, in <module>
    import pwndbg.file
  File "/home/name/Desktop/pwndbg/pwndbg/file.py", line 18, in <module>
    import pwndbg.symbol
  File "/home/name/Desktop/pwndbg/pwndbg/symbol.py", line 105
    print(msg, end='')
                  ^
SyntaxError: invalid syntax
```

**Comment by disconnect3d** [comment]
@automatedbugreportingfacility you are using GDB compiled with Python 2 which is unsupported by Pwndbg. Please recompile GDB with Python 3.
