### ISSUE TITLE
Pwndbg breaks w/ trace-commands enabled

### ISSUE THREAD

**Issue by claflinnate** [pwndbg/pwndbg#1021]
### Description
pwndbg breaks with trace-commands enabled, I have a use case where I want to dynamically save user input to a file which trace-commands allows, however this breaks the pwndbg functionality. 

```
+r
Starting program: /home/parallels/example/demo 
The bare metal debugging is enabled since gdb's osabi is '++show osabi' which is not 'GNU/Linux'.
Ex. the page resolving and memory de-referencing ONLY works on known pages.
This option is based on gdb client compile arguments (by default) and will be corrected if you load an ELF with a '.note.ABI-tag' section.            
If you are debugging a program that runs on the Linux ABI, please select the correct gdb client.

Breakpoint 1, main (argc=1, argv=0xfffffffff088) at demo.c:6
6               func_0_args();
Warning: Skipping auxv entry '++info auxv'
Traceback (most recent call last):
  File "/home/parallels/pwndbg/pwndbg/events.py", line 165, in caller
    func()
  File "/home/parallels/pwndbg/pwndbg/strings.py", line 33, in update_length
    length = int(message)                      
ValueError: invalid literal for int() with base 10: 'elements'

Traceback (most recent call last):
  File "/home/parallels/pwndbg/pwndbg/events.py", line 169, in caller
    raise e
  File "/home/parallels/pwndbg/pwndbg/events.py", line 165, in caller
    func()
  File "/home/parallels/pwndbg/pwndbg/strings.py", line 33, in update_length
    length = int(message)
ValueError: invalid literal for int() with base 10: 'elements'
Traceback (most recent call last):
  File "/home/parallels/pwndbg/pwndbg/events.py", line 165, in caller
    func()
  File "/home/parallels/pwndbg/pwndbg/strings.py", line 33, in update_length
    length = int(message)
ValueError: invalid literal for int() with base 10: 'elements'

Traceback (most recent call last):
  File "/home/parallels/pwndbg/pwndbg/prompt.py", line 30, in prompt_hook
    pwndbg.events.after_reload(start=cur is None)
  File "/home/parallels/pwndbg/pwndbg/events.py", line 216, in after_reload
    f()                                        
  File "/home/parallels/pwndbg/pwndbg/events.py", line 169, in caller
    raise e
  File "/home/parallels/pwndbg/pwndbg/events.py", line 165, in caller
    func()
  File "/home/parallels/pwndbg/pwndbg/strings.py", line 33, in update_length
    length = int(message)                      
ValueError: invalid literal for int() with base 10: 'elements'
```

### Steps to reproduce

before running binary, enable trace-commands 
```
gdb <binary>
set trace-commands on
r
```

### My setup

+version
Gdb:      9.2
Python:   3.8.10 (default, Mar 15 2022, 12:22:08)  [GCC 9.4.0]
Pwndbg:   1.1.0 build: 44286af
Capstone: 4.0.1024
Unicorn:  1.0.3

**Comment by disconnect3d** [comment]
```
ipdb> gdb.execute('show print elements', from_tty=True, to_string=True)
'++show print elements\nLimit on string chars or array elements to print is 200.\n'
ipdb> gdb.execute('show print elements', from_tty=False, to_string=True)
'++show print elements\nLimit on string chars or array elements to print is 200.\n'
ipdb> gdb.execute('show print elements', from_tty=True, to_string=True).split('\n')
['++show print elements', 'Limit on string chars or array elements to print is 200.', '']
ipdb> gdb.execute('show print elements', from_tty=True, to_string=True).split('\n')[0]
'++show print elements'
```

Heh, we do execute `gdb.execute(..., to_string=True)` in few places and parse the output as GDB doesn't provide good API for everything, and this is where it breaks :/.

**Comment by claflinnate** [comment]
So i dug into the error message and hack-fixed it locally which might work fine for me, in strings.py

```
 30     if message == 'unlimited':
 31         length = 0
 32     else:
 33         try:
 34             length = int(message)
 35         except:
 36             length = 0
```

adding the try/except there just forces the length to 0 if there's any kind of failure. obviously not a good production fix but i think i can at least make forward progress and haven't seen any bad functionality yet from this

**Comment by disconnect3d** [comment]
It seems we should wrap gdb.execute into something that is able to recognize that trace-command was enabled

**Comment by disconnect3d** [comment]
Our of curiosity: would u also want the Pwndbg's execution of GDB commands be saved to user file? I believe not really and u only care about explicit user's input, @claflinnate?

**Comment by claflinnate** [comment]
I think default gdb logging can do that, just not the commands that were input which was all I really needed
