### ISSUE TITLE
Context throws ValueError when connecting to remote target

### ISSUE THREAD

**Issue by thetacom** [pwndbg/pwndbg#1045]
### Description
```
Context throws ValueError when connecting to remote target. 

Exception occurred: context: invalid literal for int() with base 10: '' (<class 'ValueError'>)

Traceback (most recent call last):
  File "/home/vscode/pwndbg/pwndbg/commands/__init__.py", line 131, in __call__
    return self.function(*args, **kwargs)
  File "/home/vscode/pwndbg/pwndbg/commands/__init__.py", line 225, in _OnlyWhenRunning
    return function(*a, **kw)
  File "/home/vscode/pwndbg/pwndbg/commands/context.py", line 274, in context
    with_banner=settings.get("banner_top", True)))
  File "/home/vscode/pwndbg/pwndbg/commands/context.py", line 364, in context_regs
    regs = get_regs()
  File "/home/vscode/pwndbg/pwndbg/commands/context.py", line 419, in get_regs
    desc = pwndbg.chain.format(value)
  File "/home/vscode/pwndbg/pwndbg/chain.py", line 100, in format
    rest.append(M.get(link, symbol))
  File "/home/vscode/pwndbg/pwndbg/color/memory.py", line 45, in get
    page = pwndbg.vmmap.find(int(address))
  File "/home/vscode/pwndbg/pwndbg/memoize.py", line 52, in __call__
    value = self.func(*args, **kwargs)
  File "/home/vscode/pwndbg/pwndbg/vmmap.py", line 78, in find
    for page in get():
  File "/home/vscode/pwndbg/pwndbg/memoize.py", line 52, in __call__
    value = self.func(*args, **kwargs)
  File "/home/vscode/pwndbg/pwndbg/vmmap.py", line 45, in get
    pages.extend(monitor_info_mem())
  File "/home/vscode/pwndbg/pwndbg/memoize.py", line 52, in __call__
    value = self.func(*args, **kwargs)
  File "/home/vscode/pwndbg/pwndbg/vmmap.py", line 236, in monitor_info_mem
    p.lazy_init()
  File "/home/vscode/pwndbg/gdb-pt-dump/pt.py", line 162, in lazy_init
    pid = int(proc.read().strip(), 10)
ValueError: invalid literal for int() with base 10: ''
```
### Steps to reproduce

Remote target is a simple c program running under qemu-i386. Host environment is an aarch64 debian linux container with all pwndbg dependencies installed. 

Gdb session history:
```
target remote :57471
set exception-debugger on
context
bugreport --run-browser
exit
```
### My setup
```
Platform: Linux-5.10.104-linuxkit-aarch64-with-debian-10.12
Gdb:      8.2.1
Python:   3.7.3 (default, Jan 22 2021, 20:04:44)  [GCC 8.3.0]
Pwndbg:   1.1.0 build: 52d30e2
Capstone: 4.0.1024
Unicorn:  2.0.0
This GDB was configured as follows:
   configure --host=aarch64-linux-gnu --target=aarch64-linux-gnu
             --with-auto-load-dir=$debugdir:$datadir/auto-load
             --with-auto-load-safe-path=$debugdir:$datadir/auto-load
             --with-expat
             --with-gdb-datadir=/usr/share/gdb (relocatable)
             --with-jit-reader-dir=/usr/lib/gdb (relocatable)
             --without-libunwind-ia64
             --with-lzma
             --without-babeltrace
             --without-intel-pt
             --disable-libmcheck
             --without-mpfr
             --with-python=/usr (relocatable)
             --without-guile
             --with-separate-debug-dir=/usr/lib/debug (relocatable)
             --with-system-gdbinit=/etc/gdb/gdbinit
```

**Comment by disconnect3d** [comment]
Hey, this is... qemu user emulation, right?

**Comment by disconnect3d** [comment]
Hey,

This is a true positive bug.

I've recently merged the PR that allows us to grab memory map info for QEMU kernel targets, which added this piece of code:
https://github.com/pwndbg/pwndbg/blob/52d30e2a722454409cf91867995b2f76e874c6c3/pwndbg/vmmap.py#L234-L249

(Fwiw I should've cleared that part a bit)

But if I understand correctly, it does not handle properly the case where the target is a qemu user mode emulation... Previously this function was always executed in such a case, triggered a GDB exception and returned `tuple()` which was the expected result from it. To be honest we should rather check first whether the target is qemu kernel and call this func only in such cases.

This can be easily fixed. PR comming soon.

**Comment by disconnect3d** [comment]
Should be fixed now. @thetacom
