### ISSUE TITLE
`tls` command error: 'No symbol "__errno_location" in current context.'

### ISSUE THREAD

**Issue by gsingh93** [pwndbg/pwndbg#1237]
```console
$ gdb ./tests/binaries/heap_bins.out
pwndbg> starti
pwndbg> tls
Traceback (most recent call last):
  File "/home/gsgx/code/pwndbg/pwndbg/commands/__init__.py", line 149, in __call__
    return self.function(*args, **kwargs)
  File "/home/gsgx/code/pwndbg/pwndbg/commands/__init__.py", line 220, in _OnlyWhenRunning
    return function(*a, **kw)
  File "/home/gsgx/code/pwndbg/pwndbg/commands/tls.py", line 15, in tls
    tls_base = pwndbg.tls.address
  File "/home/gsgx/code/pwndbg/pwndbg/tls.py", line 95, in address
    return tls_base if is_valid_tls_base else self.get_tls_base_via_errno_location()
  File "/home/gsgx/code/pwndbg/pwndbg/tls.py", line 31, in get_tls_base_via_errno_location
    errno_addr = int(gdb.parse_and_eval("(int *)__errno_location()"))
gdb.error: No symbol "__errno_location" in current context.
```

Found with `./tests.sh test_commands.py` (after removing the decorator skipping it).

**Comment by gsingh93** [comment]
I was testing whether this issue is fixed, it now works with the binary shown above, but I see this error now with `/bin/ls`:
```
$ gdb /bin/ls
pwndbg> starti
pwndbg> tls

Program received signal SIGSEGV, Segmentation fault.
0x00000000000040a0 in ?? ()
Traceback (most recent call last):
  File "/home/gsgx/code/pwndbg/pwndbg/commands/__init__.py", line 185, in __call__
    return self.function(*args, **kwargs)
  File "/home/gsgx/code/pwndbg/pwndbg/commands/__init__.py", line 315, in _OnlyWhenRunning
    return function(*a, **kw)
  File "/home/gsgx/code/pwndbg/pwndbg/commands/tls.py", line 17, in tls
    tls_base = pwndbg.gdblib.tls.address
  File "/home/gsgx/code/pwndbg/pwndbg/gdblib/tls.py", line 103, in address
    return tls_base if is_valid_tls_base else self.get_tls_base_via_errno_location()
  File "/home/gsgx/code/pwndbg/pwndbg/gdblib/tls.py", line 38, in get_tls_base_via_errno_location
    errno_addr = int(gdb.parse_and_eval("(int *)__errno_location()"))
gdb.error: The program being debugged was signaled while in a function called from GDB.
GDB remains in the frame where the signal was received.
To change this behavior use "set unwindonsignal on".
Evaluation of the expression containing the function
(__errno_location@plt) will be abandoned.
When the function is done executing, GDB will silently stop.

If that is an issue, you can report it on https://github.com/pwndbg/pwndbg/issues
(Please don't forget to search if it hasn't been reported before)
To generate the report and open a browser, you may run `bugreport --run-browser`
PS: Pull requests are welcome
pwndbg>
```

But if you do `entry` instead of `starti`, `tls` works fine.

I think it would be good to have some decorator that we could add to commands and prevent them from running if libc isn't initialized.

**Comment by disconnect3d** [comment]
Heh, @OnlyWithLibcLoaded? :)

**Comment by gsingh93** [comment]
Closing this, #1496 will add the decorator.
