### ISSUE TITLE
Handle undefined symbols gracefully in command arguments

### ISSUE THREAD

**Issue by gsingh93** [pwndbg/pwndbg#1241]
If the argument to a command is invalid in some way, for example, taking the address of a symbol that doesn't exist, we should handle that gracefully, reporting it to the user and not have an uncaught exception.

```
pwndbg> telescope &target
Traceback (most recent call last):
  File "/home/gsgx/code/pwndbg/pwndbg/commands/__init__.py", line 96, in invoke
    args, kwargs = self.split_args(argument)
  File "/home/gsgx/code/pwndbg/pwndbg/commands/__init__.py", line 340, in split_args
    return tuple(), vars(self.parser.parse_args(argv))
  File "/usr/lib/python3.10/argparse.py", line 1837, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python3.10/argparse.py", line 1870, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.10/argparse.py", line 2082, in _parse_known_args
    stop_index = consume_positionals(start_index)
  File "/usr/lib/python3.10/argparse.py", line 2038, in consume_positionals
    take_action(action, args)
  File "/usr/lib/python3.10/argparse.py", line 1931, in take_action
    argument_values = self._get_values(action, argument_strings)
  File "/usr/lib/python3.10/argparse.py", line 2462, in _get_values
    value = self._get_value(action, arg_string)
  File "/usr/lib/python3.10/argparse.py", line 2495, in _get_value
    result = type_func(arg_string)
  File "/home/gsgx/code/pwndbg/pwndbg/commands/__init__.py", line 199, in fix_int_reraise
    return fix(*a, reraise=True, **kw)
  File "/home/gsgx/code/pwndbg/pwndbg/commands/__init__.py", line 186, in fix
    raise e
  File "/home/gsgx/code/pwndbg/pwndbg/commands/__init__.py", line 181, in fix
    return gdb.parse_and_eval(arg)
gdb.error: No symbol "target" in current context.
```

**Comment by disconnect3d** [comment]
I can't reproduce this on latest version.

Compiling this example with `gcc -ggdb main.c`:
```c
int main() {
	char buf[10];
	int target;
	printf("%p %p\n", buf, target);
}
```

We get:
```
pwndbg> telescope &target 1
00:0000│  0x7fffffffdd88 ◂— 0x64 /* 'd' */

pwndbg> telescope &buf 1
00:0000│  0x7fffffffdd8e ◂— 0x10000000

pwndbg> telescope buf 1
Exception occurred: telescope: Cannot convert value to long. (<class 'gdb.error'>)
For more info invoke `set exception-verbose on` and rerun the command
or debug it by yourself with `set exception-debugger on`

pwndbg> p target
$2 = 100

pwndbg> telescope target
00:0000│ rsp     0x7fffffffdd80 —▸ 0x7fffffffe239 ◂— 0x34365f363878 /* 'x86_64' */
01:0008│         0x7fffffffdd88 ◂— 0x64 /* 'd' */
02:0010│         0x7fffffffdd90 ◂— 0x1000
<97 other lines>
```

I would say that we should:
1) drop `telescope <count instead of addr>` since that makes `telescope target` when `target = 100` counter intuitive and may confuse the user
2) better handle `telescope buf`: either by casting the gdbvalue to uint64 or by printing the user they should pass `&buf`

@gsingh93 thoughts?

**Comment by gsingh93** [comment]
> If the argument to a command is invalid in some way, for example, taking the address of a symbol that doesn't exist

In your example `target` exists. I just think we should provide a better user experience here, i.e. print 'No symbol "target" in current context.' and not have a confusing exception.

> drop telescope <count instead of addr> since that makes telescope target when target = 100 counter intuitive and may confuse the user

I agree that dropping `telescope <count>` would lead to a less confusing API, and I would have designed it that way initially. But I'm so used to adding that count variable there now when just dumping the stack, it's going to be hard to switch, and I imagine it'll be like this for others too.

> better handle telescope buf: either by casting the gdbvalue to uint64 or by printing the user they should pass &buf

I think it would be great if we handled all of this for the user if we have type information. If the user types `telescope <symbol>`, and `symbol` is not a pointer, we convert `symbol` to `&symbol`. If they type `symbol` and it is a pointer, we should not change it. And if they type `&symbol`, we should never change it, regardless of the type.

Whenever we change `symbol` to `&symbol`, we can print a message telling the user we're doing this to avoid confusion.

**Comment by disconnect3d** [comment]
I think this has been done by @k4lizen recently or sth. Closing. If someone finds this still not working or sth, pls report again.
