### ISSUE TITLE
python 3 error in inthook.py

### ISSUE THREAD

**Issue by Isaac0616** [pwndbg/pwndbg#126]
When I invoke commands related to python subprocess, I get the following errors.

```python
pwndbg> checksec
bufsize must be an integer
'checksec': Prints out the binary security settings. Attempts to call the binjitsu
    checksec first, and then falls back to checksec.sh.
pwndbg> ls
Traceback (most recent call last):
  File "/root/pwndbg/pwndbg/commands/__init__.py", line 57, in __call__
    return self.function(*args, **kwargs)
  File "/root/pwndbg/pwndbg/commands/shell.py", line 82, in handler
    os.execvp(cmd, (cmd,) + a)
  File "/usr/lib/python3.5/os.py", line 615, in execvp
    _execvpe(file, args)
  File "/usr/lib/python3.5/os.py", line 643, in _execvpe
    path_list = get_exec_path(env)
  File "/usr/lib/python3.5/os.py", line 681, in get_exec_path
    warnings.simplefilter("ignore", BytesWarning)
  File "/usr/lib/python3.5/warnings.py", line 75, in simplefilter
    "lineno must be an int >= 0"
AssertionError: lineno must be an int >= 0
```

The first error is cause by the following check.
```python
if not isinstance(bufsize, int):
    raise TypeError("bufsize must be an integer")
```

After some debugging, I found that this problem is due to `inthook.py`. 
```python
pwndbg> python print(int)
<class 'pwndbg.inthook.xint'>
```

In `inthook.py`, it use the syntax
```
__metaclass__ = IsAnInt
```
to define metaclass, but this is a python 2 only syntax according to [this page](http://python-future.org/compatible_idioms.html#metaclasses).

I can fix it by using the `future` package like this:
```git
--- a/pwndbg/inthook.py
+++ b/pwndbg/inthook.py
@@ -9,6 +9,7 @@ from __future__ import absolute_import
 from __future__ import division
 from __future__ import print_function
 from __future__ import unicode_literals
+from future.utils import with_metaclass

 import sys

@@ -28,8 +29,7 @@ class IsAnInt(type):
     def __instancecheck__(self, other):
         return isinstance(other, _int)

-class xint(builtins.int):
-    __metaclass__ = IsAnInt
+class xint(with_metaclass(IsAnInt, builtins.int)):
     def __new__(cls, value, *a, **kw):
         if isinstance(value, gdb.Value):
             if pwndbg.typeinfo.is_pointer(value):
```

Would this be an acceptable fix?

**Comment by zachriggle** [comment]
I have no idea if that would work.  If it functions in both Python2 and Python3 then I'm good with that.

**Comment by Isaac0616** [comment]
Then, I would like to make a pull request. Is there any tests that I should pass locally?

**Comment by zachriggle** [comment]
Very unfortunately the only tests currently are that everything is valid
Python2 and Python3, syntactically. See travis.yml

**Comment by zachriggle** [comment]
Closing per #128
