### ISSUE TITLE
AttributeError: '_GdbOutputFile' object has no attribute 'buffer'

### ISSUE THREAD

**Issue by Mangpha** [pwndbg/pwndbg#1362]
### Description

I installed it and tried to run it, but it didn't work

### Steps to reproduce

```
 ✘ ⚙ mangpha@pwnable  ~/pwndbg   dev  gdb
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04.1) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
Traceback (most recent call last):
  File "/home/mangpha/pwndbg/gdbinit.py", line 75, in <module>
    import pwndbg  # noqa: F401
  File "/home/mangpha/pwndbg/pwndbg/__init__.py", line 5, in <module>
    import pwndbg.color
  File "/home/mangpha/pwndbg/pwndbg/color/__init__.py", line 9, in <module>
    from . import theme as theme
  File "/home/mangpha/pwndbg/pwndbg/color/theme.py", line 2, in <module>
    from pwndbg.gdblib import config
  File "/home/mangpha/pwndbg/pwndbg/gdblib/__init__.py", line 3, in <module>
    from pwndbg.gdblib import arch as arch_mod
  File "/home/mangpha/pwndbg/pwndbg/gdblib/arch.py", line 2, in <module>
    import pwnlib
  File "/home/mangpha/.local/lib/python3.8/site-packages/pwnlib/__init__.py", line 37, in <module>
    importlib.import_module('.%s' % module, 'pwnlib')
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/mangpha/.local/lib/python3.8/site-packages/pwnlib/args.py", line 7, in <module>
    from . import term
  File "/home/mangpha/.local/lib/python3.8/site-packages/pwnlib/term/__init__.py", line 5, in <module>
    from . import readline
  File "/home/mangpha/.local/lib/python3.8/site-packages/pwnlib/term/readline.py", line 3, in <module>
    from . import term
  File "/home/mangpha/.local/lib/python3.8/site-packages/pwnlib/term/term.py", line 30, in <module>
    fd = sys.stdout.buffer
AttributeError: '_GdbOutputFile' object has no attribute 'buffer'
(gdb)
```

### My setup

```
gdb: GNU gdb (Ubuntu 9.2-0ubuntu1~20.04.1) 9.2
python: 3.8.10
OS: ubuntu-20.04.5-live-server-amd64
pwndbg: 2022.08.30
```

**Comment by lebr0nli** [comment]
Hi, it seems like the problem you mentioned is similar to an issue of the unmaintained forked version of pwntools: https://github.com/Gallopsled/pwntools/issues/1339

Could you install the latest stable release of pwntools and test if it works for you? Thanks!

**Comment by Mangpha** [comment]
@lebr0nli It works right away. Thank you!
