### ISSUE TITLE
vmmap incorrect for core dumps from gcore

### ISSUE THREAD

**Issue by zachriggle** [pwndbg/pwndbg#144]
It looks like something's wrong with the `vmmap` infrastructure when generated by the `gcore` command-line tool.  It works fine with corefiles generated from `gdb`.

# Via `gcore`

Note the address of the`[vdso]`.

```
$ /bin/bash -c 'gcore $$'
0x00007f6011cdaa0c in waitpid () from /lib/x86_64-linux-gnu/libc.so.6
warning: target file /proc/26026/cmdline contained unexpected null characters
Saved corefile core.26026
$ gdb --batch --ex 'vmmap' --ex 'info proc map' -- /bin/bash core.26026
Loaded 96 commands.  Type pwndbg [filter] for a list.

warning: core file may not match specified executable file.
[New LWP 26026]
Core was generated by `/bin/sh'.
#0  0x00007f6011cdaa0c in __libc_waitpid (pid=0xffffffff, stat_loc=0x7ffc6afc10c8, options=0x0) at ../sysdeps/unix/sysv/linux/waitpid.c:31
31	../sysdeps/unix/sysv/linux/waitpid.c: No such file or directory.
LEGEND: STACK | HEAP | CODE | DATA | RWX | RODATA
0x100007ffc6a6c7000 0x100007ffc6a6c8000 r-xp     1000 0      [vdso]
Mapped address spaces:

          Start Addr           End Addr       Size     Offset objfile
            0x400000           0x4ef000    0xef000        0x0 /bin/bash
            0x6ef000           0x6f0000     0x1000    0xef000 /bin/bash
            0x6f0000           0x6f9000     0x9000    0xf0000 /bin/bash
      0x7f6010d96000     0x7f6011c1a000   0xe84000        0x0 /usr/lib/locale/locale-archive
      0x7f6011c1a000     0x7f6011dd4000   0x1ba000        0x0 /lib/x86_64-linux-gnu/libc-2.19.so
      0x7f6011dd4000     0x7f6011fd4000   0x200000   0x1ba000 /lib/x86_64-linux-gnu/libc-2.19.so
      0x7f6011fd4000     0x7f6011fd8000     0x4000   0x1ba000 /lib/x86_64-linux-gnu/libc-2.19.so
      0x7f6011fd8000     0x7f6011fda000     0x2000   0x1be000 /lib/x86_64-linux-gnu/libc-2.19.so
      0x7f6011fdf000     0x7f6011fe2000     0x3000        0x0 /lib/x86_64-linux-gnu/libdl-2.19.so
      0x7f6011fe2000     0x7f60121e1000   0x1ff000     0x3000 /lib/x86_64-linux-gnu/libdl-2.19.so
      0x7f60121e1000     0x7f60121e2000     0x1000     0x2000 /lib/x86_64-linux-gnu/libdl-2.19.so
      0x7f60121e2000     0x7f60121e3000     0x1000     0x3000 /lib/x86_64-linux-gnu/libdl-2.19.so
      0x7f60121e3000     0x7f6012208000    0x25000        0x0 /lib/x86_64-linux-gnu/libtinfo.so.5.9
      0x7f6012208000     0x7f6012407000   0x1ff000    0x25000 /lib/x86_64-linux-gnu/libtinfo.so.5.9
      0x7f6012407000     0x7f601240b000     0x4000    0x24000 /lib/x86_64-linux-gnu/libtinfo.so.5.9
      0x7f601240b000     0x7f601240c000     0x1000    0x28000 /lib/x86_64-linux-gnu/libtinfo.so.5.9
      0x7f601240c000     0x7f601242f000    0x23000        0x0 /lib/x86_64-linux-gnu/ld-2.19.so
      0x7f6012625000     0x7f601262c000     0x7000        0x0 /usr/lib/x86_64-linux-gnu/gconv/gconv-modules.cache
      0x7f601262e000     0x7f601262f000     0x1000    0x22000 /lib/x86_64-linux-gnu/ld-2.19.so
```

# Via `gdb`

Everything looks correct when the core-dump is generated directly from GDB.

```
$ gdb --batch --ex 'start' --ex 'gcore' -- /bin/sh
Loaded 96 commands.  Type pwndbg [filter] for a list.
Temporary breakpoint 1 at 0x41eab0
Saved corefile core.27569
$ gdb --batch --ex 'vmmap' --ex 'info proc map' -- /bin/bash core.27569
Loaded 96 commands.  Type pwndbg [filter] for a list.

warning: core file may not match specified executable file.
[New LWP 27569]
Core was generated by `/bin/sh'.
Program terminated with signal SIGTRAP, Trace/breakpoint trap.
#0  0x000000000041eab0 in main ()
LEGEND: STACK | HEAP | CODE | DATA | RWX | RODATA
          0x400000           0x4ef000 r-xp    ef000 0      /bin/sh
          0x4ef000           0x6ef000 ---p   200000 ef000  /bin/sh
          0x6ef000           0x6f0000 r--p     1000 ef000  /bin/sh
          0x6f0000           0x6ff000 rw-p     f000 f0000  /bin/sh
    0x7ffff7dda000     0x7ffff7dfd000 r-xp    23000 0      [linker]
    0x7ffff7dda000     0x7ffff7dfd000 r-xp    23000 0      /lib64/ld-linux-x86-64.so.2
    0x7ffff7dfd000     0x7ffff7ffc000 ---p   1ff000 22000  [linker]
    0x7ffff7dfd000     0x7ffff7ffc000 ---p   1ff000 22000  /lib64/ld-linux-x86-64.so.2
    0x7ffff7ffc000     0x7ffff7ffd000 r--p     1000 22000  [linker]
    0x7ffff7ffc000     0x7ffff7ffd000 r--p     1000 22000  /lib64/ld-linux-x86-64.so.2
    0x7ffff7ffd000     0x7ffff7fff000 rw-p     2000 23000  [linker]
    0x7ffff7ffd000     0x7ffff7fff000 rw-p     2000 23000  /lib64/ld-linux-x86-64.so.2
0x100007ffff76fa000 0x100007ffff76fb000 r-xp     1000 0      [vdso]
Mapped address spaces:

          Start Addr           End Addr       Size     Offset objfile
            0x400000           0x4ef000    0xef000        0x0 /bin/bash
            0x6ef000           0x6f0000     0x1000    0xef000 /bin/bash
            0x6f0000           0x6f9000     0x9000    0xf0000 /bin/bash
      0x7ffff75e8000     0x7ffff77a2000   0x1ba000        0x0 /lib/x86_64-linux-gnu/libc-2.19.so
      0x7ffff77a2000     0x7ffff79a2000   0x200000   0x1ba000 /lib/x86_64-linux-gnu/libc-2.19.so
      0x7ffff79a2000     0x7ffff79a6000     0x4000   0x1ba000 /lib/x86_64-linux-gnu/libc-2.19.so
      0x7ffff79a6000     0x7ffff79a8000     0x2000   0x1be000 /lib/x86_64-linux-gnu/libc-2.19.so
      0x7ffff79ad000     0x7ffff79b0000     0x3000        0x0 /lib/x86_64-linux-gnu/libdl-2.19.so
      0x7ffff79b0000     0x7ffff7baf000   0x1ff000     0x3000 /lib/x86_64-linux-gnu/libdl-2.19.so
      0x7ffff7baf000     0x7ffff7bb0000     0x1000     0x2000 /lib/x86_64-linux-gnu/libdl-2.19.so
      0x7ffff7bb0000     0x7ffff7bb1000     0x1000     0x3000 /lib/x86_64-linux-gnu/libdl-2.19.so
      0x7ffff7bb1000     0x7ffff7bd6000    0x25000        0x0 /lib/x86_64-linux-gnu/libtinfo.so.5.9
      0x7ffff7bd6000     0x7ffff7dd5000   0x1ff000    0x25000 /lib/x86_64-linux-gnu/libtinfo.so.5.9
      0x7ffff7dd5000     0x7ffff7dd9000     0x4000    0x24000 /lib/x86_64-linux-gnu/libtinfo.so.5.9
      0x7ffff7dd9000     0x7ffff7dda000     0x1000    0x28000 /lib/x86_64-linux-gnu/libtinfo.so.5.9
      0x7ffff7dda000     0x7ffff7dfd000    0x23000        0x0 /lib/x86_64-linux-gnu/ld-2.19.so
      0x7ffff7ffc000     0x7ffff7ffd000     0x1000    0x22000 /lib/x86_64-linux-gnu/ld-2.19.so
```

# Comparison

What's more is that there's clearly more information in the `gcore` corefile.  

```
$ du -sh corefile.26026 core.27569
15M	corefile.26026
1.4M	core.27569
$ file corefile.26026 core.27569
corefile.26026: ELF 64-bit LSB  core file x86-64, version 1 (SYSV), SVR4-style, from '/bin/sh'
core.27569:     ELF 64-bit LSB  core file x86-64, version 1 (SYSV), SVR4-style, from '/bin/sh'
```

**Comment by zachriggle** [comment]
So this is extra odd, since gcore is just a shell script wrapper around GDB.

**Comment by disconnect3d** [comment]
This has been fixed at some point and I believe we receive whatever info we can from the corefile right now.

This is how it looks on a gcore from bash process:
```
pwndbg> vmmap
LEGEND: STACK | HEAP | CODE | DATA | RWX | RODATA
             Start                End Perm     Size Offset File
    0x5ae172fec000     0x5ae17301b000 r--p    2f000      0 /usr/bin/bash
    0x5ae17301b000     0x5ae1730fa000 ---p    df000  2f000 /usr/bin/bash
    0x5ae1730fa000     0x5ae173134000 ---p    3a000 10e000 /usr/bin/bash
    0x5ae173135000     0x5ae173139000 r--p     4000 148000 /usr/bin/bash
    0x5ae173139000     0x5ae173142000 ---p     9000 14c000 /usr/bin/bash
    0x7e1a50e00000     0x7e1a515ec000 ---p   7ec000      0 /usr/lib/locale/locale-archive
    0x7e1a51600000     0x7e1a51628000 r--p    28000      0 /usr/lib/x86_64-linux-gnu/libc.so.6
    0x7e1a51628000     0x7e1a517bd000 ---p   195000  28000 /usr/lib/x86_64-linux-gnu/libc.so.6
    0x7e1a517bd000     0x7e1a51815000 ---p    58000 1bd000 /usr/lib/x86_64-linux-gnu/libc.so.6
    0x7e1a51815000     0x7e1a51816000 ---p     1000 215000 /usr/lib/x86_64-linux-gnu/libc.so.6
    0x7e1a51816000     0x7e1a5181a000 r--p     4000 215000 /usr/lib/x86_64-linux-gnu/libc.so.6
    0x7e1a5181a000     0x7e1a5181c000 ---p     2000 219000 /usr/lib/x86_64-linux-gnu/libc.so.6
    0x7e1a5191f000     0x7e1a5192d000 r--p     e000      0 /usr/lib/x86_64-linux-gnu/libtinfo.so.6.3
    0x7e1a5192d000     0x7e1a5193e000 ---p    11000   e000 /usr/lib/x86_64-linux-gnu/libtinfo.so.6.3
    0x7e1a5193e000     0x7e1a5194c000 ---p     e000  1f000 /usr/lib/x86_64-linux-gnu/libtinfo.so.6.3
    0x7e1a5194c000     0x7e1a51950000 r--p     4000  2c000 /usr/lib/x86_64-linux-gnu/libtinfo.so.6.3
    0x7e1a51950000     0x7e1a51951000 ---p     1000  30000 /usr/lib/x86_64-linux-gnu/libtinfo.so.6.3
    0x7e1a51960000     0x7e1a51967000 ---p     7000      0 /usr/lib/x86_64-linux-gnu/gconv/gconv-modules.cache
    0x7e1a51969000     0x7e1a5196b000 r--p     2000      0 /usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
    0x7e1a5196b000     0x7e1a51995000 ---p    2a000   2000 /usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
    0x7e1a51995000     0x7e1a519a0000 ---p     b000  2c000 /usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
    0x7e1a519a1000     0x7e1a519a3000 r--p     2000  37000 /usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
    0x7e1a519a3000     0x7e1a519a5000 ---p     2000  39000 /usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
    0x5ae173142000     0x5ae17314d000 ---p     b000      0 load4
    0x5ae173b4e000     0x5ae173b6f000 ---p    21000      0 load5
    0x7e1a5181c000     0x7e1a51829000 ---p     d000      0 load9
    0x7e1a5191c000     0x7e1a5191f000 ---p     3000      0 load10
    0x7e1a51967000     0x7e1a51969000 ---p     2000      0 load14
    0x7ffce5df1000     0x7ffce5e12000 rw-p    21000      0 [stack]
    0x7ffce5f0e000     0x7ffce5f10000 r-xp     2000      0 load19
0xffffffffff600000 0xffffffffff601000 r-xp     1000      0 [vsyscall]
pwndbg> 
```

Closing.
