### ISSUE TITLE
Arguments for commands are evaluated before OnlyWhenRunning decorator

### ISSUE THREAD

**Issue by gsingh93** [pwndbg/pwndbg#1462]
If you start `gdb` but don't run any binary, the following commands will throw exceptions despite being annotated with `@OnlyWhenRunning`:
- telescope
- probeleak
- xinfo
- leakfind

This is because in `Command.invoke` in `pwndbg/commands/__init__.py`, we call `args, kwargs = self.split_args(argument)` and then pass these arguments to the command function.

The issue is that the above methods have an argument with a default register value, i.e. `$sp`, and when this is evaluated an exception is thrown.

The exception comes from the `fix_int_reraise` function, and a more general issue is that there's probably a better way to handle these errors instead of re-raising. We should tell the user more descriptively what the issue is. This can be tested by running something like:
```
pwndbg> xor a a a
Traceback (most recent call last):
  File "/usr/local/google/home/gsgx/tools/pwndbg/pwndbg/commands/__init__.py", line 98, in invoke
    args, kwargs = self.split_args(argument)
  File "/usr/local/google/home/gsgx/tools/pwndbg/pwndbg/commands/__init__.py", line 445, in split_args
    return tuple(), vars(self.parser.parse_args(argv))
  File "/usr/lib/python3.10/argparse.py", line 1838, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python3.10/argparse.py", line 1871, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.10/argparse.py", line 2087, in _parse_known_args
    stop_index = consume_positionals(start_index)
  File "/usr/lib/python3.10/argparse.py", line 2043, in consume_positionals
    take_action(action, args)
  File "/usr/lib/python3.10/argparse.py", line 1932, in take_action
    argument_values = self._get_values(action, argument_strings)
  File "/usr/lib/python3.10/argparse.py", line 2467, in _get_values
    value = self._get_value(action, arg_string)
  File "/usr/lib/python3.10/argparse.py", line 2500, in _get_value
    result = type_func(arg_string)
  File "/usr/local/google/home/gsgx/tools/pwndbg/pwndbg/commands/__init__.py", line 201, in fix_int_reraise
    return fix(*a, reraise=True, **kw)
  File "/usr/local/google/home/gsgx/tools/pwndbg/pwndbg/commands/__init__.py", line 188, in fix
    raise e
  File "/usr/local/google/home/gsgx/tools/pwndbg/pwndbg/commands/__init__.py", line 183, in fix
    return gdb.parse_and_eval(arg)
gdb.error: No symbol table is loaded.  Use the "file" command.

If that is an issue, you can report it on https://github.com/pwndbg/pwndbg/issues
(Please don't forget to search if it hasn't been reported before)
To generate the report and open a browser, you may run `bugreport --run-browser`
PS: Pull requests are welcome
```

**Comment by gsingh93** [comment]
This might be a duplicate of https://github.com/pwndbg/pwndbg/issues/273

**Comment by disconnect3d** [comment]
I closed the old #273 as this probably gives more details already.
