### ISSUE TITLE
Error on starup with Docker ubuntu:20.04 image

### ISSUE THREAD

**Issue by martinclauss** [pwndbg/pwndbg#1539]
Hey there :)

### Description

pwndbg throws an error on startup in Docker with Ubuntu 20.04 image

### Steps to reproduce

host:

```
$ docker run -it --rm ubuntu:20.04 /bin/bash 
```

installation inside Docker:

```
root@bbbb5b1563fb:/# apt update && apt upgrade -y && apt install -y git
[...]
root@bbbb5b1563fb:/# git clone https://github.com/pwndbg/pwndbg
[...]
root@bbbb5b1563fb:/# cd pwndbg
root@bbbb5b1563fb:/pwndbg# ./setup.sh
[...]
+ grep pwndbg /root/.gdbinit
+ echo 'source /pwndbg/gdbinit.py'
```

run pwndbg:

```
root@bbbb5b1563fb:/pwndbg# gdb /bin/ls
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04.1) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
******
Your encoding (ANSI_X3.4-1968) is different than UTF-8. pwndbg might not work properly.
You might try launching gdb with:
    LC_ALL=en_US.UTF-8 PYTHONIOENCODING=UTF-8 gdb
Make sure that en_US.UTF-8 is activated in /etc/locale.gen and you called locale-gen
******
pwndbg: loaded 136 pwndbg commands and 34 shell commands. Type pwndbg [--shell | --all] [filter] for a list.
pwndbg: created $rebase, $ida GDB functions (can be used with print/break)
Traceback (most recent call last):
  File "/pwndbg/gdbinit.py", line 100, in <module>
    import pwndbg  # noqa: F401
  File "/pwndbg/pwndbg/__init__.py", line 79, in <module>
    config_mod.init_params()
  File "/pwndbg/pwndbg/gdblib/config.py", line 114, in init_params
    Parameter(p)
  File "/pwndbg/pwndbg/gdblib/config.py", line 46, in __init__
    self.value = param.value
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
Reading symbols from /bin/ls...
(No debugging symbols found in /bin/ls)
Python Exception <class 'AttributeError'> partially initialized module 'pwndbg' has no attribute 'lib' (most likely due to a circular import): 
------- tip of the day (disable with set show-tips off) -------
Use the canary command to see all stack canary/cookie values on the stack (based on the *usual* stack canary value initialized by glibc)
```

### My setup

- pwndbg from `dev` branch
- Python 3.8.10
- Docker version 20.10.23, build 7155243

### Additional observation

Interestingly, when I run:

```
--- tools/pwndbg ‹dev* ?› » git pull
Already up to date.
--- tools/pwndbg ‹dev* ?› » docker-compose run ubuntu20.04 /bin/bash
Creating pwndbg_ubuntu20.04_run ... done
root@593f76a20f90:/pwndbg# gdb /bin/ls
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04.1) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
pwndbg: loaded 136 pwndbg commands and 37 shell commands. Type pwndbg [--shell | --all] [filter] for a list.
pwndbg: created $rebase, $ida GDB functions (can be used with print/break)
Reading symbols from /bin/ls...
(No debugging symbols found in /bin/ls)
------- tip of the day (disable with set show-tips off) -------
Pwndbg context displays where the program branches to thanks to emulating few instructions into the future. You can disable this with set emulate off which may also speed up debugging
pwndbg> 
```

**it works**!

**Comment by gsingh93** [comment]
Can you try the suggestion in the warning message:
```
******
Your encoding (ANSI_X3.4-1968) is different than UTF-8. pwndbg might not work properly.
You might try launching gdb with:
    LC_ALL=en_US.UTF-8 PYTHONIOENCODING=UTF-8 gdb
Make sure that en_US.UTF-8 is activated in /etc/locale.gen and you called locale-gen
******
```

If you look at the `Dockerfile` in the repo, we set `ENV LANG en_US.utf8`, which seems to be related to the error message:
```
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
```

**Comment by martinclauss** [comment]
FYI: Installation from this release: https://github.com/pwndbg/pwndbg/releases/tag/2022.08.30 commit  `cf2c3eede8f0059236e07857159ece978fd56912` works for me.

https://github.com/pwndbg/pwndbg/releases/tag/2022.12.19 does not work

I'll check out your suggestion!

**Comment by martinclauss** [comment]
this line

https://github.com/pwndbg/pwndbg/blob/2a5f5634444979e9ebe60340a1fd11aae57aa3f3/Dockerfile#LL25C5-L25C86

solved the problem. very strange behavior :)

thanks!

**Comment by gsingh93** [comment]
Thanks for confirming. I think the reason UTF8 needs to be setup correctly is that some config options default to unicode symbols. I'm discussing with others whether we should support falling back to non-unicode symbols in this case instead of throwing an exception.
