### ISSUE TITLE
Reload command fails when run during program debugging

### ISSUE THREAD

**Issue by disconnect3d** [pwndbg/pwndbg#1547]
This actually does not fail the reload process, it still kinda works, but I guess it may not execute everything it was supposed to be executed?

```
pwndbg> reload
pwndbg: loaded 136 pwndbg commands and 49 shell commands. Type pwndbg [--shell | --all] [filter] for a list.
pwndbg: created $rebase, $ida GDB functions (can be used with print/break)
Traceback (most recent call last):
  File "/home/dc/pwndbg/pwndbg/commands/__init__.py", line 184, in __call__
    return self.function(*args, **kwargs)
  File "/home/dc/pwndbg/pwndbg/commands/reload.py", line 30, in reload
    pwndbg.gdblib.events.after_reload()
  File "/home/dc/pwndbg/pwndbg/gdblib/events.py", line 226, in after_reload
    for f in registered[gdb.events.start]:
KeyError: <pwndbg.gdblib.events.StartEvent object at 0x7fffdce4b358>
```

To reproduce: `gdb /bin/ls` + `starti` + `reload`.

**Comment by disconnect3d** [comment]
Here is a patch that fixes this:
```py
diff --git a/pwndbg/gdblib/events.py b/pwndbg/gdblib/events.py
index 1c18221..3abdd8c 100644
--- a/pwndbg/gdblib/events.py
+++ b/pwndbg/gdblib/events.py
@@ -220,15 +220,29 @@ gdb.events.new_objfile.connect(log_objfiles)


 def after_reload(start=True) -> None:
+    """
+    Run registered event hooks after reloading Pwndbg imports
+    """
     if gdb.selected_inferior().pid:
-        for f in registered[gdb.events.stop]:
+        # While we fetch registered hooks via gdb.events.* keys, for start and before_prompt
+        # we have to fetch it differently. This is because we hijack those two attributes of
+        # gdb.events in the global namespace of this file. As a result, when we reload Pwndbg
+        # modules, those attributes gets reassigned to new objects and so using those new
+        # attributes here as keys does not work.
+        for k, v in registered.items():
+            if isinstance(k, StartEvent):
+                start_events = v
+            elif isinstance(k, EventWrapper) and k.name == "before_prompt":
+                before_prompt_events = v
+
+        for f in registered.get(gdb.events.stop):
             f()
-        for f in registered[gdb.events.start]:
+        for f in start_events:
             if start:
                 f()
-        for f in registered[gdb.events.new_objfile]:
+        for f in registered.get(gdb.events.new_objfile):
             f()
-        for f in registered[gdb.events.before_prompt]:
+        for f in before_prompt_events:
             f()
```

However, I am wondering if this is the correct fix as... this all means that the `registered` object IS NOT reloaded/recomputed during the `reload` command and it probably should have been?

**Comment by disconnect3d** [comment]
This eventually means that all global variables that were there before reload, are still there afterwards.

**Comment by gsingh93** [comment]
Not sure if related, but I noticed that my `.gdbinit` config is no longer loaded after reloading.

**Comment by disconnect3d** [comment]
I can't reproduce the reload command failing. However, the global vars are not reloaded.

I tested this by adding a global var to `pwndbg/__init__.py` called `testvar`:

An interesting point here:
```
pwndbg> pi pwndbg.testvar
1
pwndbg> reload
[... - context displayed]
pwndbg> pi pwndbg.testvar
1
pwndbg> pi import pwndbg
pwndbg> pi pwndbg.testvar
2
```

**Comment by disconnect3d** [comment]
Closing in favor of https://github.com/pwndbg/pwndbg/issues/3499
