### ISSUE TITLE
'NoneType' object has no attribute 'start' while thread replace arena?

### ISSUE THREAD

**Issue by yooo1999** [pwndbg/pwndbg#1563]
I use last commit https://github.com/pwndbg/pwndbg/commit/afa96abfa022052adbf39a430a7f353faac32838
I allocated few heap memory and print each time the `thread_arena`
When the memory has been allocated at another arena (maybe because the memory in his arena over) , or maybe extend the arena  I got exception.

The allocation is:
```
python
import gdb
for _  in range(10000):
    gdb.execute('call (void *)malloc(0x10000)')
    print((pwndbg.heap.current.thread_arena)) 
end
```
the exception :
```

Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "/home/USER/pwndbg/pwndbg/heap/ptmalloc.py", line 635, in __str__
    res = [message.hint(prefix % (arena_name)) + str(self.heaps[0])]
  File "/home/USER/pwndbg/pwndbg/heap/ptmalloc.py", line 598, in heaps
    heap = self.active_heap
  File "/home/USER/pwndbg/pwndbg/heap/ptmalloc.py", line 591, in active_heap                                                                                                                                                                      self._active_heap = Heap(self.top, arena=self)
  File "/home/USER/pwndbg/pwndbg/heap/ptmalloc.py", line 371, in __init__
    start = heap_region.start + allocator.heap_info.sizeof
AttributeError: 'NoneType' object has no attribute 'start'
Error while executing Python code.
```

And when I press `arena`  after the thread allocated in another arena that show me the same arena (that strange )

when I press `arenas` after that exception I got:
```

arenas: An unknown error occurred when running this command.
Maybe you can try to determine the libc symbols addresses manually, set them appropriately and re-run this command. For this, see the `heap_config` command output and set the `main_arena`, `mp_`, `global_max_fast`, `tcache` and `thread_arena` addresses.
Traceback (most recent call last):
  File "/home/USER/pwndbg/pwndbg/commands/__init__.py", line 184, in __call__
    return self.function(*args, **kwargs)
  File "/home/USER/pwndbg/pwndbg/commands/__init__.py", line 315, in _OnlyWhenRunning
    return function(*a, **kw)
  File "/home/USER/pwndbg/pwndbg/commands/__init__.py", line 395, in _OnlyWithResolvedHeapSyms
    return _try2run_heap_command(function, a, kw)
  File "/home/USER/pwndbg/pwndbg/commands/__init__.py", line 377, in _try2run_heap_command
    raise err
  File "/home/USER/pwndbg/pwndbg/commands/__init__.py", line 358, in _try2run_heap_command
    return function(*a, **kw)
  File "/home/USER/pwndbg/pwndbg/commands/__init__.py", line 340, in _OnlyWhenHeapIsInitialized
    return function(*a, **kw)
  File "/home/USER/pwndbg/pwndbg/commands/heap.py", line 186, in arenas
    print(ar)
  File "/home/USER/pwndbg/pwndbg/heap/ptmalloc.py", line 635, in __str__
    res = [message.hint(prefix % (arena_name)) + str(self.heaps[0])]
  File "/home/USER/pwndbg/pwndbg/heap/ptmalloc.py", line 598, in heaps
    heap = self.active_heap
  File "/home/USER/pwndbg/pwndbg/heap/ptmalloc.py", line 591, in active_heap
    self._active_heap = Heap(self.top, arena=self)
  File "/home/USER/pwndbg/pwndbg/heap/ptmalloc.py", line 371, in __init__
    start = heap_region.start + allocator.heap_info.sizeof
AttributeError: 'NoneType' object has no attribute 'start'

> /home/USER/pwndbg/pwndbg/heap/ptmalloc.py(371)__init__()
-> start = heap_region.start + allocator.heap_info.sizeof
```
So I think the problem is the pwndbg doesn't know how to "refresh" the arena

**Comment by CptGibbon** [comment]
Is there a difference if you step a single instruction before trying the `arena` or `arenas` commands?
Since the allocations are being made via GDB's `call` command pwndbg might not get the opportunity to update.

**Comment by yooo1999** [comment]
which kind of instruction do you want me to try ?

**Comment by CptGibbon** [comment]
Just step an instruction with GDB's `si` command.

**Comment by disconnect3d** [comment]
Can you provide a minimal C example that can be used to reproduce this issue? I tried your Python GDB script in a debug session of the /bin/ls binary after executing `entry` command, but it just works for me and do not crash.

**Comment by yooo1999** [comment]
@disconnect3d That was multithreaded application, I will try to make a sample code

**Comment by disconnect3d** [comment]
@yooo1999 Ping

**Comment by disconnect3d** [comment]
I can reproduce this issue on a /bin/ls binary - it still persists and it actually comes from us caching the results of some calls. If you do `memoize off`, then the command seems to work fine.

It may be that this happens because we cache the results of `pwndbg.gdblib.vmmap.find(addr)`. In here, when we call malloc in a loop and then try to `print((pwndbg.heap.current.thread_arena))`, the `vmmap.find` result is cached and results `None` which is not the correct result.

**Comment by disconnect3d** [comment]
Potential solutions for this could be:
1. Check if there is some "call hook" in GDB, but likely there is not or/and it is not present in older GDBs. If there is: we could invalidate caches there? But this may not solve other cases like this.
2. Investigate if there is a way to detect that we are executing user's script and not Pwndbg hooks or single commands in CLI: we could then not use cached values for such calls.
3. Simply instrument users to disable caching in such cases and offer them a decorator to do that? But this may still not be so obvious and my be inconvenient.
4. Override `gdb.execute` so any calls to it invalidates caches. Alternatively, do that only for certain calls, though it may be hard to tell which ones.


@gsingh93 Thoughts?

**Comment by gsingh93** [comment]
> Override gdb.execute so any calls to it invalidates caches. Alternatively, do that only for certain calls, though it may be hard to tell which ones.

This was my first thought before even reading your comment. For a while now, I've wanted us to remove a majority of the direct calls to `gdb.execute()` and put them behind some other function, i.e. instead of `gdb.execute('info sharelibrary')` we have an `info_sharedlibrary()` function that calls it.

The original motivation for doing this was just readability and better type checking, but it would be useful here too: if we move all of our direct calls to `gdb.execute` to other functions, we can memoize those functions themselves. Then we can make any call to `gdb.execute` invalidate the cache, and it should only affect call sites where the parent function wasn't cached.

**Comment by disconnect3d** [comment]
Fixed in https://github.com/pwndbg/pwndbg/pull/3813. Requires GDB >= 13.
