### ISSUE TITLE
No such file or directory When tried to download libc

### ISSUE THREAD

**Issue by yooo1999** [pwndbg/pwndbg#1591]
I used last commit a3dcfaa139b1e5e4cd23848f9a1b754c9de0fc5b
I attach to process with gdb-multiarch (using `pwndbg` )  and I set a sysroot for all the binaries of this device in my PC 

`set sysroot /mnt/hgfs/sysroot/`

When I tried to press `vis` I see pwndbg tried to download the libc from the device (to analyze the heap).
The prbolem is , pwndbg tried to download the libc from the sysroot (in my PC)  and that failed 
```


Traceback (most recent call last):
  File "/home/USER/pwndbg/pwndbg/commands/__init__.py", line 184, in __call__
    return self.function(*args, **kwargs)
  File "/home/USER/pwndbg/pwndbg/commands/__init__.py", line 320, in _OnlyWhenRunning
    return function(*a, **kw)
  File "/home/USER/pwndbg/pwndbg/commands/__init__.py", line 420, in _OnlyWithResolvedHeapSyms
    return _try2run_heap_command(function, a, kw)
  File "/home/USER/pwndbg/pwndbg/commands/__init__.py", line 388, in _try2run_heap_command
    raise err
  File "/home/USER/pwndbg/pwndbg/commands/__init__.py", line 363, in _try2run_heap_command
    return function(*a, **kw)
  File "/home/USER/pwndbg/pwndbg/commands/__init__.py", line 345, in _OnlyWhenHeapIsInitialized
    return function(*a, **kw)
  File "/home/USER/pwndbg/pwndbg/commands/heap.py", line 737, in vis_heap_chunks
    arena = allocator.thread_arena
  File "/home/USER/pwndbg/pwndbg/heap/ptmalloc.py", line 1450, in thread_arena
    if self.main_arena.address != pwndbg.heap.current.main_arena.next or self.multithreaded:
  File "/home/USER/pwndbg/pwndbg/heap/ptmalloc.py", line 1299, in main_arena
    section = pwndbg.glibc.dump_elf_data_section()
  File "/home/USER/pwndbg/pwndbg/gdblib/proc.py", line 143, in wrapper
    return func(*a, **kw)
  File "/home/USER/pwndbg/pwndbg/glibc.py", line 88, in dump_elf_data_section
    return pwndbg.gdblib.elf.dump_section_by_name(libc_filename, ".data")
  File "/home/USER/pwndbg/pwndbg/gdblib/elf.py", line 181, in dump_section_by_name
    local_path = pwndbg.gdblib.file.get_file(filepath)
  File "/home/USER/pwndbg/pwndbg/gdblib/file.py", line 72, in get_file
    raise OSError("Could not download remote file %r:\n" "Error: %s" % (path, error))
OSError: Could not download remote file '/mnt/hgfs/sysroot/lib/libc.so.6':
Error: Remote I/O error: No such file or directory
```

The problem is that GDB doesn't support to run 
`remote get "/mnt/hgfs/sysroot/lib/libc.so.6" "/tmp/tmaaa"` if that file is located in my PC (because of `sysroot` )

**Comment by lebr0nli** [comment]
Hi, thanks for the bug report.

> The problem is that GDB doesn't support to run
> `remote get "/mnt/hgfs/sysroot/lib/libc.so.6" "/tmp/tmaaa"` if that file is located in my PC (because of `sysroot` )

Can your PC access `/mnt/hgfs/sysroot/lib/libc.so.6` locally?
If it can, the temporary workaround might be:
```diff
--- a/pwndbg/gdblib/file.py
+++ b/pwndbg/gdblib/file.py
@@ -69,7 +69,13 @@ def get_file(path: str) -> str:
                 error = str(e)

             if error:
-                raise OSError("Could not download remote file %r:\n" "Error: %s" % (path, error))
+                print(
+                    message.warn(
+                        "pwndbg.gdblib.file.get(%s) returns local path as we can't download file from remote server"
+                        % path
+                    )
+                )
+                local_path = path
         else:
             print(
                 message.warn(
```

----

And I guess we will need to find a way to determine should or shouldn’t download the file in the future when we are connecting to a gdbserver, since some paths might still point to the local path even if it’s connecting to a remote server.
(for example, when we trying to `pwndbg.gdblib.file.get_file(pwndbg.gdblib.proc.exe)`)
cc: @disconnect3d

**Comment by yooo1999** [comment]
Yes my PC can access to `/mnt/hgfs/sysroot/lib/libc.so.6`  locally. 
The workaround is work.

**Comment by disconnect3d** [comment]
This should be fixed with https://github.com/pwndbg/pwndbg/pull/1593. Please let us know if it works for you now @yooo1999
