### ISSUE TITLE
patch_list and patch_revert crashes

### ISSUE THREAD

**Issue by disconnect3d** [pwndbg/pwndbg#1749]
```
pwndbg> patch_list
No patches to list
pwndbg> patch $rip nop
pwndbg> patch_list
Patches:
Traceback (most recent call last):
  File "/root/pwndbg/pwndbg/commands/__init__.py", line 184, in __call__
    return self.function(*args, **kwargs)
  File "/root/pwndbg/pwndbg/commands/__init__.py", line 331, in _OnlyWhenRunning
    return function(*a, **kw)
  File "/root/pwndbg/pwndbg/commands/patch.py", line 76, in patch_list
    message.warning("%#x:" % addr),
AttributeError: module 'pwndbg.color.message' has no attribute 'warning'
```

**Comment by disconnect3d** [comment]
The `patch_revert $rip` command also crashes:
```
pwndbg> patch_revert $rip
Traceback (most recent call last):
  File "/root/pwndbg/pwndbg/commands/__init__.py", line 184, in __call__
    return self.function(*args, **kwargs)
  File "/root/pwndbg/pwndbg/commands/__init__.py", line 331, in _OnlyWhenRunning
    return function(*a, **kw)
  File "/root/pwndbg/pwndbg/commands/patch.py", line 53, in patch_revert
    old, _new = patches[address]
KeyError: <gdb.Value object at 0x7f1bc29faff0>
```
