### ISSUE TITLE
"'function' object has no attribute '_reset'" in `pwndbg/pwndbg/color/syntax_highlight.py`

### ISSUE THREAD

**Issue by sci-42ver** [pwndbg/pwndbg#1756]
### Description

using latest dev branch, with `set syntax-highlight-style solarized-light` param, above error will be thrown

```bash
$ gdb ~/matrix-matrix-multiply/build/src/dgemm -ex 'start' -ex ''
pwndbg: loaded 141 pwndbg commands and 42 shell commands. Type pwndbg [--shell | --all] [filter] for a list.
pwndbg: created $rebase, $ida GDB functions (can be used with print/break)
Traceback (most recent call last):
  File "/home/czg/pwndbg/pwndbg/gdblib/config.py", line 93, in __get_set_string_gdb_gte_9
    trigger()
  File "/home/czg/pwndbg/pwndbg/color/syntax_highlight.py", line 37, in check_style
    get_highlight_source._reset()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'function' object has no attribute '_reset'
/home/czg/.gdbinit:19: Error in sourced command file:
Error occurred in Python: 'function' object has no attribute '_reset'
```

when I read `$ git log -p pwndbg/commands/context.py` I found nothing about `_reset`, but the error only exists after I upgrade python from `3.10` to `3.11.3` and pwndbg recently.

**Comment by disconnect3d** [comment]
The `_reset` was a method to clear a cache for a given function; this method name was changed with recent caching rewrite.

**Comment by disconnect3d** [comment]
This should be changed as:
```diff
- get_highlight_source._reset()
+ get_highlight_source.cache.clear()
```

**Comment by disconnect3d** [comment]
https://github.com/pwndbg/pwndbg/pull/1757 should fix it

**Comment by disconnect3d** [comment]
Fwiw there are no other instances of this issue (after fixing this one):
```
dc@dev-vps:~/pwndbg$ rg '\._reset'
dc@dev-vps:~/pwndbg$
```

**Comment by disconnect3d** [comment]
This has been fixed in https://github.com/pwndbg/pwndbg/pull/1757
