### ISSUE TITLE
Exception occurred: context: name 'RISCV_GRP_CALL' is not defined (<class 'NameError'>)

### ISSUE THREAD

**Issue by JANlittle** [pwndbg/pwndbg#1790]
### Description
When I tried to debug a riscv-64 program, pwndbg immediately prompted this error:
```
Exception occurred: context: name 'RISCV_GRP_CALL' is not defined (<class 'NameError'>)
```
So I immediately input `set exception-verbose on` to print the full Traceback below:
```
Traceback (most recent call last):
  File "/root/pwndbg/pwndbg/commands/__init__.py", line 184, in __call__
    return self.function(*args, **kwargs)
  File "/root/pwndbg/pwndbg/commands/__init__.py", line 331, in _OnlyWhenRunning
    return function(*a, **kw)
  File "/root/pwndbg/pwndbg/commands/context.py", line 399, in context
    func(
  File "/root/pwndbg/pwndbg/commands/context.py", line 507, in context_regs
    regs = get_regs()
  File "/root/pwndbg/pwndbg/commands/context.py", line 581, in get_regs
    desc = pwndbg.chain.format(value)
  File "/root/pwndbg/pwndbg/chain.py", line 143, in format
    enhanced = pwndbg.enhance.enhance(chain[-2] + offset, code=code, safe_linking=safe_linking)
  File "/root/pwndbg/pwndbg/enhance.py", line 90, in enhance
    instr = pwndbg.disasm.one(value)
  File "/root/pwndbg/pwndbg/disasm/__init__.py", line 172, in one
    for insn in get(address, 1):
  File "/root/pwndbg/pwndbg/disasm/__init__.py", line 196, in get
    i = get_one_instruction(address)
  File "/root/pwndbg/pwndbg/lib/cache.py", line 137, in decorator
    value = func(*a, **kw)
  File "/root/pwndbg/pwndbg/disasm/__init__.py", line 160, in get_one_instruction
    pwndbg.disasm.arch.DisassemblyAssistant.enhance(ins)
  File "/root/pwndbg/pwndbg/disasm/arch.py", line 46, in enhance
    enhancer.enhance_conditional(instruction)
  File "/root/pwndbg/pwndbg/disasm/arch.py", line 65, in enhance_conditional
    c = self.condition(instruction)
  File "/root/pwndbg/pwndbg/disasm/riscv.py", line 48, in condition
    if RISCV_GRP_CALL in instruction.groups:
NameError: name 'RISCV_GRP_CALL' is not defined
```
This seems to be due to the incomplete support of pwndbg for riscv, and I have ensured that my pwndbg is the latest version.
### Steps to reproduce
Just simply debug startup with qemu:
```
qemu-riscv64 -g 1234 ./exposed
gdb-multiarch ./exposed

pwndbg> set arch riscv:rv64
pwndbg> target remote 127.0.0.1:1234
```

### My setup

```
Platform: Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
OS: Ubuntu 22.04.1 LTS
OS ABI: #1 SMP Fri Jan 27 02:56:13 UTC 2023
Architecture: x86_64
Endian: little
Charset: utf-8
Width: 92
Height: 26
Gdb:      12.1
Python:   3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0]
Pwndbg:   2023.03.19 build: de4acb2
Capstone: 5.0.1280
Unicorn:  2.0.1
This GDB was configured as follows:
   configure --host=x86_64-linux-gnu --target=x86_64-linux-gnu
             --with-auto-load-dir=$debugdir:$datadir/auto-load
             --with-auto-load-safe-path=$debugdir:$datadir/auto-load
             --with-expat
             --with-gdb-datadir=/usr/share/gdb (relocatable)
             --with-jit-reader-dir=/usr/lib/gdb (relocatable)
             --without-libunwind-ia64
             --with-lzma
             --with-babeltrace
             --with-intel-pt
             --with-mpfr
             --with-xxhash
             --with-python=/usr (relocatable)
             --with-python-libdir=/usr/lib (relocatable)
             --with-debuginfod
             --without-guile
             --enable-source-highlight
             --with-separate-debug-dir=/usr/lib/debug (relocatable)
             --with-system-gdbinit=/etc/gdb/gdbinit
             --with-system-gdbinit-dir=/etc/gdb/gdbinit.d

("Relocatable" means the directory can be moved with the GDB installation
tree, and GDB will still find it.)

```

**Comment by JANlittle** [comment]
Here is the binary:
[exposed.zip](https://github.com/pwndbg/pwndbg/files/12016843/exposed.zip)

**Comment by disconnect3d** [comment]
Hi, please re-run `./setup.sh` or re-install dependencies from `requirements.txt`.

We recently improved the support for RISC-V which also updated the Capstone dependency to a newer version: https://github.com/pwndbg/pwndbg/commit/a6cc19aa5ce36147c80281923bf3603ee40743ea#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552L1 and that newer version adds that constant.

**Comment by disconnect3d** [comment]
Alternatively you can also just install this single dependency via `python3 -m pip install capstone==5.0.0rc4`.

**Comment by disconnect3d** [comment]
> Hi, please re-run `./setup.sh` or re-install dependencies from `requirements.txt`.

Oh also please note that if you do that, the newest dev branch will create a [Python virtual environment](https://docs.python.org/3/library/venv.html) in `<pwndbg-dir>/.venv/` and install all dependencies there. This is a superior solution to what we used previously which was installing Python dependencies to the system Python packages (which could break your system if you were really unlucky).

**Comment by disconnect3d** [comment]
I am going to close this as simply updating deps should fix this. Please re-open or create a new issue if this doesn't fix your case!

**Comment by JANlittle** [comment]
It works! Thanks for your help🥰
