### ISSUE TITLE
Support tracking function calls made through the PLT/GOT

### ISSUE THREAD

**Issue by mbrla0** [pwndbg/pwndbg#1958]
## Motivation
When analyzing the behavior of dynamically linked programs, it's often interesting to know which parts of it interact with functions provided by library code[^1], as well as if the entry points to these external functions may be changed in some way. For many binaries, especially those built to be position independent[^2], this information may be acquired by inspecting and keeping track of accesses to entries in the Procedure Linkage Table (PLT) and the Global Offset Table (GOT).

[^1]: And how code inside libraries interacts with functions provided by the libraries they themselves depend on, and so on.
[^2]: Including, but is not limited to, most shared libraries, as well as executables built to make use of ASLR.

The PLT and the GOT are sections designed to allow efficient dynamic symbol resolution, at runtime or at load time, for position independent code. The technique that makes use of them does this by moving dynamic symbol references out of the text sections and into the tables, where each entry corresponds to a different symbol, and making it so that code in the text sections references the entries in the tables instead of the symbols directly[^3]. The actual runtime addresses of each of the dynamic symbols and the branch targets for the function calls based on them are stored in the tables.

[^3]: Referencing data in the tables can be done by means of relative addressing, and thus the instructions in the text sections need not be changed to be able to reference external symbols. This also allows for the text sections to be shared between all running instances of the program, which is one of the reasons why this technique is interesting in terms of memory efficiency.

Combined with this, it used to be common practice that the binding of symbols for function calls was done lazily, such that the function pointer would be initialized to the dynamic linker resolver, and, at the first call, the symbol would be resolved and that function pointer would be overwritten with the real address of the function. Predictably, using this method requires that the pages on which these function pointers reside be kept writable for at least as long as there are symbols still left to resolve, which, in practice, almost always means these pages are kept writable for the whole lifetime of the program. This means that, when being used by programs or libraries that do lazy binding, the tables can provide an attacker with an interesting vector with which to hijack execution.

While lazy binding has been falling out of favor, there should still be plenty of programs and libraries in which it is still used. And, so, I think implementing this might be interesting.

## Proposed Solution
Add two new commands that enable and disable tracking, and one or more commands to query information, though I'm not entirely sure how these should look like. Tracking could be done by means of watching for accesses to the addresses of entries in the PLT/GOT that correspond to branch target addresses. The location of which, for ELF, can be retrieved by reading the data from the segment marked with `PT_DYNAMIC`, more specifically, the dynamic array entries marked `DT_PLTGOT` and `DT_JMPREL`.

Watching accesses may be slow, so another possibility that can be considered for the mechanism by which accesses may be logged - although more experimental in nature and certainly not as simple to implement - would be to map executable pages owned by pwndbg to the address space of the executing program and change the entries in the PLT to branch to snippets of code that would write information about the running context into a memory region that could later be read from by pwndbg. These snippets would be JIT compiled for the current architecture by pwndbg and written to the page.

## Additional Context
There already is code in pwndbg - specifically, in `pwndbg/commands/got.py` - that deals with the problem of discovering the GOT for a given ELF image. However, the code has a major shortcoming in that it derives that information from the entries in the section header, rather than the ones in the `ST_DYNAMIC` segment, that `ld.so` uses. Meaning that there are valid binaries with a GOT that the existing code will nonetheless fail to read the it from. 

While there is an option that makes `readelf` use the `ST_DYNAMIC` segment that could be used to get around this, I'm not sure how much better that is as opposed to just parsing these fields from the ELF image ourselves.

**Comment by mbrla0** [comment]
I plan to have a PR up, or at least a draft, implementing this, in a few days at most.

**Comment by mbrla0** [comment]
Interestingly, even the existing implementation in `pwndbg/commands/got.py`, that goes out of its way to support cases where the `vmmap` is invalid - specifically mentioning QEMU -, will still break if QEMU reports a `vmmap` where no entries have the same name as the original program image. This is the case for the main docker image, where QEMU calls it `main.exe`, which makes the following excerpt always fail:

```py
    # The following code is inspired by the "got" command of https://github.com/bata24/gef/blob/dev/gef.py by @bata24, thank you!
    # TODO/FIXME: Maybe a -v option to show more information will be better        
    outputs = []                                                                   
    if path == pwndbg.gdblib.proc.exe:                                             
        bin_base_offset = pwndbg.gdblib.proc.binary_base_addr if "PIE enabled" in pie_status else 0
    else:                                                                          
        # TODO/FIXME: Is there a better way to get the base address of the loaded shared library?
        # I guess parsing the vmmap result might also work, but what if it's not reliable or not available? (e.g. debugging with qemu-user)
        text_section_addr = pwndbg.gdblib.info.parsed_sharedlibrary()[path][0]  
        with open(local_path, "rb") as f:                                          
            bin_base_offset = (                                                    
                text_section_addr - ELFFile(f).get_section_by_name(".text").header["sh_addr"]
            )                                                                      
            print(bin_base_offset)
```

This is due to the fact that the method implementing the `pwndbg.gdblib.proc.binary_base_addr` property will end up raising an exception when the `vmmap` does not contain an entry whose name is the same as `pwndbg.gdblib.proc.exe`:

```
pwndbg> pi pwndbg.gdblib.proc.binary_base_addr
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/pwndbg/pwndbg/lib/cache.py", line 138, in decorator
    value = func(*a, **kw)
  File "/pwndbg/pwndbg/gdblib/proc.py", line 100, in binary_base_addr
    return self.binary_vmmap[0].start
IndexError: tuple index out of range
Error while executing Python code.
```

I'm wondering if for my implementation I should look for a way that `vmmap`s could be avoided entirely, or if we should just embrace them, since the current GOT-related code already requires a somewhat well-formed one to be available anyway.
