### ISSUE TITLE
Missing psutil

### ISSUE THREAD

**Issue by mauvehed** [pwndbg/pwndbg#197]
**OSX 10.12.4, python 2.7.12, gdb 7.12.1 (installed from brew)**

When trying to run 'gdb':

```
Traceback (most recent call last):
  File "/Users/mauvehed/gitwork/mauvehed/pwndbg/gdbinit.py", line 36, in <module>
    import pwndbg # isort:skip
  File "/Users/mauvehed/gitwork/mauvehed/pwndbg/pwndbg/__init__.py", line 12, in <module>
    import pwndbg.android
  File "/Users/mauvehed/gitwork/mauvehed/pwndbg/pwndbg/android.py", line 12, in <module>
    import pwndbg.file
  File "/Users/mauvehed/gitwork/mauvehed/pwndbg/pwndbg/file.py", line 20, in <module>
    import pwndbg.qemu
  File "/Users/mauvehed/gitwork/mauvehed/pwndbg/pwndbg/qemu.py", line 14, in <module>
    import psutil
ImportError: No module named psutil
(gdb) quit
```

```
pip install psutil
Requirement already satisfied: psutil in /usr/local/lib/python3.5/site-packages
```

```
pip2.7 install psutil
Requirement already satisfied: psutil in /usr/local/lib/python2.7/site-packages
```

**Comment by mauvehed** [comment]
So I figured this was a result of gdb using the wrong python, which it is. Not only do I have python from brew, I also have the original OSX python, which is located under /System/Library/Frameworks/Python.framework/Versions/2.7/

Trying "easy_install pip" did not result in the system python installing pip. Eventually I fixed this with

`sudo /System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7 -m ensurepip --upgrade`

Note that "sudo -H" may be required due to permission issues after install as root.
