### ISSUE TITLE
Reverse BTS replay causes unhandled exception

### ISSUE THREAD

**Issue by ghost** [pwndbg/pwndbg#1992]
### Steps to reproduce
```
$ cat sigsegv.c
int main() {
  (*(int*)0)++;
}
$ cat .gdbinit
break main
commands
  record btrace bts
  # do not add 'continue' in a commands block without the deadlock patch
end
set exception-verbose on
run
$ gcc -O0 sigsegv.c -o sigsegv
$ gdb -ex 'source ./.gdbinit' -- sigsegv
<...lines omitted...>
```

<details>
<summary>Continue manually until segfault, then reverse execution:</summary>

```
pwndbg> reverse-next

Breakpoint 1, 0x000055555555511d in main ()
The process is already being recorded.  Use "record stop" to stop recording first.
'context': Print out the current register, instruction, and stack context.
Traceback (most recent call last):
  File "/home/inty/pwndbg/pwndbg/commands/__init__.py", line 190, in __call__
    return self.function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inty/pwndbg/pwndbg/commands/__init__.py", line 346, in _OnlyWhenRunning
    return function(*a, **kw)
           ^^^^^^^^^^^^^^^^^^
  File "/home/inty/pwndbg/pwndbg/commands/context.py", line 404, in context
    func(
  File "/home/inty/pwndbg/pwndbg/commands/context.py", line 512, in context_regs
    regs = get_regs()
           ^^^^^^^^^^
  File "/home/inty/pwndbg/pwndbg/commands/context.py", line 586, in get_regs
    desc = pwndbg.chain.format(value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inty/pwndbg/pwndbg/chain.py", line 116, in format
    chain = get(value, limit, offset, hard_stop, hard_end, safe_linking=safe_linking)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inty/pwndbg/pwndbg/chain.py", line 68, in get
    address = address + offset
              ~~~~~~~~^~~~~~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/inty/pwndbg/pwndbg/gdblib/prompt.py", line 77, in prompt_hook
    pwndbg.commands.context.context()
  File "/home/inty/pwndbg/pwndbg/commands/__init__.py", line 193, in __call__
    pwndbg.exception.handle(self.function.__name__)
  File "/home/inty/pwndbg/pwndbg/exception.py", line 113, in handle
    print_exception(exception_msg)
  File "/home/inty/pwndbg/pwndbg/exception.py", line 33, in print_exception
    if not isinstance(_rich_console, Ellipsis):  # type: ignore[arg-type]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: isinstance() arg 2 must be a type, a tuple of types, or a union
pwndbg>
```

</details>

### My setup
Arch Linux
```
Gdb:      13.2
Python:   3.11.6 (main, Nov 14 2023, 09:36:21) [GCC 13.2.1 20230801]
Pwndbg:   2023.07.17 build: 77516a2
Capstone: 5.0.1280
Unicorn:  2.0.1
```

**Comment by ghost** [comment]
The documentation does say "variables and registers are not available during reverse execution," but RIP at least seems to be available in vanilla gdb.

**Comment by disconnect3d** [comment]
Ugh, the actual printing of exception failed to print it due to a bug here... my bad..:

```
  File "/home/inty/pwndbg/pwndbg/exception.py", line 33, in print_exception
    if not isinstance(_rich_console, Ellipsis):  # type: ignore[arg-type]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: isinstance() arg 2 must be a type, a tuple of types, or a union
```

Tbh I never used GDB's reverse execution. I only used RR https://rr-project.org/ which worked fine with Pwndbg. You should probably try to use it instead

**Comment by disconnect3d** [comment]
The exception printing bug was fixed in https://github.com/pwndbg/pwndbg/pull/1994

**Comment by disconnect3d** [comment]
Re:
```
  File "/home/inty/pwndbg/pwndbg/commands/context.py", line 512, in context_regs
    regs = get_regs()
           ^^^^^^^^^^
  File "/home/inty/pwndbg/pwndbg/commands/context.py", line 586, in get_regs
    desc = pwndbg.chain.format(value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inty/pwndbg/pwndbg/chain.py", line 116, in format
    chain = get(value, limit, offset, hard_stop, hard_end, safe_linking=safe_linking)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/inty/pwndbg/pwndbg/chain.py", line 68, in get
    address = address + offset
              ~~~~~~~~^~~~~~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
```

I bet we try to print an unavailable register value here, to be debugged

**Comment by ghost** [comment]
> I only used RR [rr-project.org](https://rr-project.org/) which worked fine with Pwndbg. You should probably try to use it instead

At the moment I was opening this issue, I was trying to Do It Live and also had issues with `rr` (I got it to work since, and changed my workflow around that).

> I bet we try to print an unavailable register value here, to be debugged

Basically, yeah, plus gdb doesn't let us map memory at all while reverse executing, pwndbg basically encounters a lot of `None`s and breaks down in a lot of places.

I did run the simple test case above a few times and basically tried my best to patch up the most obvious points of failure. If you think this is worth the time, I could whip up a PR. (Do note that, for what it's worth, gdb's native replay (`replay full`) seems to work perfectly well with pwndbg.)

**Comment by disconnect3d** [comment]
Ideally, we want to support all possible edge cases when working with GDB, so if u do want to make it work, please do so.

On the other hand that's probably the first time someone reports this (unless I am mistaken), so idk if its that valuable considering that this mode is not so great.
