### ISSUE TITLE
Error in got and checksec

### ISSUE THREAD

**Issue by OdanBroder** [pwndbg/pwndbg#2119]
```
pwndbg> got -a
Filtering out read-only entries (display them with -r or --show-readonly)

Traceback (most recent call last):
  File "/home/syjoon/pwndbg-src/pwndbg/commands/__init__.py", line 196, in __call__
    return self.function(*args, **kwargs)
  File "/home/syjoon/pwndbg-src/pwndbg/commands/__init__.py", line 356, in _OnlyWhenRunning
    return function(*a, **kw)
  File "/home/syjoon/pwndbg-src/pwndbg/commands/got.py", line 89, in got
    _got(pwndbg.gdblib.proc.exe, accept_readonly, symbol_filter)
  File "/home/syjoon/pwndbg-src/pwndbg/commands/got.py", line 118, in _got
    relro_status = pwndbg.wrappers.checksec.relro_status(local_path)
  File "/home/syjoon/pwndbg-src/pwndbg/commands/__init__.py", line 261, in _OnlyWithFile
    return function(*a, **kw)
  File "/home/syjoon/pwndbg-src/pwndbg/wrappers/__init__.py", line 35, in _OnlyWithCommand
    return function(*a, **kw)
  File "/home/syjoon/pwndbg-src/pwndbg/wrappers/checksec.py", line 30, in relro_status
    out = get_raw_out(local_path)
  File "/home/syjoon/pwndbg-src/pwndbg/commands/__init__.py", line 261, in _OnlyWithFile
    return function(*a, **kw)
  File "/home/syjoon/pwndbg-src/pwndbg/wrappers/__init__.py", line 35, in _OnlyWithCommand
    return function(*a, **kw)
  File "/home/syjoon/pwndbg-src/pwndbg/lib/cache.py", line 141, in decorator
    value = func(*a, **kw)
  File "/home/syjoon/pwndbg-src/pwndbg/wrappers/checksec.py", line 17, in get_raw_out
    return pwndbg.wrappers.call_cmd(get_raw_out.cmd + ["--file=" + local_path])
  File "/home/syjoon/pwndbg-src/pwndbg/wrappers/__init__.py", line 43, in call_cmd
    return subprocess.check_output(cmd, stderr=STDOUT).decode("utf-8")
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'checksec'

> /usr/lib/python3.10/subprocess.py(1863)_execute_child()
-> raise child_exception_type(errno_num, err_msg, err_filename)
(Pdb) 
```
```

pwndbg> checksec
Traceback (most recent call last):
  File "/home/syjoon/pwndbg-src/pwndbg/commands/__init__.py", line 196, in __call__
    return self.function(*args, **kwargs)
  File "/home/syjoon/pwndbg-src/pwndbg/commands/__init__.py", line 261, in _OnlyWithFile
    return function(*a, **kw)
  File "/home/syjoon/pwndbg-src/pwndbg/commands/checksec.py", line 24, in checksec
    output = pwndbg.wrappers.checksec.get_raw_out(pwndbg.gdblib.file.get_proc_exe_file())
  File "/home/syjoon/pwndbg-src/pwndbg/commands/__init__.py", line 261, in _OnlyWithFile
    return function(*a, **kw)
  File "/home/syjoon/pwndbg-src/pwndbg/wrappers/__init__.py", line 35, in _OnlyWithCommand
    return function(*a, **kw)
  File "/home/syjoon/pwndbg-src/pwndbg/lib/cache.py", line 141, in decorator
    value = func(*a, **kw)
  File "/home/syjoon/pwndbg-src/pwndbg/wrappers/checksec.py", line 17, in get_raw_out
    return pwndbg.wrappers.call_cmd(get_raw_out.cmd + ["--file=" + local_path])
  File "/home/syjoon/pwndbg-src/pwndbg/wrappers/__init__.py", line 43, in call_cmd
    return subprocess.check_output(cmd, stderr=STDOUT).decode("utf-8")
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'checksec'

> /usr/lib/python3.10/subprocess.py(1863)_execute_child()
-> raise child_exception_type(errno_num, err_msg, err_filename)
(Pdb)
```

My version:
```
pwndbg> version
Gdb:      12.1
Python:   3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
Pwndbg:   2024.02.14 build: 385e63f6
Capstone: 5.0.1280
Unicorn:  2.0.1
```

How can I fix it

**Comment by disconnect3d** [comment]
I believe setup should install it out of the box. Did u run setup.sh? What is in `/home/syjoon/pwndbg-src/.venv/bin`?

**Comment by OdanBroder** [comment]
I have fixed it, it is my carelessness
thank you very much
