### ISSUE TITLE
gdblib/qemu.py is_qemu() function breaks remote debugging 

### ISSUE THREAD

**Issue by fidgetingbits** [pwndbg/pwndbg#2195]
This is one of the bugs that lead me to creating a lazy-loadable gdbinit.py on nix fwiw. Worth noting that this will reliably hit the first issue that PR #1755 fixes, but the delayed event handling that PR adds doesn't change anything. Since they seem only tangentially related, I'm filing a new issue.

While remotely attaching to gdbserver in a docker container I always hit the following:

```
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /nix/store/xdgadrl8zmgy4fdxvhdnvnrz2dh5j22f-pwndbg/share/pwndbg/pwndbg/gdblib/events.py:124 in   │
│ caller                                                                                           │
│                                                                                                  │
│   121 │   │   try:                                                                               │
│   122 │   │   │   # Don't pass the event along to the decorated function.                        │
│   123 │   │   │   # This is because there are functions with multiple event decorators           │
│ ❱ 124 │   │   │   func()                                                                         │
│   125 │   │   except Exception as e:                                                             │
│   126 │   │   │   import pwndbg.exception                                                        │
│   127                                                                                            │
│                                                                                                  │
│ /nix/store/xdgadrl8zmgy4fdxvhdnvnrz2dh5j22f-pwndbg/share/pwndbg/pwndbg/gdblib/hooks.py:26 in     │
│ update_arch                                                                                      │
│                                                                                                  │
│   23 @pwndbg.gdblib.events.stop                                                                  │
│   24 @pwndbg.gdblib.events.new_objfile                                                           │
│   25 def update_arch() -> None:                                                                  │
│ ❱ 26 │   arch_mod.update()                                                                       │
│   27                                                                                             │
│   28                                                                                             │
│   29 @pwndbg.gdblib.events.new_objfile                                                           │
│                                                                                                  │
│ /nix/store/xdgadrl8zmgy4fdxvhdnvnrz2dh5j22f-pwndbg/share/pwndbg/pwndbg/gdblib/arch.py:86 in      │
│ update                                                                                           │
│                                                                                                  │
│   83                                                                                             │
│   84                                                                                             │
│   85 def update() -> None:                                                                       │
│ ❱ 86 │   arch_name, ptrsize, endian = _get_arch(typeinfo.ptrsize)                                │
│   87 │   arch.update(arch_name, ptrsize, endian)                                                 │
│   88 │   pwnlib.context.context.arch = pwnlib_archs_mapping[arch_name]                           │
│   89 │   pwnlib.context.context.bits = ptrsize * 8                                               │
│                                                                                                  │
│ /nix/store/xdgadrl8zmgy4fdxvhdnvnrz2dh5j22f-pwndbg/share/pwndbg/pwndbg/gdblib/arch.py:62 in      │
│ _get_arch                                                                                        │
│                                                                                                  │
│   59 │   │   endian = "big"                                                                      │
│   60 │                                                                                           │
│   61 │   if pwndbg.gdblib.proc.alive:                                                            │
│ ❱ 62 │   │   arch = gdb.newest_frame().architecture().name()                                     │
│   63 │   else:                                                                                   │
│   64 │   │   arch = gdb.execute("show architecture", to_string=True).strip()                     │
│   65 │   │   not_exactly_arch = True                                                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
error: Selected thread is running.
Traceback (most recent call last):
  File "/nix/store/xdgadrl8zmgy4fdxvhdnvnrz2dh5j22f-pwndbg/share/pwndbg/pwndbg/gdblib/events.py", line 129, in caller
    raise e
  File "/nix/store/xdgadrl8zmgy4fdxvhdnvnrz2dh5j22f-pwndbg/share/pwndbg/pwndbg/gdblib/events.py", line 124, in caller
    func()
  File "/nix/store/xdgadrl8zmgy4fdxvhdnvnrz2dh5j22f-pwndbg/share/pwndbg/pwndbg/gdblib/hooks.py", line 26, in update_arch
    arch_mod.update()
  File "/nix/store/xdgadrl8zmgy4fdxvhdnvnrz2dh5j22f-pwndbg/share/pwndbg/pwndbg/gdblib/arch.py", line 86, in update
    arch_name, ptrsize, endian = _get_arch(typeinfo.ptrsize)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/xdgadrl8zmgy4fdxvhdnvnrz2dh5j22f-pwndbg/share/pwndbg/pwndbg/gdblib/arch.py", line 62, in _get_arch
    arch = gdb.newest_frame().architecture().name()
           ^^^^^^^^^^^^^^^^^^
gdb.error: Selected thread is running.
```

I don't have a small repro yet, but you can reliably trigger it using the following instructions. If I run gdbserver locally this doesn't trigger. I have tested debugging other binaries over docker, not just redis-server, and it will still trigger. 

Build a docker image:

```docker
FROM redis:7.0.11-alpine
EXPOSE 6379
EXPOSE 8888

RUN apk update
RUN apk add gdb
RUN apk add musl-dbg
RUN gdbserver --multi :8888 &
CMD [ "sh", "-c", "gdbserver --multi :8888 redis-server --save 60 1 --loglevel debug"]
```

Then run pwndbg and run the following commands:

```
set exception-verbose on
target extended-remote localhost:8888
file target:/usr/local/bin/redis-server
br main
run
```

Also: 

```bash
❯ gdb -v
GNU gdb (GDB) 13.2
```

Would be nicer to repro without docker obviously, as it would be easier to create a test. @SamiKalliomaki how were you triggering the bug you tried to fix in your PR out of curiosity?

As for fix in the PR, if I add:

```python
    if pwndbg.gdblib.proc.alive and not gdb.selected_thread().is_running():
```

This DOES avoid that exception, so that is likely something that can be fixed independently.

However, then I get a new error when calling `gdb.execute()`.

```
Reading /usr/lib/debug/.build-id/a4/16a43cf0726627fc19b4a0765eb47a5e261551.debug from remote target...
------- tip of the day (disable with set show-tips off) -------
If you have debugging symbols the info args command shows current frame's function arguments (use up and down to switch between frames)
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /nix/store/a7cqla1p7avs0qwl91nx9kpx69jscwj2-pwndbg/share/pwndbg/pwndbg/gdblib/events.py:124 in   │
│ caller                                                                                           │
│                                                                                                  │
│   121 │   │   try:                                                                               │
│   122 │   │   │   # Don't pass the event along to the decorated function.                        │
│   123 │   │   │   # This is because there are functions with multiple event decorators           │
│ ❱ 124 │   │   │   func()                                                                         │
│   125 │   │   except Exception as e:                                                             │
│   126 │   │   │   import pwndbg.exception                                                        │
│   127                                                                                            │
│                                                                                                  │
│ /nix/store/a7cqla1p7avs0qwl91nx9kpx69jscwj2-pwndbg/share/pwndbg/pwndbg/lib/cache.py:145 in       │
│ decorator                                                                                        │
│                                                                                                  │
│   142 │   │   │   │   if cached_value is not _NOT_FOUND_IN_CACHE:                                │
│   143 │   │   │   │   │   return cached_value                                                    │
│   144 │   │   │   │                                                                              │
│ ❱ 145 │   │   │   │   value = func(*a, **kw)                                                     │
│   146 │   │   │   │                                                                              │
│   147 │   │   │   │   # Sanity check: its not perfect and won't cover all cases like ([],)       │
│   148 │   │   │   │   # but it should be good enough                                             │
│                                                                                                  │
│ /nix/store/a7cqla1p7avs0qwl91nx9kpx69jscwj2-pwndbg/share/pwndbg/pwndbg/gdblib/qemu.py:74 in root │
│                                                                                                  │
│    71 @start                                                                                     │
│    72 @pwndbg.lib.cache.cache_until("stop")                                                      │
│    73 def root() -> str | None:                                                                  │
│ ❱  74 │   if not is_qemu_usermode():                                                             │
│    75 │   │   return None                                                                        │
│    76 │                                                                                          │
│    77 │   binfmt_root = f"/etc/qemu-binfmt/{pwndbg.gdblib.arch.qemu}/"                           │
│                                                                                                  │
│ /nix/store/a7cqla1p7avs0qwl91nx9kpx69jscwj2-pwndbg/share/pwndbg/pwndbg/lib/cache.py:145 in       │
│ decorator                                                                                        │
│                                                                                                  │
│   142 │   │   │   │   if cached_value is not _NOT_FOUND_IN_CACHE:                                │
│   143 │   │   │   │   │   return cached_value                                                    │
│   144 │   │   │   │                                                                              │
│ ❱ 145 │   │   │   │   value = func(*a, **kw)                                                     │
│   146 │   │   │   │                                                                              │
│   147 │   │   │   │   # Sanity check: its not perfect and won't cover all cases like ([],)       │
│   148 │   │   │   │   # but it should be good enough                                             │
│                                                                                                  │
│ /nix/store/a7cqla1p7avs0qwl91nx9kpx69jscwj2-pwndbg/share/pwndbg/pwndbg/gdblib/qemu.py:53 in      │
│ is_qemu_usermode                                                                                 │
│                                                                                                  │
│    50 │   """Returns ``True`` if the target remote is being run under                            │
│    51 │   QEMU usermode emulation."""                                                            │
│    52 │                                                                                          │
│ ❱  53 │   return is_qemu() and is_usermode()                                                     │
│    54                                                                                            │
│    55                                                                                            │
│    56 @pwndbg.lib.cache.cache_until("stop")                                                      │
│                                                                                                  │
│ /nix/store/a7cqla1p7avs0qwl91nx9kpx69jscwj2-pwndbg/share/pwndbg/pwndbg/lib/cache.py:145 in       │
│ decorator                                                                                        │
│                                                                                                  │
│   142 │   │   │   │   if cached_value is not _NOT_FOUND_IN_CACHE:                                │
│   143 │   │   │   │   │   return cached_value                                                    │
│   144 │   │   │   │                                                                              │
│ ❱ 145 │   │   │   │   value = func(*a, **kw)                                                     │
│   146 │   │   │   │                                                                              │
│   147 │   │   │   │   # Sanity check: its not perfect and won't cover all cases like ([],)       │
│   148 │   │   │   │   # but it should be good enough                                             │
│                                                                                                  │
│ /nix/store/a7cqla1p7avs0qwl91nx9kpx69jscwj2-pwndbg/share/pwndbg/pwndbg/gdblib/qemu.py:28 in      │
│ is_qemu                                                                                          │
│                                                                                                  │
│    25 │   # pwndbg> maintenance packet Qqemu.sstepbits                                           │
│    26 │   # sending: "Qqemu.sstepbits"                                                           │
│    27 │   # received: "ENABLE=1,NOIRQ=2,NOTIMER=4"                                               │
│ ❱  28 │   response = gdb.execute("maintenance packet Qqemu.sstepbits", to_string=True, from_tt   │
│    29 │                                                                                          │
│    30 │   return "ENABLE=" in response                                                           │
│    31                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
error: Cannot execute this command while the target is running.
```

In this case I traced it down to `gdblib/file.py:get_file()`, as it will call:

```python
    local_path = path
    qemu_root = pwndbg.gdblib.qemu.root()

    if qemu_root:
        return os.path.join(qemu_root, path)
```

This `pwndbg.gdblib.qemu.root()` ultimately hits ends up failing because of `is_qemu()` calling the `gdb.execute` shown in the exception trace. 

This function is called because there is a stop event handler that triggers, and the cache is invalidated for most qemu functions. I did confirm that the same functions are called earlier and succeed.

This of course isn't something where we can just return `False` if the target is running, since we need to know if it's qemu or not... One solution would be to if those could be cached longer, as I don't suspect those will actually be expected to change on a stop?

I played around with this a bit. If I cache until a start, it just throws the exception on a separate code path but due to the same issue. If I cache forever, then it works (not surprising). But that's not ideal, since hypothetically in a single gdb session you might attach to one remote server, detach and then attach to some qemu instance.

I wonder if there's another way to invalidate the cache on a different less aggressive [event](https://sourceware.org/gdb/current/onlinedocs/gdb.html/Events-In-Python.html)?
Maybe something like `connection_removed`, `executable_changed` or `new_inferior`? The former sounds kind of promising, although you can have multiple connections to different targets at once apparently...

**Comment by patryk4815** [comment]
@fidgetingbits Please check if https://github.com/pwndbg/pwndbg/pull/2577 fix your issue
