### ISSUE TITLE
Celan Install, error at startup on import pwndbg

### ISSUE THREAD

**Issue by George-TL** [pwndbg/pwndbg#2209]
### Description

```
GNU gdb (Debian 13.2-1+b1) 13.2
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
Traceback (most recent call last):
  File "/home/kali/pwndbg/gdbinit.py", line 61, in <module>
    import pwndbg  # noqa: F401
    ^^^^^^^^^^^^^
  File "/home/kali/pwndbg/pwndbg/__init__.py", line 8, in <module>
    import pwndbg.commands
  File "/home/kali/pwndbg/pwndbg/commands/__init__.py", line 26, in <module>
    from pwndbg.heap.ptmalloc import DebugSymsHeap
  File "/home/kali/pwndbg/pwndbg/heap/ptmalloc.py", line 170, in <module>
    class ChunkField(Enum):
  File "/usr/lib/python3.11/enum.py", line 581, in __new__
    raise TypeError(
TypeError: ReprEnum subclasses must be mixed with a data type (i.e. int, str, float, etc.)
(gdb) 
```

### Steps to reproduce

Type gdb

### My setup

Kali Linux 2024.2 from kali-linux-2024.2-virtualbox-amd64

git clone https://github.com/pwndbg/pwndbg
cd ~/pwndbg
./setup.sh
cd ~

**Comment by CptGibbon** [comment]
This appears related to #2152 

```
class ChunkField(Enum):
...
TypeError: ReprEnum subclasses must be mixed with a data type (i.e. int, str, float, etc.)
```

https://github.com/pwndbg/pwndbg/blob/1faed37165338ae322bcbf07c61e0f7e0f4cd42d/pwndbg/heap/ptmalloc.py#L170-L172

Should I have used IntEnum here?
