### ISSUE TITLE
startup exceptions in init_ida_rpc_client

### ISSUE THREAD

**Issue by anthraxx** [pwndbg/pwndbg#228]
Did not yet investigate but i'm throwing here what greeted me after new pull

```Traceback (most recent call last):
  File "~/pwndbg/pwndbg/ida.py", line 58, in init_ida_rpc_client
    _ida.here()
  File "/usr/lib/python3.6/xmlrpc/client.py", line 1112, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.6/xmlrpc/client.py", line 1452, in __request
    verbose=self.__verbose
  File "/usr/lib/python3.6/xmlrpc/client.py", line 1154, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.6/xmlrpc/client.py", line 1166, in single_request
    http_conn = self.send_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.6/xmlrpc/client.py", line 1279, in send_request
    self.send_content(connection, request_body)
  File "/usr/lib/python3.6/xmlrpc/client.py", line 1309, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.6/socket.py", line 704, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.6/socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
OSError: Int or String expected
```

**Comment by disconnect3d** [comment]
This will be fixed by PR https://github.com/pwndbg/pwndbg/pull/223 - to be precisely, by this commit: https://github.com/pwndbg/pwndbg/pull/223/commits/4584f720b55b9afb95a7738de7fe7438b21c2891

**Comment by anthraxx** [comment]
hm I tried to apply that patch and it didn't fix the issue hmmmmm

**Comment by disconnect3d** [comment]
@anthraxx I guess you got another issue after cherry-picking 4584f72 which will be fixed by: https://github.com/pwndbg/pwndbg/pull/224

I am sorry for the mess I have done yesterday.

**Comment by anthraxx** [comment]
I can confirm applying both patch sets fixes the issues, this can be closed once we get the PRs applied

**Comment by anthraxx** [comment]
works, re-tested
