### ISSUE TITLE
capstone archive is missing setup.py breaking setup.sh

### ISSUE THREAD

**Issue by r1git** [pwndbg/pwndbg#231]
Download `https://github.com/aquynh/capstone/archive/next.zip#subdirectory=bindings/python`
Unzip
There is no `setup.py`

Reported @ capstone: https://github.com/aquynh/capstone/issues/896

This is now breaking `setup.sh`:

```
+  ./setup.sh : main()  62 > sudo /usr/bin/python2.7 -m pip install -Ur requirements.txt
Downloading/unpacking https://github.com/aquynh/capstone/archive/next.zip (from -r requirements.txt (line 11))
  Downloading next.zip (3.5MB): 3.5MB downloaded
  Running setup.py (path:/tmp/pip-dkJa1S-build/setup.py) egg_info for package from https://github.com/aquynh/capstone/archive/next.zip
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
    IOError: [Errno 2] No such file or directory: '/tmp/pip-dkJa1S-build/setup.py'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

IOError: [Errno 2] No such file or directory: '/tmp/pip-dkJa1S-build/setup.py'
```

**Comment by zachriggle** [comment]
I think you misunderstand how `requirements.txt` works.

**Comment by r1git** [comment]
That's exactly how it's done in `setup.sh`. The result for me was the error you could have read in my first post: pip complains about `setup.py` not found.
I believe this comes from my configuration somewhere. Can't figure out where though.
