### ISSUE TITLE
CI/CD Path Validation Error

### ISSUE THREAD

**Issue by k4lizen** [pwndbg/pwndbg#2314]
Looking at the "Post Cache for docker images" section of https://github.com/pwndbg/pwndbg/actions/runs/10012491583/job/27678119432?pr=2289.
```
Warning: Unexpected input(s) 'path', valid inputs are ['key', 'restore-keys', 'concurrency', 'skip-save']
Post job cleanup.
/usr/bin/sh -c docker save '63b21fc254a1' '63b21fc254a1' 'pwndbg_debian11:latest' '63b21fc254a1' | tar xf - -C .
Start storing root cache, key: debian11-cache-images-9609453c0abe83d5155c1a884c2384c837215ab6a0bd4f271a6418d78193ce4b-root, dir: /home/runner/work/_actions/jpribyl/action-docker-layer-caching/v0.1.1/dist/ttsc-dist/.adlc/image
/usr/bin/tar --posix -z -cf cache.tgz --exclude cache.tgz -P -C /home/runner/work/pwndbg/pwndbg --files-from manifest.txt
Cache Size: ~1270 MB (1331658395 B)
Cache saved successfully
Stored root cache, key: debian11-cache-images-9609453c0abe83d5155c1a884c2384c837215ab6a0bd4f271a6418d78193ce4b-root, id: 225699
Start storing layer cache: {"layerId":"blobs/sha256","key":"layer-debian11-cache-images-blobs/sha256"}
Start storing layer cache: {"layerId":"blobs/sha256","key":"layer-debian11-cache-images-blobs/sha256"}
Start storing layer cache: {"layerId":"blobs/sha256","key":"layer-debian11-cache-images-blobs/sha256"}
Start storing layer cache: {"layerId":"blobs/sha256","key":"layer-debian11-cache-images-blobs/sha256"}
Error: Unexpected error: Error: Path Validation Error: Path(s) specified in the action for caching do(es) not exist, hence no cache is being saved.
Start storing layer cache: {"layerId":"blobs/sha256","key":"layer-debian11-cache-images-blobs/sha256"}
Error: Path Validation Error: Path(s) specified in the action for caching do(es) not exist, hence no cache is being saved.
    at Object.<anonymous> (/home/runner/work/_actions/jpribyl/action-docker-layer-caching/v0.1.1/dist/ttsc-dist/post.js/index.js:158:19)
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/_actions/jpribyl/action-docker-layer-caching/v0.1.1/dist/ttsc-dist/post.js/index.js:12:58)
Error: Error: Path Validation Error: Path(s) specified in the action for caching do(es) not exist, hence no cache is being saved.
Error: Unexpected error: Error: Path Validation Error: Path(s) specified in the action for caching do(es) not exist, hence no cache is being saved.
Start storing layer cache: {"layerId":"blobs/sha256","key":"layer-debian11-cache-images-blobs/sha256"}
Error: Unexpected error: Error: Path Validation Error: Path(s) specified in the action for caching do(es) not exist, hence no cache is being saved.
Start storing layer cache: {"layerId":"blobs/sha256","key":"layer-debian11-cache-images-blobs/sha256"}
Error: Unexpected error: Error: Path Validation Error: Path(s) specified in the action for caching do(es) not exist, hence no cache is being saved.
Start storing layer cache: {"layerId":"blobs/sha256","key":"layer-debian11-cache-images-blobs/sha256"}
Error: Unexpected error: Error: Path Validation Error: Path(s) specified in the action for caching do(es) not exist, hence no cache is being saved.
Start storing layer cache: {"layerId":"blobs/sha256","key":"layer-debian11-cache-images-blobs/sha256"}
Error: Unexpected error: Error: Path Validation Error: Path(s) specified in the action for caching do(es) not exist, hence no cache is being saved.
Start storing layer cache: {"layerId":"blobs/sha256","key":"layer-debian11-cache-images-blobs/sha256"}
Error: Unexpected error: Error: Path Validation Error: Path(s) specified in the action for caching do(es) not exist, hence no cache is being saved.
Start storing layer cache: {"layerId":"blobs/sha256","key":"layer-debian11-cache-images-blobs/sha256"}
Error: Unexpected error: Error: Path Validation Error: Path(s) specified in the action for caching do(es) not exist, hence no cache is being saved.
Start storing layer cache: {"layerId":"blobs/sha256","key":"layer-debian11-cache-images-blobs/sha256"}
Error: Unexpected error: Error: Path Validation Error: Path(s) specified in the action for caching do(es) not exist, hence no cache is being saved.
Start storing layer cache: {"layerId":"blobs/sha256","key":"layer-debian11-cache-images-blobs/sha256"}
Error: Unexpected error: Error: Path Validation Error: Path(s) specified in the action for caching do(es) not exist, hence no cache is being saved.
Start storing layer cache: {"layerId":"blobs/sha256","key":"layer-debian11-cache-images-blobs/sha256"}
Error: Unexpected error: Error: Path Validation Error: Path(s) specified in the action for caching do(es) not exist, hence no cache is being saved.
Error: Unexpected error: Error: Path Validation Error: Path(s) specified in the action for caching do(es) not exist, hence no cache is being saved.
Error: Unexpected error: Error: Path Validation Error: Path(s) specified in the action for caching do(es) not exist, hence no cache is being saved.
Error: Unexpected error: Error: Path Validation Error: Path(s) specified in the action for caching do(es) not exist, hence no cache is being saved.
```
All OSes seem to be affected (ubuntu20, ubuntu22, debian, arch) and the errors aren't specific to that PR (another example https://github.com/pwndbg/pwndbg/actions/runs/10039445775/job/27743394801). It seems at some point it was expected that this would non-critically error though, as can be seen by the comment in https://github.com/pwndbg/pwndbg/blob/dev/.github/workflows/docker.yml#L24
```yml
 - name: Cache for docker images
      uses: jpribyl/action-docker-layer-caching@v0.1.1
      # Ignore the failure of a step and avoid terminating the job.
      continue-on-error: true
      with:
        path: ~/.cache/images
        key: ${{ matrix.images }}-cache-images-{hash}
```
The errors seem to slow down the job.

**Comment by disconnect3d** [comment]
From https://github.com/actions/cache?tab=readme-ov-file#inputs :
> path - A list of files, directories, and wildcard patterns to cache and restore. See [@actions/glob](https://github.com/actions/toolkit/tree/main/packages/glob) for supported patterns.

The error we get is that the path doesn't exist. Assuming the name for this GH action: "Cache for docker images" it clearly doesn't serve its role because this path would not contain docker images data, unless there is something I don't know.

**Comment by disconnect3d** [comment]
This was added in https://github.com/pwndbg/pwndbg/commit/dd6454065d05daffa7bc36e896dd7baec09c3e1d - maybe this path never worked as expected?
