### ISSUE TITLE
Python2 Broken

### ISSUE THREAD

**Issue by zachriggle** [pwndbg/pwndbg#234]
```
pwndbg> start
Temporary breakpoint 1 at 0x41eab0
Struct() argument 1 must be string, not unicode
'context': Print out the current register, instruction, and stack context.

    Accepts subcommands 'reg', 'disasm', 'code', 'stack', 'backtrace', and 'args'.
```

**Comment by zachriggle** [comment]
N.B. That this occurs on Python 2.7.6

**Comment by disconnect3d** [comment]
Uh that is even more interesting.

```
$ gdb -v
GNU gdb (Debian 7.7.1+dfsg-5) 7.7.1

pwndbg> py import sys; print(sys.version)
2.7.9 (default, Jun 29 2016, 13:11:10) 
[GCC 4.9.2]
```

```
dc@alx:~/pwndbg$ gdb -q /bin/ls
Loaded 105 commands.  Type pwndbg [filter] for a list.
Reading symbols from /bin/ls...(no debugging symbols found)...done.
pwndbg> start
Temporary breakpoint 1 at 0x402168
Traceback (most recent call last):
  File "/home/dc/pwndbg/pwndbg/commands/__init__.py", line 56, in __call__
    return self.function(*args, **kwargs)
  File "/home/dc/pwndbg/pwndbg/commands/__init__.py", line 130, in _OnlyWhenRunning
    return function(*a, **kw)
  File "/home/dc/pwndbg/pwndbg/commands/context.py", line 64, in context
    result.extend(func())
  File "/home/dc/pwndbg/pwndbg/commands/context.py", line 77, in context_regs
    result.extend(get_regs())
  File "/home/dc/pwndbg/pwndbg/commands/context.py", line 100, in get_regs
    changed = pwndbg.regs.changed
  File "/home/dc/pwndbg/pwndbg/regs.py", line 374, in changed
    if self[reg] != value:
  File "/home/dc/pwndbg/pwndbg/memoize.py", line 47, in __call__
    value = self.func(*args, **kwargs)
  File "/home/dc/pwndbg/pwndbg/regs.py", line 303, in __getitem__
    return int(item) & pwndbg.arch.ptrmask
  File "/home/dc/pwndbg/pwndbg/inthook.py", line 51, in __new__
    return _int.__new__(cls, value, *a, **kw)
OverflowError: Python int too large to convert to C long
```

(Same happens for `entry`, probably those are aliases)

**Comment by disconnect3d** [comment]
About my error, I have added prints into `xint.__new__`:
```
        print(cls, value, *a, **kw)
        print(type(cls), type(value))
```
And got that:
```
<class 'pwndbg.inthook.xint'> 18446744073709544288
<class 'pwndbg.inthook.IsAnInt'> <type 'long'>
```

**Comment by zachriggle** [comment]
Where is the `long` coming from?


*Zach Riggle*

**Comment by disconnect3d** [comment]
You are asking hard questions... :P But that's good :smile:.

It was hard to get pdb session in that place right to see really WTH happens there.

PR with some pdb debugging enchancement incomming!

PS: I am going to answer this, I just wasn't happy with having buffering issues in pdb (at least I think that was buffering as I could get output but after like 5 hits of CTRL+D , also `export PYTHONUNBUFFERED=1` or `PYTHONUNBUFFERED=1 gdb` didn't help).

**Comment by disconnect3d** [comment]
This can be closed as the issue has been fixed in the meantime.

Just as an info: we have also provided a way to set verbose exceptions or debugging (`set exception-verbose on` and `set exception-debugger on`).

Example output on GDB with Py2:
```
pwndbg> set context-sections ''
Set which context sections are displayed by default (also controls order) to ''
pwndbg> version
Gdb: GNU gdb (Debian 7.7.1+dfsg-5) 7.7.1
Python: 2.7.9 (default, Jun 29 2016, 13:11:10)  [GCC 4.9.2]
Pwndbg: 1.0.0 build: 73a0e11
pwndbg> start
Temporary breakpoint 1 at 0x402168
Breakpoint _init
pwndbg> 
```
