### ISSUE TITLE
context throw an exception when controlling $pc which from illegal memory

### ISSUE THREAD

**Issue by 0xddaa** [pwndbg/pwndbg#249]
### Description

I forged the FILE structure and tried to control program flow.
However, `context` will throw an exception if $pc is from illegal memory.
```
pwndbg> x/3i $pc
=> 0x7ffff7708193 <_IO_flush_all_lockp+371>:    call   QWORD PTR [rax+0x18]
   0x7ffff7708196 <_IO_flush_all_lockp+374>:    cmp    eax,0xffffffff
   0x7ffff7708199 <_IO_flush_all_lockp+377>:    mov    eax,0xffffffff
```
The traceback is as below:

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7708193 in _IO_flush_all_lockp (do_lock=do_lock@entry=0) at genops.c:786
786     in genops.c
Traceback (most recent call last):
  File "/home/dada/tools/pwndbg/pwndbg/commands/__init__.py", line 56, in __call__
    return self.function(*args, **kwargs)
  File "/home/dada/tools/pwndbg/pwndbg/commands/__init__.py", line 130, in _OnlyWhenRunning
    return function(*a, **kw)
  File "/home/dada/tools/pwndbg/pwndbg/commands/context.py", line 64, in context
    result.extend(func())
  File "/home/dada/tools/pwndbg/pwndbg/commands/context.py", line 77, in context_regs
    result.extend(get_regs())
  File "/home/dada/tools/pwndbg/pwndbg/commands/context.py", line 120, in get_regs
    desc = pwndbg.chain.format(value)
  File "/home/dada/tools/pwndbg/pwndbg/chain.py", line 97, in format
    enhanced = pwndbg.enhance.enhance(chain[-2] + offset, code=code)
  File "/home/dada/tools/pwndbg/pwndbg/enhance.py", line 100, in enhance
    instr = pwndbg.disasm.one(value)
  File "/home/dada/tools/pwndbg/pwndbg/disasm/__init__.py", line 108, in one
    for insn in get(address, 1):
  File "/home/dada/tools/pwndbg/pwndbg/disasm/__init__.py", line 128, in get
    i = get_one_instruction(address)
  File "/home/dada/tools/pwndbg/pwndbg/memoize.py", line 47, in __call__
    value = self.func(*args, **kwargs)
  File "/home/dada/tools/pwndbg/pwndbg/disasm/__init__.py", line 100, in get_one_instruction
    pwndbg.disasm.arch.DisassemblyAssistant.enhance(ins)
  File "/home/dada/tools/pwndbg/pwndbg/disasm/arch.py", line 55, in enhance
    enhancer.enhance_next(instruction)
  File "/home/dada/tools/pwndbg/pwndbg/disasm/arch.py", line 111, in enhance_next
    instruction.target = self.next(instruction, call=True)
  File "/home/dada/tools/pwndbg/pwndbg/disasm/x86.py", line 112, in next
    return super(DisassemblyAssistant, self).next(instruction, call)
  File "/home/dada/tools/pwndbg/pwndbg/disasm/arch.py", line 147, in next
    addr = int(pwndbg.memory.poi(pwndbg.typeinfo.ppvoid, addr))
  File "/home/dada/tools/pwndbg/pwndbg/inthook.py", line 40, in __new__
    value = value.cast(pwndbg.typeinfo.ulong)
gdb.MemoryError: Cannot access memory at address 0x124c
```

### Steps to reproduce
```
section .text
global _start
_start:
    mov     rax, 0x1234
    call    [rax + 0x18]
```
`nasm -f elf64 test.asm -o asm.o && ld asm.o -m elf_x86_64 -o test`

### My setup
```
pwndbg> version
Gdb: GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.04) 7.11.1
Python: 3.5.2 (default, Nov 17 2016, 17:05:23)  [GCC 5.4.0 20160609]
Pwndbg: 1.0.0 build: 6a1fdb28
```

**Comment by zachriggle** [comment]
This is no longer an issue.  Using pwntools to demonstrate:

```
$ pwn asm "mov eax, 0x1234; jmp 0xdeadbeef" --debug
```

```
pwndbg> c
Continuing.

Program received signal SIGSEGV, Segmentation fault.
0x00001234 in ?? ()
LEGEND: STACK | HEAP | CODE | DATA | RWX | RODATA
[───────────────────────────REGISTERS────────────────────────────]
*EAX  0x1234
 EBX  0x0
 ECX  0x0
 EDX  0x0
 EDI  0x0
 ESI  0x0
 EBP  0x0
 ESP  0xffb027c0 ◂— 0x1
*EIP  0x1234
[─────────────────────────────DISASM─────────────────────────────]
Invalid address 0x1234










[─────────────────────────────STACK──────────────────────────────]
00:0000│ esp  0xffb027c0 ◂— 0x1
01:0004│      0xffb027c4 —▸ 0xffb046dd ◂— 0x706d742f ('/tmp')
02:0008│      0xffb027c8 ◂— 0x0
03:000c│      0xffb027cc —▸ 0xffb04702 ◂— 0x3d202020 ('   =')
04:0010│      0xffb027d0 —▸ 0xffb04732 ◂— 0x5353454c ('LESS')
05:0014│      0xffb027d4 —▸ 0xffb0474b ◂— 0x5f303258 ('X20_')
06:0018│      0xffb027d8 —▸ 0xffb04774 ◂— 0x5f4b4341 ('ACK_')
07:001c│      0xffb027dc —▸ 0xffb0478d ◂— 0x4e455950 ('PYEN')
[───────────────────────────BACKTRACE────────────────────────────]
 ► f 0     1234
Program received signal SIGSEGV (fault address 0x1234)
pwndbg>
```
