### ISSUE TITLE
`pwnlib.constants.linux.riscv64` is unavailable

### ISSUE THREAD

**Issue by msanft** [pwndbg/pwndbg#2500]
### Description

When disassembling a `syscall`, [pwndbg tries to reference the `linux.riscv64` module from pwntools/pwnlib](https://github.com/pwndbg/pwndbg/pull/2180), which is [not yet available on any of their release branches](https://github.com/Gallopsled/pwntools/tree/4.13.1/pwnlib/constants/linux). This causes the following error:

```
Traceback (most recent call last):
  File "/nix/store/9dbskfl97sb737ny6qnq6lvp6jd5804x-python3.12-pwndbg-2024.08.29/lib/python3.12/site-packages/pwndbg/commands/__init__.py", line 187, in __call__
    return self.function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/9dbskfl97sb737ny6qnq6lvp6jd5804x-python3.12-pwndbg-2024.08.29/lib/python3.12/site-packages/pwndbg/commands/__init__.py", line 377, in _OnlyWhenRunning
    return function(*a, **kw)
           ^^^^^^^^^^^^^^^^^^
  File "/nix/store/9dbskfl97sb737ny6qnq6lvp6jd5804x-python3.12-pwndbg-2024.08.29/lib/python3.12/site-packages/pwndbg/commands/context.py", line 405, in context
    func(
  File "/nix/store/9dbskfl97sb737ny6qnq6lvp6jd5804x-python3.12-pwndbg-2024.08.29/lib/python3.12/site-packages/pwndbg/commands/context.py", line 632, in context_disasm
    result = pwndbg.gdblib.nearpc.nearpc(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/9dbskfl97sb737ny6qnq6lvp6jd5804x-python3.12-pwndbg-2024.08.29/lib/python3.12/site-packages/pwndbg/gdblib/nearpc.py", line 138, in nearpc
    instructions, index_of_pc = pwndbg.gdblib.disasm.near(
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/9dbskfl97sb737ny6qnq6lvp6jd5804x-python3.12-pwndbg-2024.08.29/lib/python3.12/site-packages/pwndbg/gdblib/disasm/__init__.py", line 500, in near
    insn = one(target, emu, put_cache=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/9dbskfl97sb737ny6qnq6lvp6jd5804x-python3.12-pwndbg-2024.08.29/lib/python3.12/site-packages/pwndbg/gdblib/disasm/__init__.py", line 252, in one
    for insn in get(address, 1, emu, enhance=enhance, from_cache=from_cache, put_cache=put_cache):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/9dbskfl97sb737ny6qnq6lvp6jd5804x-python3.12-pwndbg-2024.08.29/lib/python3.12/site-packages/pwndbg/gdblib/disasm/__init__.py", line 287, in get
    i = get_one_instruction(
        ^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/9dbskfl97sb737ny6qnq6lvp6jd5804x-python3.12-pwndbg-2024.08.29/lib/python3.12/site-packages/pwndbg/gdblib/disasm/__init__.py", line 225, in get_one_instruction
    pwndbg.gdblib.disasm.arch.DisassemblyAssistant.enhance(pwn_ins, emu)
  File "/nix/store/9dbskfl97sb737ny6qnq6lvp6jd5804x-python3.12-pwndbg-2024.08.29/lib/python3.12/site-packages/pwndbg/gdblib/disasm/arch.py", line 206, in enhance
    enhancer._enhance_syscall(instruction, emu)
  File "/nix/store/9dbskfl97sb737ny6qnq6lvp6jd5804x-python3.12-pwndbg-2024.08.29/lib/python3.12/site-packages/pwndbg/gdblib/disasm/arch.py", line 579, in _enhance_syscall
    DisassemblyAssistant._syscall_name(instruction.syscall, syscall_arch)
  File "/nix/store/9dbskfl97sb737ny6qnq6lvp6jd5804x-python3.12-pwndbg-2024.08.29/lib/python3.12/site-packages/pwndbg/gdblib/disasm/arch.py", line 547, in _syscall_name
    "rv32": linux.riscv64,
            ^^^^^^^^^^^^^
  File "/nix/store/srm2iarbh355nfbdyhq7h98g1sj4x8b1-python3.12-pwntools-4.13.1/lib/python3.12/site-packages/pwnlib/constants/__init__.py", line 117, in __getattr__
    raise AttributeError("'module' object has no attribute '%s'" % key)
AttributeError: 'module' object has no attribute 'riscv64'
```

### Steps to reproduce

Disassemble a `syscall` instruction while stepping.

### My setup

```
Gdb:      15.1
Python:   3.12.6 (main, Sep  6 2024, 19:03:47) [GCC 13.3.0]
Pwndbg:   2024.08.29
Capstone: 5.0.1280
Unicorn:  2.1.0
```

**Comment by patryk4815** [comment]
@msanft from where did you get this pwndbg?
If from Nixpkgs, they use "random" python dependencies - this is every time issue in many distros... arch, nixpkgs.. etc

Our flake should work fine: `nix shell github:pwndbg/pwndbg`

Pwndbg use beta version of pwntools and it contains riscv https://github.com/pwndbg/pwndbg/blob/dev/pyproject.toml#L165

**Comment by msanft** [comment]
> @msanft from where did you get this pwndbg?
> 
> If from Nixpkgs, they use "random" python dependencies - this is every time issue in many distros... arch, nixpkgs.. etc
> 
> 
> 
> Our flake should work fine: `nix shell github:pwndbg/pwndbg`
> 
> 
> 
> Pwndbg use beta version of pwntools and it contains riscv https://github.com/pwndbg/pwndbg/blob/dev/pyproject.toml#L165
> 
> 
> 
> 

Thx! This is a bug specific to nixpkgs then
