### ISSUE TITLE
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

### ISSUE THREAD

**Issue by brookate** [pwndbg/pwndbg#2570]
when I start connect remote port

```
pwndbg> target remote :1234
Remote debugging using :1234
warning: while parsing target description (at line 1): Could not load XML document "i386-64bit.xml"
warning: Could not load XML target description; ignoring
0x000000000000fff0 in exception_stacks ()
Exception occurred: Error: int() argument must be a string, a bytes-like object or a real number, not 'NoneType' (<class 'TypeError'>)
For more info invoke `set exception-verbose on` and rerun the command
or debug it by yourself with `set exception-debugger on`
Python Exception <class 'TypeError'>: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
Exception occurred: Error: int() argument must be a string, a bytes-like object or a real number, not 'NoneType' (<class 'TypeError'>)
For more info invoke `set exception-verbose on` and rerun the command
or debug it by yourself with `set exception-debugger on`
Python Exception <class 'TypeError'>: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
pwndbg>

Traceback (most recent call last):
  File "/home/uuu/repo/pwndbg/pwndbg/gdblib/events.py", line 156, in caller
    func()
  File "/home/uuu/repo/pwndbg/pwndbg/lib/cache.py", line 162, in decorator
    value = func(*a, **kw)
            ^^^^^^^^^^^^^^
  File "/home/uuu/repo/pwndbg/pwndbg/gdblib/stack.py", line 72, in is_executable
    ehdr = pwndbg.gdblib.elf.exe()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uuu/repo/pwndbg/pwndbg/gdblib/proc.py", line 186, in wrapper
    return func(*a, **kw)
           ^^^^^^^^^^^^^^
  File "/home/uuu/repo/pwndbg/pwndbg/lib/cache.py", line 162, in decorator
    value = func(*a, **kw)
            ^^^^^^^^^^^^^^
  File "/home/uuu/repo/pwndbg/pwndbg/gdblib/elf.py", line 251, in exe
    return load(e)
           ^^^^^^^
  File "/home/uuu/repo/pwndbg/pwndbg/gdblib/elf.py", line 290, in load
    return get_ehdr(pointer)[1]
           ^^^^^^^^^^^^^^^^^
  File "/home/uuu/repo/pwndbg/pwndbg/gdblib/elf.py", line 311, in get_ehdr
    vmmap = pwndbg.gdblib.vmmap.find(pointer, should_explore=False)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uuu/repo/pwndbg/pwndbg/lib/cache.py", line 162, in decorator
    value = func(*a, **kw)
            ^^^^^^^^^^^^^^
  File "/home/uuu/repo/pwndbg/pwndbg/gdblib/vmmap.py", line 206, in find
    for page in get():
                ^^^^^
  File "/home/uuu/repo/pwndbg/pwndbg/lib/cache.py", line 162, in decorator
    value = func(*a, **kw)
            ^^^^^^^^^^^^^^
  File "/home/uuu/repo/pwndbg/pwndbg/gdblib/vmmap.py", line 158, in get
    pages.extend(kernel_vmmap_via_page_tables())
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/home/uuu/repo/pwndbg/pwndbg/lib/cache.py", line 162, in decorator
    value = func(*a, **kw)
            ^^^^^^^^^^^^^^
  File "/home/uuu/repo/pwndbg/pwndbg/gdblib/vmmap.py", line 607, in kernel_vmmap_via_page_tables
    if not pwndbg.gdblib.kernel.paging_enabled():
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uuu/repo/pwndbg/pwndbg/gdblib/kernel/__init__.py", line 630, in paging_enabled
    return x86_64Ops.paging_enabled()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uuu/repo/pwndbg/pwndbg/gdblib/kernel/__init__.py", line 316, in paging_enabled
    return int(pwndbg.gdblib.regs.cr0) & BIT(31) != 0
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

Traceback (most recent call last):
  File "/home/uuu/repo/pwndbg/pwndbg/gdblib/prompt.py", line 80, in prompt_hook
    pwndbg.gdblib.events.after_reload(start=cur is None)
  File "/home/uuu/repo/pwndbg/pwndbg/gdblib/events.py", line 232, in after_reload
    invoke_event(gdb.events.stop)
  File "/home/uuu/repo/pwndbg/pwndbg/gdblib/events.py", line 227, in invoke_event
    f(*args, **kwargs)
  File "/home/uuu/repo/pwndbg/pwndbg/gdblib/events.py", line 161, in caller
    raise e
  File "/home/uuu/repo/pwndbg/pwndbg/gdblib/events.py", line 156, in caller
    func()
  File "/home/uuu/repo/pwndbg/pwndbg/lib/cache.py", line 162, in decorator
    value = func(*a, **kw)
            ^^^^^^^^^^^^^^
  File "/home/uuu/repo/pwndbg/pwndbg/gdblib/stack.py", line 72, in is_executable
    ehdr = pwndbg.gdblib.elf.exe()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uuu/repo/pwndbg/pwndbg/gdblib/proc.py", line 186, in wrapper
    return func(*a, **kw)
           ^^^^^^^^^^^^^^
  File "/home/uuu/repo/pwndbg/pwndbg/lib/cache.py", line 162, in decorator
    value = func(*a, **kw)
            ^^^^^^^^^^^^^^
  File "/home/uuu/repo/pwndbg/pwndbg/gdblib/elf.py", line 251, in exe
    return load(e)
           ^^^^^^^
  File "/home/uuu/repo/pwndbg/pwndbg/gdblib/elf.py", line 290, in load
    return get_ehdr(pointer)[1]
           ^^^^^^^^^^^^^^^^^
  File "/home/uuu/repo/pwndbg/pwndbg/gdblib/elf.py", line 311, in get_ehdr
    vmmap = pwndbg.gdblib.vmmap.find(pointer, should_explore=False)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uuu/repo/pwndbg/pwndbg/lib/cache.py", line 162, in decorator
    value = func(*a, **kw)
            ^^^^^^^^^^^^^^
  File "/home/uuu/repo/pwndbg/pwndbg/gdblib/vmmap.py", line 206, in find
    for page in get():
                ^^^^^
  File "/home/uuu/repo/pwndbg/pwndbg/lib/cache.py", line 162, in decorator
    value = func(*a, **kw)
            ^^^^^^^^^^^^^^
  File "/home/uuu/repo/pwndbg/pwndbg/gdblib/vmmap.py", line 158, in get
    pages.extend(kernel_vmmap_via_page_tables())
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uuu/repo/pwndbg/pwndbg/lib/cache.py", line 162, in decorator
    value = func(*a, **kw)
            ^^^^^^^^^^^^^^
  File "/home/uuu/repo/pwndbg/pwndbg/gdblib/vmmap.py", line 607, in kernel_vmmap_via_page_tables
    if not pwndbg.gdblib.kernel.paging_enabled():
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uuu/repo/pwndbg/pwndbg/gdblib/kernel/__init__.py", line 630, in paging_enabled
    return x86_64Ops.paging_enabled()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uuu/repo/pwndbg/pwndbg/gdblib/kernel/__init__.py", line 316, in paging_enabled
    return int(pwndbg.gdblib.regs.cr0) & BIT(31) != 0
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
pwndbg> 
```

**Comment by disconnect3d** [comment]
@brookate hi, any chance u can provide a minimal example for reproducing this?

**Comment by disconnect3d** [comment]
Also: what GDB and QEMU versions do you use?

The `Could not load XML document "i386-64bit.xml"` seems like an issue not on our end, but who knows.

**Comment by brookate** [comment]
gdb version 

```
~ gdb --version
GNU gdb (Gentoo 15.2 vanilla) 15.2
Copyright (C) 2024 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

and qemu is android emulator, I used following 
```
emulator -show-kernel -no-snapshot -wipe-data -avd  xxx -qemu -s -S 
```

**Comment by brookate** [comment]
Oh, qemu version too old, rebuild emulator can resolve this.
