### ISSUE TITLE
Bare metal debugging

### ISSUE THREAD

**Issue by RageYL** [pwndbg/pwndbg#264]
Hi,

When debugging on a bare metal mcu (arm, cortex-m4 processor) pwndbg 'hang' immediately after the connection with the remote gdbserver has been established

1) AUXV are not present: pwndbg tries to find those and will end up searching the whole memory (walk_stack2)
2) $xpsr is used instead of $cpsr. it uses a different bit to indicate thumb mode ($ps is not available on this arch)
xpsr: http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.ddi0413d/ch02s02s02.html
3) find_upper/lower_boundary is slow (each memory dereference is slow on remote): in my case max_pages is reached, it takes 30 seconds to display registers...

idea for 1) 2) 3):
the input binary contains lots of information that could be very useful:
- immediately available (do not look for them in the memory, eg: entry point)
- disable unneeded operations (no auxv with a cortex-m4, readelf -A)

idea 2)
it would be nice to display context without crashing even if a register is not found

**Comment by disconnect3d** [comment]
@RageYL Can you look if we can determine somehow whether we are debugging bare metal or not?

Maybe there is some kind of `info ...` command that gives us such information after connecting to remote target?

**Comment by RageYL** [comment]
I already (very briefly) looked and didn't find any command, that's why i suggested parsing the binary as i could get the information with readelf. 
But i'll take a more serious look and keep you updated ;) (should be done by the end of the week)

**Comment by disconnect3d** [comment]
@RageYL Can you check `show osabi` after connecting to remote target?
Someone mentioned this on #gdb IRC channel on freenode.

**Comment by RageYL** [comment]
@disconnect3d show osabi displays: The current OS ABI is "auto" (currently "none")

**Comment by disconnect3d** [comment]
So maybe this is how we can determine debugging bare metal:
```python
is_bare_metal = '(currently "none")' in gdb.execute('show osabi', to_string=True)
```

For me (without debugging bare metal) it is:
```
$ gdb
Loaded 106 commands. Type pwndbg [filter] for a list.
pwndbg> show osabi
The current OS ABI is "auto" (currently "GNU/Linux").
The default OS ABI is "GNU/Linux".
```

This is also returned when debugging a MIPS binary remotely (launched as `qemu-mips -g 1234`).

**Comment by RageYL** [comment]
I feared gdb could return "none" in some other cases, but from what i'm reading (http://agentzh.org/misc/code/gdb/osabi.c.html) if the osabi value, defined in the elf header, is invalid, "\<invalid>" is returned and not "none".
This choice seems safe as the osabi value seems bound to the gdb architecture defined at compile time: even if the binary contains an edited value for the osabi, gdb still use 'auto' (which is equal to gdb's architecture). So, as long as one use a gdb configured for the same architecture as the binary (which should always be the case), the osabi value should be valid.
In last resort, one can still manually set the osabi value.

**Comment by zachriggle** [comment]
Sounds good to me!

**Comment by zachriggle** [comment]
It might be useful to have a `@pwndbg.abi.Linux` decorator that does some magic

**Comment by disconnect3d** [comment]
So the first part has been merged - #369 - thanks @cebrusfs o/
I will assign you to this issue.

EDIT: Interesting, seems I can only assign ppl from pwndbg team and RageYL who created the issue (maybe also other ppl who would comment it; well... whatever).

**Comment by cebrusfs** [comment]
#369 support the basic functions for bare metal and #385 recover the page information from ELF and use them for de-reference.
The remaining problem is the thumb supporting on $xspr and $cspr, but I don't have time/plan to fix it in short time. I think it is better to let people who are interested to do that?

**Comment by ttimasdf** [comment]
I've got a hacky solution regarding the usage of $xpsr. I've just take a short look of pwndbg's code so I'm not sure if i'm adding the right piece at the right place.
Cortex-M series don't have a $cspr register but a similar $xspr instead. The [bit offset](http://infocenter.arm.com/help/topic/com.arm.doc.ddi0413d/ch02s02s02.html) indicating Thumb mode is also different than that with $cspr. This commit(ttimasdf/pwndbg@2b5ba4d4faad6c831230eeab972428e8a73de137) try to detects them and uses whichever available. I can't say the code is the best practice but it works :smile: Could be a reference.

**Comment by dawidcrivelli** [comment]
If I set manually `set osabi none`, and hardcode the architecture to `armcm` in the sourcecode (`return "armcm"` in `arch.py`), I still get an exception, since pwndbg is not able to access the `xpsr` register.

```
pwndbg> ni
FORCING armcm
0x00024d34 in ?? ()
'nearpc': Disassemble near a specified address.
Traceback (most recent call last):
  File "/home/dawid/tools/pwndbg/pwndbg/commands/__init__.py", line 130, in __call__
    return self.function(*args, **kwargs)
  File "/home/dawid/tools/pwndbg/pwndbg/commands/__init__.py", line 221, in _OnlyWhenRunning
    return function(*a, **kw)
  File "/home/dawid/tools/pwndbg/pwndbg/commands/nearpc.py", line 93, in nearpc
    instructions = pwndbg.disasm.near(pc, lines, emulate=emulate, show_prev_insns=not nearpc.repeat)
  File "/home/dawid/tools/pwndbg/pwndbg/disasm/__init__.py", line 170, in near
    current = one(address)
  File "/home/dawid/tools/pwndbg/pwndbg/disasm/__init__.py", line 116, in one
    for insn in get(address, 1):
  File "/home/dawid/tools/pwndbg/pwndbg/disasm/__init__.py", line 136, in get
    i = get_one_instruction(address)
  File "/home/dawid/tools/pwndbg/pwndbg/memoize.py", line 44, in __call__
    value = self.func(*args, **kwargs)
  File "/home/dawid/tools/pwndbg/pwndbg/disasm/__init__.py", line 104, in get_one_instruction
    md   = get_disassembler(address)
  File "/home/dawid/tools/pwndbg/pwndbg/disasm/__init__.py", line 79, in get_disassembler
    extra = (CS_MODE_MCLASS | CS_MODE_THUMB) if (pwndbg.regs.xpsr & (1<<24)) else CS_MODE_MCLASS
TypeError: unsupported operand type(s) for &: 'NoneType' and 'int'

> /home/dawid/tools/pwndbg/pwndbg/disasm/__init__.py(79)get_disassembler()
-> extra = (CS_MODE_MCLASS | CS_MODE_THUMB) if (pwndbg.regs.xpsr & (1<<24)) else CS_MODE_MCLASS

(Pdb) print (pwndbg.regs.xpsr)
None
```

To fix it, I have to delete the lines at [](pwndbg/regs.py:282): 
```
if attr.lower() == 'xpsr':
               attr = 'xPSR'
```
It looks like my version of gdb-multiarch (8.1.1) uses again lower-case names for the registers :roll_eyes: .

Is there a way to force the architecture to be `armcm` without changing the source code ?

**Comment by ikcalB** [comment]
is there any progresss (maybe in a non master branch) on this?

**Comment by disconnect3d** [comment]
@ikcalB If you are not tied to a specific architecture we lack proper support for, this patch may or may not help: https://github.com/pwndbg/pwndbg/files/6376801/kernel.patch.txt. Originally developed for hacking around a linux kernel on a ctf and described on https://github.com/pwndbg/pwndbg/issues/911#issuecomment-826778913 but it should also help for bare metal debugging.

Please, let me know if you try it and feel free to ping me if you want to help develop this feature.

**Comment by disconnect3d** [comment]
Here is more or less what needs to be done for bare metal debugging:

1) disable the gdblib.stack.update hook
2) disable the gdblib.stack.is_executable hook
3) disable the gdblib.symbol.add_main_to_symbols hook
4) the pwndbg.gdblib.proc.pid returns 42000 for OCD remote debugging which is wrong (note: "QEMU usermode emulation always returns 42000 for some reason." too :/)
5) ^ i am not sure but i think this may make vmmap return wrong logic?
5) vmmap_add command should cast the gdb.Value it receives to int()
6) vmmap_add should support naming of custom vmmaps
7) gdblib.vmmap.get should probably return early if custom maps are defined and just return them? not sure
8) dereference-limit needs to be set to 0 or 1 {so we don't hit memory if its not needed}
After doing some fast monkey patching like early return from 1,2,3, returning custom vmmaps from vmmap, the 'ctx regs' still accessed lots of remote memory, not sure why; maybe the vmmap_add didnt work properly

**Comment by niflostancu** [comment]
I am also interested in having PwnDbg working on microcontroller architectures (ARM Cortex-Ms, for now).

I have successfully hacked the code to fix some of the issues I persoanlly encountered:
https://github.com/niflostancu/pwndbg/tree/niflo_armcm_hacks

Basically, what I did was:
- add ability to override binary architecture via GDB_MCU_ARCH environment variable (I've had problems with a Cortex-M3 tagging the CPU arch with "v7", no "-M");
- ignore unrecognized register errors (for some targets, `pwndbg.gdblib.regs.xpsr` is None :| );
- new method for filling vmmaps from GDB's mem map (filled by the remote target); use the `GDB_MCU_TARGET` environment variable to enable.

As the name suggests, they are just some ugly "workarounds".
If you think that any of these changes deserve to be in the official tree, tell me and I will come with a PR.
Thanks!

**Comment by disconnect3d** [comment]
@patryk4815 what's the state of this? I think it works for the most part? At least I know u and @Grazfather do some bare metal debugging. Can we close this?

**Comment by Grazfather** [comment]
It works surprisingly well by default, at least on rp2040 (cortex m0) and esp32-c3 (risvc). That said, I don't use too many features other than the context view.

**Comment by disconnect3d** [comment]
I am going to close this for now since afaik it is working well. Thanks @Grazfather for info!
