### ISSUE TITLE
next* commands on various archs

### ISSUE THREAD

**Issue by disconnect3d** [pwndbg/pwndbg#325]
### Description

It seems the `nextsc` command fails on ARM. We should also verify other `next*` commands on ARMs and other archs then x86/x64.

Any idea what to do with them? Disabling them might be a solution(?)

Below you can see a failure example.
```
pwndbg> nextsc
Traceback (most recent call last):
  File "/home/dc/installed/pwndbg/pwndbg/commands/__init__.py", line 99, in __call__
    return self.function(*args, **kwargs)
  File "/home/dc/installed/pwndbg/pwndbg/commands/__init__.py", line 191, in _OnlyWhenRunning
    return function(*a, **kw)
  File "/home/dc/installed/pwndbg/pwndbg/commands/next.py", line 65, in next_syscall
    while pwndbg.proc.alive and not pwndbg.next.break_next_interrupt() and pwndbg.next.break_next_branch():
  File "/home/dc/installed/pwndbg/pwndbg/next.py", line 80, in break_next_interrupt
    ins = next_int(address)
  File "/home/dc/installed/pwndbg/pwndbg/next.py", line 38, in next_int
    ins = pwndbg.disasm.one(pwndbg.regs.pc)
  File "/home/dc/installed/pwndbg/pwndbg/disasm/__init__.py", line 108, in one
    for insn in get(address, 1):
  File "/home/dc/installed/pwndbg/pwndbg/disasm/__init__.py", line 128, in get
    i = get_one_instruction(address)
  File "/home/dc/installed/pwndbg/pwndbg/memoize.py", line 48, in __call__
    value = self.func(*args, **kwargs)
  File "/home/dc/installed/pwndbg/pwndbg/disasm/__init__.py", line 100, in get_one_instruction
    pwndbg.disasm.arch.DisassemblyAssistant.enhance(ins)
  File "/home/dc/installed/pwndbg/pwndbg/disasm/arch.py", line 57, in enhance
    print(enhancer.dump(instruction))
  File "/home/dc/installed/pwndbg/pwndbg/disasm/arch.py", line 254, in dump
    rv.append('       access   = %s' % (access.get(op.access, op.access)))
AttributeError: 'ArmOp' object has no attribute 'access'
  ```

**Comment by zachriggle** [comment]
Doesn't fail for me.  What version of Capstone are you using?  Works for me with the latest `next` branch, which is what we require (see `requirements.txt`).

**Comment by disconnect3d** [comment]
Hmm.. I am trying to reproduce as that happened to me like a week ago..
Currently I have got another problem:
```
$ arm-linux-gnueabihf-gcc main.c
$ file ./a.out
./a.out: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 3.2.0, BuildID[sha1]=a44697dc030c4ed90b460914c89b30db2e9a7152, with debug_info, not stripped
$ qemu-arm ./a.out 
./a.out: error while loading shared libraries: libc.so.6: wrong ELF class: ELFCLASS64
```

EDIT:
A proper `LD_PRELOAD` with path to arm libc helped.

**Comment by zachriggle** [comment]
Probably easier to just use a statically-linked library.  

I've got a long and useful StackExchange post on making QEMU work nicely: https://reverseengineering.stackexchange.com/questions/8829/cross-debugging-for-mips-elf-with-qemu-toolchain

It's targeted at MIPS, but also works for ARM.

**Comment by disconnect3d** [comment]
@zachriggle Thanks for the idea of using static linking.
 Also see this https://asciinema.org/a/StzXbi9nNbptGbWAPB0v478Qy
Seems we have to check for something like `.is_stopped` somewhere anyway.

The `nearpc` shown there is totally different then `objdump` result:
```
000104d4 <main>:
   104d4:       e92d4800        push    {fp, lr}
   104d8:       e28db004        add     fp, sp, #4
   104dc:       e24dd008        sub     sp, sp, #8
   104e0:       e50b0008        str     r0, [fp, #-8]
   104e4:       e50b100c        str     r1, [fp, #-12]
   104e8:       ebfffff1        bl      104b4 <foo>
   104ec:       e51b3008        ldr     r3, [fp, #-8]
   104f0:       e3530001        cmp     r3, #1
   104f4:       1a000001        bne     10500 <main+0x2c>
   104f8:       e59f0038        ldr     r0, [pc, #56]   ; 10538 <main+0x64>
   104fc:       eb001b15        bl      17158 <_IO_puts>
   10500:       e51b3008        ldr     r3, [fp, #-8]
   10504:       e3530002        cmp     r3, #2
   10508:       1a000001        bne     10514 <main+0x40>
   1050c:       e59f0028        ldr     r0, [pc, #40]   ; 1053c <main+0x68>
   10510:       eb001b10        bl      17158 <_IO_puts>
   10514:       e51b3008        ldr     r3, [fp, #-8]
   10518:       e3530002        cmp     r3, #2
   1051c:       1a000001        bne     10528 <main+0x54>
   10520:       e59f0018        ldr     r0, [pc, #24]   ; 10540 <main+0x6c>
   10524:       eb001b0b        bl      17158 <_IO_puts>
   10528:       e3a03000        mov     r3, #0
   1052c:       e1a00003        mov     r0, r3
   10530:       e24bd004        sub     sp, fp, #4
   10534:       e8bd8800        pop     {fp, pc}
   10538:       0006f60c        .word   0x0006f60c
   1053c:       0006f614        .word   0x0006f614
   10540:       0006f61c        .word   0x0006f61c
```

**Comment by disconnect3d** [comment]
About the infinite looping when program has stopped:
```
Program stopped.
0x000105a4 in __libc_start_main (main=0x1, argc=0, argv=0x0, init=0x10c40 <__assert_fail_base+120>, fini=0x10ce0 <__assert_fail_base+280>, rtld_fini=0x0, stack_end=0xf6ffe8c4) at libc-start.c:282
282	in libc-start.c
OUR PROGRAM IS ALIVE? True
```
`OUR PROGRAM IS ALIVE? True` is my debug print in  https://github.com/pwndbg/pwndbg/blob/dev/pwndbg/proc.py#L48. Trying to debug/see how to fix that.

EDIT:
The state when "Program stopped":
```
In : dir(gdb.selected_thread())
['__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'global_num', 'inferior', 'is_exited', 'is_running', 'is_stopped', 'is_valid', 'name', 'num', 'ptid', 'switch']
In : gdb.selected_thread().is_exited()
False
In : gdb.selected_thread().is_running()
False
In : gdb.selected_thread().is_valid()
True
In : gdb.selected_inferior()
<gdb.Inferior object at 0x7f39275c5b20>
In : dir(gdb.selected_inferior())
['__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'is_valid', 'num', 'pid', 'read_memory', 'search_memory', 'threads', 'was_attached', 'write_memory']
In : gdb.selected_inferior().is_valid()
True
In : gdb.selected_inferior().was_attached
False
```

**Comment by disconnect3d** [comment]
@zachriggle can you try doing `nextcall` in above example as shown on asciinema? Does it go into an infinite loop on your side?
Idk how we can detect this "Program stopped" thing...

**Comment by zachriggle** [comment]
re: the asciinema, `nearpc` has no way to determine what processor mode should be used.

If you want to force Thumb, you need to add a `+1` to the address

**Comment by zachriggle** [comment]
You need to upload whatever binary you're using if you want me to look at it :P

**Comment by disconnect3d** [comment]
@zachriggle You could always copy the code from asciinema (yeah you can copy the text there :D).

But anyway, here it is:
```c
#include <stdio.h>

void foo() {
    printf("Hello world %d\n", 10);
}

int main(int argc, char* argv[]) {
    foo();
    if (argc == 1)
        puts("ARGC 1");
    if (argc == 2)
        puts("ARGC 2");
    if (argc == 2)
        puts("ARGC 3");
}
```

[a.zip](https://github.com/pwndbg/pwndbg/files/1240309/a.zip)

**Comment by zachriggle** [comment]
Yeah, I deleted that comment since I realized it doesn't matter.

Pwndbg has no way to determine that `main` is Thumb mode.  The binary isn't running, so the current mode isn't Thumb, and the address given is even (Thumb addresses are odd).

Technically, I'd vote that the symbols are wrong :P

In any case, something else is up since your addresses for main don't match up (104d4 vs 0x10110) between Github (above) and on Asciinema.

**Comment by disconnect3d** [comment]
@zachriggle Lets focus on the `next*` commands.

Any idea how we can deal with the `program stopped`? :/

**Comment by disconnect3d** [comment]
I have retested this on `arm-linux-gnueabi` and ` arm-linux-gnueabihf` and the `program stopped` issue doesn't appear anymore. There are still some other issues with some commands but that being said I am going to close this. Lets solve bugs in seperate PRs or issues.

#### Tested on
```
pwndbg> version
Gdb:      8.1.0.20180409-git
Python:   3.6.5 (default, Apr  1 2018, 05:46:30)  [GCC 7.3.0]
Pwndbg:   1.0.0 build: 2bc872c
Capstone: 4.0.1024
Unicorn:  1.0.1
```

* compiled e.g. as `arm-linux-gnueabi-gcc-8 ./test2.c -ggdb`
* qemu launched e.g. as `qemu-arm -g 4444 -L /usr/arm-linux-gnueabi ./a.out`
* there is no infinite loop problem
* `nextcall` works fine - stops at `bl` instructions
* `nextsyscall`, `stepsyscall`, `nextret`, `stepret` seems to be more or less broken
