### ISSUE TITLE
ctypes: Header file parsing

### ISSUE THREAD

**Issue by zachriggle** [pwndbg/pwndbg#345]
Given a C header file which declares a structure type, we should be able to generate a `ctypes` structure definition for it.

This is the inverse of #344

**Comment by zachriggle** [comment]
It looks like `ctypeslib2` could support this, but the `clang` module only supports Python2.

```
Traceback (most recent call last):
  File "/Users/riggle/.pyenv/versions/3.6.1/bin/clang2py", line 3, in <module>
    from ctypeslib.clang2py import main
  File "/Users/riggle/.pyenv/versions/3.6.1/lib/python3.6/site-packages/ctypeslib/clang2py.py", line 10, in <module>
    from ctypeslib.codegen.codegenerator import generate_code
  File "/Users/riggle/.pyenv/versions/3.6.1/lib/python3.6/site-packages/ctypeslib/codegen/codegenerator.py", line 13, in <module>
    from ctypeslib.codegen import clangparser
  File "/Users/riggle/.pyenv/versions/3.6.1/lib/python3.6/site-packages/ctypeslib/codegen/clangparser.py", line 3, in <module>
    from clang.cindex import Index, TranslationUnit
  File "/Users/riggle/.pyenv/versions/3.6.1/lib/python3.6/site-packages/clang/__init__.py", line 29, in <module>
    raise Exception("Only Python 2 is supported.")
Exception: Only Python 2 is supported.
```

**Comment by disconnect3d** [comment]
We have `cymbol` command that adds structures for debugging from header files. Not exactly the same but yeah.

Not doing this. Maybe in the future. Closing for now.
