### ISSUE TITLE
AttributeError: 'module' object has no attribute 'memoize' 

### ISSUE THREAD

**Issue by gsingh93** [pwndbg/pwndbg#35]
After installing pwndbg with setup.sh, when loading gdb pwndbg complained about missing psutil. After installing psutil, I get this:
```
Traceback (most recent call last):
  File "/home/vagrant/tools/pwndbg/gdbinit.py", line 11, in <module>
    import pwndbg
  File "/home/vagrant/tools/pwndbg/pwndbg/__init__.py", line 6, in <module>
    import pwndbg.arch
  File "/home/vagrant/tools/pwndbg/pwndbg/arch.py", line 11, in <module>
    import pwndbg.regs
  File "/home/vagrant/tools/pwndbg/pwndbg/regs.py", line 19, in <module>
    import pwndbg.proc
  File "/home/vagrant/tools/pwndbg/pwndbg/proc.py", line 14, in <module>
    import pwndbg.qemu
  File "/home/vagrant/tools/pwndbg/pwndbg/qemu.py", line 14, in <module>
    @pwndbg.memoize.reset_on_stop
AttributeError: 'module' object has no attribute 'memoize'
```

This is on a fresh Ubuntu 14.04 Vagrant VM.

**Comment by gsingh93** [comment]
Fixed with https://github.com/pwndbg/pwndbg/commit/f5705206b7f47026291982d2c37bc0cf3bfb42cb
