### ISSUE TITLE
AttributeError: 'Elf64_Ehdr' object has no attribute 'objfile'

### ISSUE THREAD

**Issue by zachriggle** [pwndbg/pwndbg#351]
```
Traceback (most recent call last):
  File "/home/pwntools/pwndbg/pwndbg/prompt.py", line 24, in prompt_hook
    pwndbg.events.after_reload(start=False)
  File "/home/pwntools/pwndbg/pwndbg/events.py", line 163, in after_reload
    f()
  File "/home/pwntools/pwndbg/pwndbg/events.py", line 123, in caller
    raise e
  File "/home/pwntools/pwndbg/pwndbg/events.py", line 119, in caller
    func()
  File "/home/pwntools/pwndbg/pwndbg/symbol.py", line 108, in autofetch
    if objfile == pwndbg.elf.exe().objfile:
AttributeError: 'Elf64_Ehdr' object has no attribute 'objfile'
```

**Comment by zachriggle** [comment]
Whoops, apparently I'd made some local modifications that I forgot about, and didn't check first.
