### ISSUE TITLE
ida_script.py:maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by plusls** [pwndbg/pwndbg#353]
### Description

When I use pwndbg with IDA，I connect to IDA successfully.

But, when I run the program, it raise 

```python
xmlrpc.client.Fault: <Fault 1: "<type 'exceptions.RuntimeError'>:maximum recursion depth exceeded while calling a Python object">
```

### Steps to reproduce

1. run ida
2. run `set ida-rpc-host 192.168.137.1` to connect IDA
3. b main
4. r
python raise exception:
```python
Traceback (most recent call last):
  File "/home/plusls/pwndbg/pwndbg/commands/__init__.py", line 100, in __call__
    return self.function(*args, **kwargs)
  File "/home/plusls/pwndbg/pwndbg/commands/__init__.py", line 192, in _OnlyWhenRunning
    return function(*a, **kw)
  File "/home/plusls/pwndbg/pwndbg/commands/nearpc.py", line 119, in nearpc
    pre = pwndbg.ida.Anterior(i.address)
  File "/home/plusls/pwndbg/pwndbg/ida.py", line 93, in __call__
    return self.fn(*args, **kwargs)
  File "/home/plusls/pwndbg/pwndbg/ida.py", line 110, in wrapper
    return function(l2r(address), *args, **kwargs)
  File "/home/plusls/pwndbg/pwndbg/memoize.py", line 48, in __call__
    value = self.func(*args, **kwargs)
  File "/home/plusls/pwndbg/pwndbg/ida.py", line 207, in Anterior
    r = _ida.LineA(addr, i)
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1092, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1432, in __request
    verbose=self.__verbose
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1134, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1150, in single_request
    return self.parse_response(resp)
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1322, in parse_response
    return u.close()
  File "/usr/lib/python3.5/xmlrpc/client.py", line 655, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault 1: "<type 'exceptions.RuntimeError'>:maximum recursion depth exceeded while calling a Python object">
```

### My setup

pwndbg:
Gdb: GNU gdb (Ubuntu 7.12.50.20170314-0ubuntu1.1) 7.12.50.20170314-git
Python: 3.5.3 (default, Sep 14 2017, 22:58:41)  [GCC 6.3.0 20170406]
Pwndbg: 1.0.0 build: 70784f2

IDA:
IDA Pro 7.0

OS:
pwndbg: xubuntu 17.04
IDA: windows10

### Solve
Can delete code `idc.LineA = LineA` in **ida_script.py** line 68 to solve this problem
old code:
```python

def LineA(*a, **kw):
    v = orig_LineA(*a, **kw)
    if v and v.startswith('\x01\x04; '):
        v = v[4:]
    return v


idc.LineA = LineA

mutex = threading.Condition()
```

after edit:
```python

def LineA(*a, **kw):
    v = orig_LineA(*a, **kw)
    if v and v.startswith('\x01\x04; '):
        v = v[4:]
    return v

mutex = threading.Condition()
```

**Comment by disconnect3d** [comment]
@plusIs Could you provide a PR with that? Also, do you know if that works with other IDA Pro versions?

**Comment by zachriggle** [comment]
We don't want to replace it.  The `\x01\x04; ` bit at the beginning is prepended to IDA (internally and invisibly) when adding Hexrays comments to the disassembly (repro: Open function in Hex-rays, switch to disassembly with `tab` and then hit `/`).

**Comment by disconnect3d** [comment]
I guess this bug is not valid anymore so I am closing this issue. I have double checked that and IDA Pro rpc works for me.

**Comment by sven337** [comment]
I have the same problem as the original poster, so maybe this should be reopened? I'm available on IRC.

**Comment by plusls** [comment]
The lastest pwndbg does have this problem.

**Comment by obilodeau** [comment]
Same here:

```
pwndbg> run
Starting program: <strip>/a.out 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".

Breakpoint 1, 0x000055555555520d in main ()
Traceback (most recent call last):
  File "/usr/share/pwndbg/pwndbg/commands/__init__.py", line 135, in __call__
    return self.function(*args, **kwargs)
  File "/usr/share/pwndbg/pwndbg/commands/__init__.py", line 226, in _OnlyWhenRunning
    return function(*a, **kw)
  File "/usr/share/pwndbg/pwndbg/commands/nearpc.py", line 126, in nearpc
    pre = pwndbg.ida.Anterior(instr.address)
  File "/usr/share/pwndbg/pwndbg/ida.py", line 119, in __call__
    return self.fn(*args, **kwargs)
  File "/usr/share/pwndbg/pwndbg/ida.py", line 136, in wrapper
    return function(l2r(address), *args, **kwargs)
  File "/usr/share/pwndbg/pwndbg/memoize.py", line 48, in __call__
    value = self.func(*args, **kwargs)
  File "/usr/share/pwndbg/pwndbg/ida.py", line 240, in Anterior
    r = _ida.LineA(addr, i)
  File "/usr/lib/python3.7/xmlrpc/client.py", line 1112, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.7/xmlrpc/client.py", line 1452, in __request
    verbose=self.__verbose
  File "/usr/lib/python3.7/xmlrpc/client.py", line 1154, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.7/xmlrpc/client.py", line 1170, in single_request
    return self.parse_response(resp)
  File "/usr/lib/python3.7/xmlrpc/client.py", line 1342, in parse_response
    return u.close()
  File "/usr/lib/python3.7/xmlrpc/client.py", line 656, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault 1: "<type 'exceptions.RuntimeError'>:maximum recursion depth exceeded while calling a Python object">

If that is an issue, you can report it on https://github.com/pwndbg/pwndbg/issues
(Please don't forget to search if it hasn't been reported before)
To generate the report and open a browser, you may run `bugreport --run-browser`
PS: Pull requests are welcome
'context': Print out the current register, instruction, and stack context.

    Accepts subcommands 'reg', 'disasm', 'code', 'stack', 'backtrace', and 'args'.
Traceback (most recent call last):
  File "/usr/share/pwndbg/pwndbg/commands/__init__.py", line 135, in __call__
    return self.function(*args, **kwargs)
  File "/usr/share/pwndbg/pwndbg/commands/__init__.py", line 226, in _OnlyWhenRunning
    return function(*a, **kw)
  File "/usr/share/pwndbg/pwndbg/commands/context.py", line 88, in context
    result.extend(func())
  File "/usr/share/pwndbg/pwndbg/commands/context.py", line 184, in context_disasm
    while len(result) < code_lines + 1:
TypeError: object of type 'NoneType' has no len()

If that is an issue, you can report it on https://github.com/pwndbg/pwndbg/issues
(Please don't forget to search if it hasn't been reported before)
To generate the report and open a browser, you may run `bugreport --run-browser`
PS: Pull requests are welcome
```

```
pwndbg> version
Gdb:      8.2.1
Python:   3.7.3 (default, Mar 26 2019, 21:43:19)  [GCC 8.2.1 20181127]
Pwndbg:   1.1.0
Capstone: 4.0.1024
Unicorn:  1.0.1
IDA PRO:  7.1
IDA Py:   2.7.16 (default, Mar 11 2019, 18:59:25) 
[GCC 8.2.1 20181127]
Hexrays:  7.1.0.180227
```
