### ISSUE TITLE
Pwndbg crashes when opening corefiles

### ISSUE THREAD

**Issue by zachriggle** [pwndbg/pwndbg#408]
Just rename the attachment to get the files.

```
$ gdb ./simple_stack_arm ./core.2281
pwndbg: loaded 162 commands. Type pwndbg [filter] for a list.
pwndbg: created $rebase, $ida gdb functions (can be used with print/break)
Set whether to print a full stacktracefor exceptions raised in Pwndbg commands to True
Reading symbols from ./simple_stack_arm...done.

warning: core file may not match specified executable file.

warning: Couldn't find general-purpose registers in core file.

warning: Unexpected size of section `.reg2' in core file.

warning: Could not load shared library symbols for 2 libraries, e.g. /lib/arm-linux-gnueabi/libc.so.6.
Use the "info sharedlibrary" command to see the complete listing.
Do you need "set solib-search-path" or "set sysroot"?
Core was generated by `/labs/labs/simple_stack/simple_stack_arm payload'.

warning: Couldn't find general-purpose registers in core file.

warning: Unexpected size of section `.reg2' in core file.
#0  <unavailable> in ?? ()
Could not check ASLR: Couldn't get personality
'context': Print out the current register, instruction, and stack context.

    Accepts subcommands 'reg', 'disasm', 'code', 'stack', 'backtrace', and 'args'.
Traceback (most recent call last):
  File "/home/pwntools/pwndbg/pwndbg/commands/__init__.py", line 109, in __call__
    return self.function(*args, **kwargs)
  File "/home/pwntools/pwndbg/pwndbg/commands/__init__.py", line 200, in _OnlyWhenRunning
    return function(*a, **kw)
  File "/home/pwntools/pwndbg/pwndbg/commands/context.py", line 81, in context
    result.extend(func())
  File "/home/pwntools/pwndbg/pwndbg/commands/context.py", line 93, in context_regs
    return [pwndbg.ui.banner("registers")] + get_regs()
  File "/home/pwntools/pwndbg/pwndbg/commands/context.py", line 137, in get_regs
    desc = pwndbg.chain.format(value)
  File "/home/pwntools/pwndbg/pwndbg/chain.py", line 92, in format
    chain = get(value, limit, offset, hard_stop, hard_end)
  File "/home/pwntools/pwndbg/pwndbg/chain.py", line 49, in get
    address = address + offset
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

If that is an issue, you can report it on https://github.com/pwndbg/pwndbg/issues
(Please don't forget to search if it hasn't been reported before)
PS: Pull requests are welcome
pwndbg> pi
>>> platform.python_version()
'3.5.2'
>>> platform.platform()
'Linux-4.9.60-linuxkit-aufs-x86_64-with-Ubuntu-16.04-xenial'
```

![attachment tar gz](https://user-images.githubusercontent.com/111640/35309315-aeeb80ae-0060-11e8-8e36-0ce877acc2eb.jpg)

**Comment by zachriggle** [comment]
It looks like this is because the architecture was incorrect, and register information is actually missing.  Using the `i r` command there are no registers.

Not sure how we want to handle this -- having an error message is better than nothing.

**Comment by disconnect3d** [comment]
I have looked on it and I think we can't really do anything here.

I didn't find a way to detect those warnings. I have asked about that on irc on gdb channel on freenode. I am going to reopen this if someone points out something.

That being said I am closing this as WONTFIX (or rather CANTFIX here, huh).
