### ISSUE TITLE
find_fake_chunk and malloc_chunk bug with chunksize 0x7f or similar size

### ISSUE THREAD

**Issue by iromise** [pwndbg/pwndbg#410]
### Description
When I am using find_fake_chunk and malloc_chunk nearby malloc_hook, i just get the following error

```shell
pwndbg> x/8gx 0x7f30f5494b20-16
0x7f30f5494b10 <__malloc_hook>:	0x0000000000000000	0x0000000000000000
0x7f30f5494b20 <main_arena>:	0x0000000000000000	0x0000000000000000
0x7f30f5494b30 <main_arena+16>:	0x000000000143f320	0x0000000000000000
0x7f30f5494b40 <main_arena+32>:	0x0000000000000000	0x0000000000000000      
pwndbg> find_fake_fast 0x7f30f5494b10 0x7f
FAKE CHUNKS
Exception occured: malloc_chunk: Cannot access memory at address 0x7f30f5400000 (<class 'gdb.MemoryError'>)
For more info invoke `set exception-verbose on` and rerun the command
```shell
pwndbg> x/8gx 0x7f30f5494b20-40+8+5
0x7f30f5494b05 <__memalign_hook+5>:	0x30f5155a0000007f	0x000000000000007f
0x7f30f5494b15 <__malloc_hook+5>:	0x0000000000000000	0x0000000000000000
0x7f30f5494b25 <main_arena+5>:	0x0000000000000000	0x000143f320000000
0x7f30f5494b35 <main_arena+21>:	0x0000000000000000	0x0000000000000000
pwndbg> malloc_chunk 0x7f30f5494b05
Traceback (most recent call last):
  File "/home/iromise/pwndbg/pwndbg/commands/__init__.py", line 109, in __call__
    return self.function(*args, **kwargs)
  File "/home/iromise/pwndbg/pwndbg/commands/__init__.py", line 200, in _OnlyWhenRunning
    return function(*a, **kw)
  File "/home/iromise/pwndbg/pwndbg/commands/heap.py", line 203, in malloc_chunk
    fastbins = main_heap.fastbins(arena)
  File "/home/iromise/pwndbg/pwndbg/heap/ptmalloc.py", line 212, in fastbins
    arena = self.get_arena(arena_addr)
  File "/home/iromise/pwndbg/pwndbg/heap/ptmalloc.py", line 159, in get_arena
    return pwndbg.memory.poi(self.malloc_state, arena_addr)
  File "/home/iromise/pwndbg/pwndbg/memory.py", line 285, in poi
    return gdb.Value(addr).cast(type.pointer()).dereference()
gdb.MemoryError: Cannot access memory at address 0x7f30f5400000
```

### Steps to reproduce
Use any dynamic linked binary with heap action, and remember the chunk size should be 0x7f or similar size.

### My setup

ldd (Ubuntu GLIBC 2.23-0ubuntu10) 2.23

### bug location(maybe)
I think it is because the size of chunk near malloc_hook is 0x7f and this will cause non_main_arena=1, and this is the bug.
```python
    prev_inuse, is_mmapped, non_main_arena = main_heap.chunk_flags(size)
    arena = None
    if non_main_arena:
        arena = main_heap.get_heap(addr)['ar_ptr']
```
here is the code location. https://github.com/pwndbg/pwndbg/blob/8aea51aa477362062d6b050a390eb14ff8b86d9b/pwndbg/commands/heap.py#L198

when i comment it just as a guess, it works.

**Comment by mak** [comment]
Actually there was another but `heap.global_max_fast` was returning an address instead of value.
Checking for `non_main_arena` is not a bug, its a proper behavior for normal chunk, there should be a way to signal that chunk is not normal so this path can be skipped

**Comment by iromise** [comment]
yeah, we just need some check.

**Comment by iromise** [comment]
As it is fixed, closed.
