### ISSUE TITLE
bug of function get_load_segment_info in readelf.py

### ISSUE THREAD

**Issue by Bluekezhou** [pwndbg/pwndbg#427]
when I got readelf result like below
```
readelf --program-headers /bin/ls | grep "LOAD" -A 10
  LOAD           0x0000000000000000 0x0000000000400000 0x0000000000400000
                 0x000000000001da64 0x000000000001da64  R E    200000
```
the function crashed at line 65
```
65   fsize, msize, read, write, execute, align = re_secnd.match(line).groups()
```
the reason is in the regex format
```python
re_secnd = re.compile(r"\s+(0x[0-9A-Fa-f]+) (0x[0-9A-Fa-f]+)  (.)(.)(.)\s+(**0x**[0-9A-Fa-f]+)"
```
I mean, "0x" should not a absolute prefix of align number

**Comment by disconnect3d** [comment]
Hey, thanks for reporting this bug!

For me it happens only on machine with GDB with Py2 (but its probably unrelated to Py version, see below):

Launched on `/bin/ls` binary:
```
pwndbg> version
e requires the readline library
pwndbg: loaded 165 commands. Type pwndbg [filter] for a list.
pwndbg: created $rebase, $ida gdb functions (can be used with print/break)
Reading symbols from /bin/ls...(no debugging symbols found)...done.

pwndbg> version
Gdb:      GNU gdb (Debian 7.7.1+dfsg-5) 7.7.1
Python:   2.7.9 (default, Jun 29 2016, 13:11:10)  [GCC 4.9.2]
Pwndbg:   1.0.0 build: 1a5e134
Capstone: 4.0.1024
Unicorn:  1.0.0

pwndbg> xinfo
Extended information for virtual address 0x4048c5:

  Containing mapping:
          0x400000           0x41c000 r-xp    1c000 0      /bin/ls

  Offset information:
         Mapped Area 0x4048c5 = 0x400000 + 0x48c5
       File (Memory) 0x4048c5 = 0x400000 + 0x48c5
Traceback (most recent call last):
  File "/home/dc/pwndbg/pwndbg/commands/__init__.py", line 109, in __call__
    return self.function(*args, **kwargs)
  File "/home/dc/pwndbg/pwndbg/commands/__init__.py", line 200, in _OnlyWhenRunning
    return function(*a, **kw)
  File "/home/dc/pwndbg/pwndbg/commands/xinfo.py", line 105, in xinfo
    xinfo_mmap_file(page, addr)
  File "/home/dc/pwndbg/pwndbg/commands/xinfo.py", line 70, in xinfo_mmap_file
    for segment in pwndbg.wrappers.readelf.get_load_segment_info():
  File "/home/dc/pwndbg/pwndbg/commands/__init__.py", line 189, in _OnlyWithFile
    return function(*a, **kw)
  File "/home/dc/pwndbg/pwndbg/wrappers/__init__.py", line 28, in _OnlyWithCommand
    return function(*a, **kw)
  File "/home/dc/pwndbg/pwndbg/wrappers/readelf.py", line 65, in get_load_segment_info
    fsize, msize, read, write, execute, align = re_secnd.match(line).groups()
AttributeError: 'NoneType' object has no attribute 'groups'
```

**Comment by disconnect3d** [comment]
To clarify the bug report even further, the bug comes from the fact that the `Align` value presented in `readelf ...` output doesn't always have a prefix of `0x`.

Example output for two different readelf versions can be seen below (`#` is a comment):

```
Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align

# GNU readelf (GNU Binutils for Debian) 2.25 (2014):
  LOAD           0x0000000000000000 0x0000000000400000 0x0000000000400000
                 0x000000000001bad4 0x000000000001bad4  R E    200000

# GNU readelf (GNU Binutils) 2.29.1 (2017):
  LOAD           0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x000000000001e050 0x000000000001e050  R E    0x200000
```

The regex in our code matches the second line of the presented outputs.

**Comment by disconnect3d** [comment]
The pointed out issue has been fixed by https://github.com/pwndbg/pwndbg/pull/433 ; but I have found another issue that relates strictly to binaries without PIE. Gonna open another issue.
