### ISSUE TITLE
command eX crashed in the newest dev version

### ISSUE THREAD

**Issue by ripples-alive** [pwndbg/pwndbg#436]
### Description

When I tried to write some value into memory, I got crashed errors.

```
pwndbg> version
Gdb:      GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Python:   3.5.2 (default, Nov 23 2017, 16:37:01)  [GCC 5.4.0 20160609]
Pwndbg:   1.0.0 build: 12d1aef
Capstone: 4.0.1024
Unicorn:  1.0.1

pwndbg> eq 0x00007ffff7bcd010 1
'eq': Write hex qwords at the specified address.
Traceback (most recent call last):
  File "/root/pwndbg/pwndbg/commands/__init__.py", line 109, in __call__
    return self.function(*args, **kwargs)
  File "/root/pwndbg/pwndbg/commands/__init__.py", line 200, in _OnlyWhenRunning
    return function(*a, **kw)
  File "/root/pwndbg/pwndbg/commands/windbg.py", line 148, in eq
    return eX(8, address, data)
  File "/root/pwndbg/pwndbg/commands/windbg.py", line 188, in eX
    pwndbg.memory.write(address + (i * size), data)
  File "/root/pwndbg/pwndbg/memory.py", line 103, in write
    gdb.selected_inferior().write_memory(addr, bytes(data, 'utf8'))
TypeError: encoding without a string argument
```

Seems it's related to PR #432 .
`data` is already bytes (generated by `codecs.decode`), except in `ez` command.

**Comment by disconnect3d** [comment]
Hey,

Thanks for reporting this. Seems this issue was made by my last patch.
Let me fix that soon.
