### ISSUE TITLE
Unable to debug process in docker with gdb of host

### ISSUE THREAD

**Issue by hzshang** [pwndbg/pwndbg#446]
### Description
when I attach a process in a docker using gdb of host, it shows the following errors. 
However, gdb-peda works fine.

```
pwndbg> shell pidof message_me
29407
pwndbg> attach 29407
Attaching to process 29407
Reading symbols from target:/pwn/message_me...(no debugging symbols found)...done.
Reading symbols from target:/lib/x86_64-linux-gnu/libc.so.6...Reading symbols from /usr/lib/debug/lib/x86_64-linux-gnu//libc-2.23.so...done.
done.
Reading symbols from target:/lib64/ld-linux-x86-64.so.2...(no debugging symbols found)...done.
warning: Target and debugger are in different PID namespaces; thread lists and other data are likely unreliable
0x00007f187fbf5260 in __read_nocancel () at ../sysdeps/unix/syscall-template.S:84
84	../sysdeps/unix/syscall-template.S: No such file or directory.
Exception occured: Error:    Message System
 (<class 'http.client.BadStatusLine'>)
For more info invoke `set exception-verbose on` and rerun the command
Python Exception <class 'http.client.BadStatusLine'>    Message System
:
Exception occured: Error:    Message System
 (<class 'http.client.BadStatusLine'>)
For more info invoke `set exception-verbose on` and rerun the command
Python Exception <class 'http.client.BadStatusLine'>    Message System
:
Exception occured: Error:    Message System
 (<class 'http.client.BadStatusLine'>)
For more info invoke `set exception-verbose on` and rerun the command
Python Exception <class 'http.client.BadStatusLine'>    Message System
:
pwndbg> set exception-verbose on
Set whether to print a full stacktracefor exceptions raised in Pwndbg commands to True
Traceback (most recent call last):
  File "/home/hzshang/pwndbg/pwndbg/events.py", line 119, in caller
    func()
  File "/home/hzshang/pwndbg/pwndbg/ida.py", line 119, in __call__
    return self.fn(*args, **kwargs)
  File "/home/hzshang/pwndbg/pwndbg/ida.py", line 274, in UpdateBreakpoints
    want = set(GetBreakpoints())
  File "/home/hzshang/pwndbg/pwndbg/ida.py", line 250, in GetBreakpoints
    for i in range(GetBptQty()):
  File "/home/hzshang/pwndbg/pwndbg/ida.py", line 119, in __call__
    return self.fn(*args, **kwargs)
  File "/home/hzshang/pwndbg/pwndbg/ida.py", line 256, in GetBptQty
    return _ida.GetBptQty()
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1092, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1432, in __request
    verbose=self.__verbose
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1134, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1147, in single_request
    resp = http_conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 279, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine:    Message System

```

### My setup

pwndbg> version
Gdb:      GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Python:   3.5.2 (default, Nov 23 2017, 16:37:01)  [GCC 5.4.0 20160609]
Pwndbg:   1.0.0 build: 0323e76
Capstone: 4.0.1024
Unicorn:  1.0.1

**Comment by disconnect3d** [comment]
@hzshang hey, thanks for reporting the issue. Would you mind looking on how to fix that?

**Comment by disconnect3d** [comment]
@hzshang The `gdb attach` into binary run in a docker container **works for me** (```docker run --rm -it -v `pwd`:/task ubuntu bash``` and `sudo gdb ./a.out` - then pidof and attach).

From your stacktrace it seems that your problem comes from IDA Pro integration.
Did you use IDA Pro at that time or had some server on port 8888 (this is the port we try to connect to automatically)?

You can always do `set ida-enabled off` to disable IDA Pro automatic connection.

**Comment by hzshang** [comment]
Thanks for support, I expose port 8888 for ncat service.  I replace the port  and it works.    

Maybe it's not a bug, sorry for mistake.

**Comment by disconnect3d** [comment]
Np, enjoy! ;)
