### ISSUE TITLE
When Using IDA: Exception: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by Alexeyan** [pwndbg/pwndbg#454]
### Description

While pwndbg on its own works, i tried the IDA-connection today and stumbled upon a few errors and exceptions.

```
pwndbg> start
Temporary breakpoint 1 at 0x555555554af0
Temporary breakpoint 1, 0x0000555555554af0 in ?? ()
Exception occured: nearpc: <Fault 1: "<type 'exceptions.RuntimeError'>:maximum recursion depth exceeded while calling a Python object"> (<class 'xmlrpc.client.Fault'>)
For more info invoke set exception-verbose on and rerun the command
'context': Print out the current register, instruction, and stack context.

Accepts subcommands 'reg', 'disasm', 'code', 'stack', 'backtrace', and 'args'.
Exception occured: context: object of type 'NoneType' has no len() (<class 'TypeError'>)
For more info invoke set exception-verbose on and rerun the command
```

First issue was that args returned `None` in this instance, which made `args.insert` fail, so i added the check to further investigate
```
def context_args(with_banner=True):
    args = pwndbg.arguments.format_args(pwndbg.disasm.one())

    # early exit to skip section if no arg found
    if not args:
        return []

    if with_banner:
        args.insert(0, pwndbg.ui.banner("arguments"))

    return args

[...]

Traceback (most recent call last):
  File "/vagrant/pwndbg/pwndbg/commands/__init__.py", line 109, in __call__
    return self.function(*args, **kwargs)
  File "/vagrant/pwndbg/pwndbg/commands/__init__.py", line 200, in _OnlyWhenRunning
    return function(*a, **kw)
  File "/vagrant/pwndbg/pwndbg/commands/context.py", line 86, in context
    result.extend(func())
TypeError: 'NoneType' object is not iterable

(Pdb) func
<function context_disasm at 0x7f6fbba407b8>

(Pdb) func()
Traceback (most recent call last):
  File "/vagrant/pwndbg/pwndbg/commands/__init__.py", line 109, in __call__
    return self.function(*args, **kwargs)
  File "/vagrant/pwndbg/pwndbg/commands/__init__.py", line 200, in _OnlyWhenRunning
    return function(*a, **kw)
  File "/vagrant/pwndbg/pwndbg/commands/context.py", line 86, in context
    result.extend(func())
TypeError: 'NoneType' object is not iterable
```

My guess would be that pwndbg tries to disassemble at the rebased address, since the binary is a position-independent executable? 

### Steps to reproduce

If needed i can upload the binary.

### My setup

OS: Ubuntu 18.04 on Virtualbox
Gdb:      GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git
Python:   3.6.5 (default, Apr  1 2018, 05:46:30)  [GCC 7.3.0]
Pwndbg:   1.0.0 build: 448dd06 // current dev branch
Capstone: 4.0.1024
Unicorn:  1.0.1
IDA Pro: 7.0

**Comment by disconnect3d** [comment]
Hey,

What Python version do you use in IDA? Also, the IDA is on Windows and pwndbg on a VM, right?

Can you also provide result of `start` with `set exception-verbose on` invoked before?

**Comment by Alexeyan** [comment]
Python 2.7.10 (default, Oct  6 2017, 22:29:07) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)] 
IDAPython 64-bit v1.7.0 final (serial 0) (c) The IDAPython Team <idapython@googlegroups.com>

It's actually IDA Pro on MacOS Host and pwndbg in Linux Guest
On the current dev branch:
```
pwndbg> set exception-verbose on
Set whether to print a full stacktracefor exceptions raised in Pwndbg commands to True
pwndbg> start
Temporary breakpoint 1 at 0x555555554af0

Temporary breakpoint 1, 0x0000555555554af0 in ?? ()
Traceback (most recent call last):
  File "/vagrant/pwndbg/pwndbg/commands/__init__.py", line 109, in __call__
    return self.function(*args, **kwargs)
  File "/vagrant/pwndbg/pwndbg/commands/__init__.py", line 200, in _OnlyWhenRunning
    return function(*a, **kw)
  File "/vagrant/pwndbg/pwndbg/commands/nearpc.py", line 126, in nearpc
    pre = pwndbg.ida.Anterior(instr.address)
  File "/vagrant/pwndbg/pwndbg/ida.py", line 119, in __call__
    return self.fn(*args, **kwargs)
  File "/vagrant/pwndbg/pwndbg/ida.py", line 136, in wrapper
    return function(l2r(address), *args, **kwargs)
  File "/vagrant/pwndbg/pwndbg/memoize.py", line 48, in __call__
    value = self.func(*args, **kwargs)
  File "/vagrant/pwndbg/pwndbg/ida.py", line 240, in Anterior
    r = _ida.LineA(addr, i)
  File "/usr/lib/python3.6/xmlrpc/client.py", line 1112, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.6/xmlrpc/client.py", line 1452, in __request
    verbose=self.__verbose
  File "/usr/lib/python3.6/xmlrpc/client.py", line 1154, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.6/xmlrpc/client.py", line 1170, in single_request
    return self.parse_response(resp)
  File "/usr/lib/python3.6/xmlrpc/client.py", line 1342, in parse_response
    return u.close()
  File "/usr/lib/python3.6/xmlrpc/client.py", line 656, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault 1: "<type 'exceptions.RuntimeError'>:maximum recursion depth exceeded while calling a Python object">

If that is an issue, you can report it on https://github.com/pwndbg/pwndbg/issues
(Please don't forget to search if it hasn't been reported before)
PS: Pull requests are welcome
'context': Print out the current register, instruction, and stack context.

    Accepts subcommands 'reg', 'disasm', 'code', 'stack', 'backtrace', and 'args'.
Traceback (most recent call last):
  File "/vagrant/pwndbg/pwndbg/commands/__init__.py", line 109, in __call__
    return self.function(*args, **kwargs)
  File "/vagrant/pwndbg/pwndbg/commands/__init__.py", line 200, in _OnlyWhenRunning
    return function(*a, **kw)
  File "/vagrant/pwndbg/pwndbg/commands/context.py", line 86, in context
    result.extend(func())
  File "/vagrant/pwndbg/pwndbg/commands/context.py", line 182, in context_disasm
    while len(result) < code_lines + 1:
TypeError: object of type 'NoneType' has no len()

If that is an issue, you can report it on https://github.com/pwndbg/pwndbg/issues
(Please don't forget to search if it hasn't been reported before)
PS: Pull requests are welcome
```
And after fixing the result 'None'-check:
```
pwndbg> set exception-verbose on
Set whether to print a full stacktracefor exceptions raised in Pwndbg commands to True
pwndbg> start
Temporary breakpoint 1 at 0x555555554af0

Temporary breakpoint 1, 0x0000555555554af0 in ?? ()
Traceback (most recent call last):
  File "/vagrant/pwndbg/pwndbg/commands/__init__.py", line 109, in __call__
    return self.function(*args, **kwargs)
  File "/vagrant/pwndbg/pwndbg/commands/__init__.py", line 200, in _OnlyWhenRunning
    return function(*a, **kw)
  File "/vagrant/pwndbg/pwndbg/commands/nearpc.py", line 126, in nearpc
    pre = pwndbg.ida.Anterior(instr.address)
  File "/vagrant/pwndbg/pwndbg/ida.py", line 119, in __call__
    return self.fn(*args, **kwargs)
  File "/vagrant/pwndbg/pwndbg/ida.py", line 136, in wrapper
    return function(l2r(address), *args, **kwargs)
  File "/vagrant/pwndbg/pwndbg/memoize.py", line 48, in __call__
    value = self.func(*args, **kwargs)
  File "/vagrant/pwndbg/pwndbg/ida.py", line 240, in Anterior
    r = _ida.LineA(addr, i)
  File "/usr/lib/python3.6/xmlrpc/client.py", line 1112, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.6/xmlrpc/client.py", line 1452, in __request
    verbose=self.__verbose
  File "/usr/lib/python3.6/xmlrpc/client.py", line 1154, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.6/xmlrpc/client.py", line 1170, in single_request
    return self.parse_response(resp)
  File "/usr/lib/python3.6/xmlrpc/client.py", line 1342, in parse_response
    return u.close()
  File "/usr/lib/python3.6/xmlrpc/client.py", line 656, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault 1: "<type 'exceptions.RuntimeError'>:maximum recursion depth exceeded while calling a Python object">

If that is an issue, you can report it on https://github.com/pwndbg/pwndbg/issues
(Please don't forget to search if it hasn't been reported before)
PS: Pull requests are welcome
'context': Print out the current register, instruction, and stack context.

    Accepts subcommands 'reg', 'disasm', 'code', 'stack', 'backtrace', and 'args'.
Traceback (most recent call last):
  File "/vagrant/pwndbg/pwndbg/commands/__init__.py", line 109, in __call__
    return self.function(*args, **kwargs)
  File "/vagrant/pwndbg/pwndbg/commands/__init__.py", line 200, in _OnlyWhenRunning
    return function(*a, **kw)
  File "/vagrant/pwndbg/pwndbg/commands/context.py", line 86, in context
    result.extend(func())
TypeError: 'NoneType' object is not iterable

If that is an issue, you can report it on https://github.com/pwndbg/pwndbg/issues
(Please don't forget to search if it hasn't been reported before)
PS: Pull requests are welcome
```

**Comment by disconnect3d** [comment]
@Alexeyan Any chance to debug this together? Can you get into irc? #pwndbg on freenode

**Comment by disconnect3d** [comment]
It seems the bug doesn't appear after https://github.com/pwndbg/pwndbg/pull/455

There is another problem tho: IDA might hang on decompiling `_start` for the first time. But it seems more like an IDA problem - a workaround would be to trying decompiling it manually so it caches that it cannot do it...
