### ISSUE TITLE
Don't show stacktrace when ebp points to invalid memory

### ISSUE THREAD

**Issue by gsingh93** [pwndbg/pwndbg#46]
Otherwise you get something like this:
```
Traceback (most recent call last):
  File "/vagrant/pwndbg/pwndbg/events.py", line 98, in caller
    func()
  File "/vagrant/pwndbg/pwndbg/arch.py", line 32, in update
    m.current = fix_arch(gdb.selected_frame().architecture().name())
gdb.MemoryError: Cannot access memory at address 0x41414145
Python Exception <class 'gdb.MemoryError'> Cannot access memory at address 0x41414145:
```

**Comment by zachriggle** [comment]
The appropriate fix is to wrap that line in an exception handler.  Separately, that should only ever be called once, when a new binary is selected

**Comment by zachriggle** [comment]
I can't reproduce this:

```
pwndbg> set $rbp=0xdeadbeef
pwndbg> set $rsp=0xcafebabe
pwndbg> pi
>>> gdb.selected_frame().architecture().name()
'i386:x86-64'
```

**Comment by gsingh93** [comment]
I can reproduce, I'll PM you the code/binary. Please reopen.

**Comment by zachriggle** [comment]
This doesn't have to do with the stack trace, it has to do with GDB being internally broken and throwing an exception inside of `gdb.selected_frame()`.  It also appears to only be an issue on i386, not e.g. amd6t4.

```
$ asm nop -felf > nop
$ gdb --batch --ex 'start' --ex 'set $ebp=0xdeadbeef' --ex si --ex context --args ./nop
Loaded 94 commands.  Type pwndbg for a list.
Temporary breakpoint 1 at 0x8049074

Temporary breakpoint 1, 0x08049074 in ?? ()
Cannot access memory at address 0xdeadbef3
0x08049075 in ?? ()
Traceback (most recent call last):
  File "/home/user/pwndbg/pwndbg/events.py", line 105, in caller
    func()
  File "/home/user/pwndbg/pwndbg/arch.py", line 32, in update
    m.current = fix_arch(gdb.selected_frame().architecture().name())
gdb.MemoryError: Cannot access memory at address 0xdeadbef3
```

Worked-around with b987b4141281c6e4922923c82ca972f71479ab46

**Comment by zachriggle** [comment]
Now only the `Cannot access memory` message is shown, and it is not possible to be muted.
