### ISSUE TITLE
High Sierra Successful install but Error on GDB start

### ISSUE THREAD

**Issue by danielnehrig** [pwndbg/pwndbg#468]
### Description
Python Error on gdb startup
```
GNU gdb (GDB) 8.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-apple-darwin17.5.0".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
Traceback (most recent call last):
  File "/Users/dnehrig/prog/pwndbg/gdbinit.py", line 36, in <module>
    import pwndbg # isort:skip
  File "/Users/dnehrig/prog/pwndbg/pwndbg/__init__.py", line 14, in <module>
    import pwndbg.arguments
  File "/Users/dnehrig/prog/pwndbg/pwndbg/arguments.py", line 16, in <module>
    import pwndbg.abi
  File "/Users/dnehrig/prog/pwndbg/pwndbg/abi.py", line 174, in <module>
    update()
  File "/Users/dnehrig/prog/pwndbg/pwndbg/abi.py", line 152, in update
    % abi
NameError: global name 'abi' is not defined
(gdb)
```

### Steps to reproduce
High Sierra
gdb --version 8.1 installed over brew
followed install instructions
setup exit code 0

### My setup
gdb --version
8.1

python --version
Python 2.7.15

pwndbg on current HEAD
commit c3e32375e125430f63d8b72e38cc7fff86702e59

High Sierra 10.13.4
2.7.15 (default, May  1 2018, 16:44:08)
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)]

**Comment by disconnect3d** [comment]
@inet-pwnZ Hey,

Thanks for reporting the bug. Can you show the result of `show osabi` command inside GDB on your system?

**Comment by danielnehrig** [comment]
```
(gdb) show osabi
The current OS ABI is "auto" (currently "none").
(gdb)
```

**Comment by disconnect3d** [comment]
@inet-pwnZ I have applied a hotfix in https://github.com/pwndbg/pwndbg/pull/469

Can you try after that?

**Comment by danielnehrig** [comment]
Pulled hotfix
now it's working
