### ISSUE TITLE
TypeError exception raised on up/down commands.

### ISSUE THREAD

**Issue by Matir** [pwndbg/pwndbg#472]
### Description

When running the command `up` or `down` with an integer argument, the following exception is raised:

```
Traceback (most recent call last):
  File "/home/david/.pwndbg/pwndbg/commands/__init__.py", line 109, in __call__
    return self.function(*args, **kwargs)
  File "/home/david/.pwndbg/pwndbg/commands/__init__.py", line 200, in _OnlyWhenRunning
    return function(*a, **kw)
  File "/home/david/.pwndbg/pwndbg/commands/ida.py", line 46, in up
    for i in range(n):
TypeError: 'str' object cannot be interpreted as an integer
```

### Steps to reproduce

Open any binary and attempt to do `up 2` during debugging.

### My setup

pwndbg> version
Gdb:      7.12.0.20161007-git
Python:   3.6.5rc1 (default, Mar 14 2018, 06:54:23)  [GCC 7.3.0]
Pwndbg:   1.0.0 build: f69b81e
Capstone: 4.0.1024
Unicorn:  1.0.1

**Comment by disconnect3d** [comment]
Thx!
