### ISSUE TITLE
cannot use pwndbg on manjaro

### ISSUE THREAD

**Issue by lometsj** [pwndbg/pwndbg#545]
i found two package by `pacman -Ss pwndbg`:pwndbg and pwndbg-git
unfortunately,i can't use either of it

both occur error when i try to run gdb:
```
$ gdb                 
GNU gdb (GDB) 8.2
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
Traceback (most recent call last):
  File "/usr/share/pwndbg/gdbinit.py", line 36, in <module>
    import pwndbg # isort:skip
  File "/usr/share/pwndbg/pwndbg/__init__.py", line 14, in <module>
    import pwndbg.arguments
  File "/usr/share/pwndbg/pwndbg/arguments.py", line 18, in <module>
    import pwndbg.chain
  File "/usr/share/pwndbg/pwndbg/chain.py", line 14, in <module>
    import pwndbg.enhance
  File "/usr/share/pwndbg/pwndbg/enhance.py", line 30, in <module>
    from pwndbg.color.syntax_highlight import syntax_highlight
  File "/usr/share/pwndbg/pwndbg/color/syntax_highlight.py", line 26, in <module>
    formatter = pygments.formatters.Terminal256Formatter(style=str(style))
AttributeError: 'NoneType' object has no attribute 'formatters'
```
it seems like str(style) returns a none type object.
could u please help me about it.

**Comment by disconnect3d** [comment]
@anthraxx any ideas here?

**Comment by anthraxx** [comment]
Yeah just close it, there was a python dep usage bug in the dependency list it should hit repo soon

**Comment by disconnect3d** [comment]
Kk, thanks!

**Comment by Peng-Hu** [comment]
> 
I also have this problem, how to solve it.
“ it should hit repo soon” means what?
