### ISSUE TITLE
r2: 'NoneType' object has no attribute 'cast' (<class 'AttributeError'>)

### ISSUE THREAD

**Issue by Cryptoshade** [pwndbg/pwndbg#581]
### Description

This happens when i initiate r2 after loading a binary in pwndbg 
I have tested both in  wsl and a 64bit ubuntu machine same behavior sorta 

### Steps to reproduce

1. Load a binary 
2. Run r2 
Exception occured: r2: 'NoneType' object has no attribute 'cast' (<class 'AttributeError'>)
Traceback (most recent call last):
  File "/root/reverse/pwndbg/pwndbg/commands/__init__.py", line 135, in __call__
    return self.function(*args, **kwargs)
  File "/root/reverse/pwndbg/pwndbg/commands/__init__.py", line 215, in _OnlyWithFile
    return function(*a, **kw)
  File "/root/reverse/pwndbg/pwndbg/commands/radare2.py", line 28, in r2
    addr = pwndbg.regs.pc
  File "/root/reverse/pwndbg/pwndbg/memoize.py", line 48, in __call__
    value = self.func(*args, **kwargs)
  File "/root/reverse/pwndbg/pwndbg/regs.py", line 280, in __getattr__
    value = value.cast(pwndbg.typeinfo.ptrdiff)
AttributeError: 'NoneType' object has no attribute 'cast'

### My setup

Gdb:      7.11.1
Python:   3.5.2 (default, Nov 12 2018, 13:43:14)  [GCC 5.4.0 20160609]
Pwndbg:   1.1.0 build: 054f209
Capstone: 4.0.1024
Unicorn:  1.0.1

**Comment by disconnect3d** [comment]
@anthraxx can you check this out?

**Comment by sudhackar** [comment]
I can help here. When the program is not running we can start r2 with default parameters without any address. @disconnect3d I'll send a PR today if that's okay?

**Comment by disconnect3d** [comment]
Sure, thanks!
