### ISSUE TITLE
IDA Integration: exceptions.OverflowError long int exceeds XML-RPC limits

### ISSUE THREAD

**Issue by obilodeau** [pwndbg/pwndbg#612]
### Description

IDA Integration fails with some binaries throwing the following exception when trying to reach your first breakpoint:

```
pwndbg> b main
Breakpoint 1 at 0x120d
pwndbg> run
Starting program: <strip>/a.out 
Exception occured: Error: <Fault 1: "<type 'exceptions.OverflowError'>:long int exceeds XML-RPC limits"> (<class 'xmlrpc.client.Fault'>)
For more info invoke `set exception-verbose on` and rerun the command
or debug it by yourself with `set exception-debugger on`
Python Exception <class 'xmlrpc.client.Fault'> <Fault 1: "<type 'exceptions.OverflowError'>:long int exceeds XML-RPC limits">: 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".

Breakpoint 1, 0x000055555555520d in main ()
```

I don't understand what is crashing the binary. I thought it was because it was a PIE executable but I've tried on other binaries and it doesn't crash.

Here's the full stacktrace:

```
pwndbg> b main
Breakpoint 1 at 0x55555555520d
pwndbg> run
Starting program: <strip>/a.out 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".

Breakpoint 1, 0x000055555555520d in main ()
Traceback (most recent call last):
  File "/usr/share/pwndbg/pwndbg/events.py", line 169, in caller
    func()
  File "/usr/share/pwndbg/pwndbg/ida.py", line 119, in __call__
    return self.fn(*args, **kwargs)
  File "/usr/share/pwndbg/pwndbg/ida.py", line 309, in Auto_Color_PC
    SetColor(colored_pc, 0x7f7fff)
  File "/usr/share/pwndbg/pwndbg/ida.py", line 119, in __call__
    return self.fn(*args, **kwargs)
  File "/usr/share/pwndbg/pwndbg/ida.py", line 136, in wrapper
    return function(l2r(address), *args, **kwargs)
  File "/usr/share/pwndbg/pwndbg/ida.py", line 165, in l2r
    result = (addr - int(exe.address) + base()) & pwndbg.arch.ptrmask
  File "/usr/share/pwndbg/pwndbg/memoize.py", line 48, in __call__
    value = self.func(*args, **kwargs)
  File "/usr/share/pwndbg/pwndbg/ida.py", line 186, in base
    segaddr = _ida.NextSeg(0)
  File "/usr/lib/python3.7/xmlrpc/client.py", line 1112, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.7/xmlrpc/client.py", line 1452, in __request
    verbose=self.__verbose
  File "/usr/lib/python3.7/xmlrpc/client.py", line 1154, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.7/xmlrpc/client.py", line 1170, in single_request
    return self.parse_response(resp)
  File "/usr/lib/python3.7/xmlrpc/client.py", line 1342, in parse_response
    return u.close()
  File "/usr/lib/python3.7/xmlrpc/client.py", line 656, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault 1: "<type 'exceptions.OverflowError'>:long int exceeds XML-RPC limits">
```

### Steps to reproduce

1. Open binary in IDA Pro
1. Run the `ida_script.py` script
1. Start pwndbg, break on `main`
1. `run`

### My setup

On Arch linux but I don't think this is related to the crash since other binaries work fine.

```
pwndbg> version
Pwndbg successfully connected to Ida Pro xmlrpc: http://127.0.0.1:31337
Gdb:      8.2.1
Python:   3.7.3 (default, Mar 26 2019, 21:43:19)  [GCC 8.2.1 20181127]
Pwndbg:   1.1.0
Capstone: 4.0.1024
Unicorn:  not found
IDA PRO:  7.1
IDA Py:   2.7.16 (default, Mar 11 2019, 18:59:25) 
[GCC 8.2.1 20181127]
Hexrays:  7.1.0.180227
```

**Comment by obilodeau** [comment]
I understand how to reproduce it now. You need to debug the binary in IDA first. Addresses stored within IDA will have their base all shifted by `0x5555...` which is larger than the RPC's `int32` wire protocol.

So a workaround, if you face this issue, is to restart with a fresh idb.

**Comment by disconnect3d** [comment]
Oh, that's interesting. Thanks for investigating this.

So... is there anything we can do here?
Can we detect that the base address is binary on the IDA side and "fix it"?

**Comment by disconnect3d** [comment]
@obilodeau Could you please check whether it is possible to retrieve an offset instead of rebased address in IDA, so maybe we could use that instead?

Or we could `try/except` this error and inform the user that this particular thing might be the catch/issue?

**Comment by disconnect3d** [comment]
Pretty sure this is outdated / not relevant anymore. Closing.

**Comment by obilodeau** [comment]
Sorry for the lack of updates. Yes, close it, I don't recall any of this and I don't use IDA Pro anymore anyway.
