### ISSUE TITLE
TypeError 'None' with heap command on LD_PRELOADed libc

### ISSUE THREAD

**Issue by suidpit** [pwndbg/pwndbg#684]
### Description

`heap` command fails when LD_PRELOADing a different libc to the binary. Exception is the following:
```
pwndbg> heap                                                                                                                                                  
'heap': Prints out chunks starting from the address specified by `addr`.                                                                                      
Traceback (most recent call last):                                                                                                                            
  File "/home/pete/grimorium/pwndbg/pwndbg/commands/__init__.py", line 135, in __call__                                                                       
    return self.function(*args, **kwargs)                                                                                                                     
  File "/home/pete/grimorium/pwndbg/pwndbg/commands/__init__.py", line 226, in _OnlyWhenRunning                                                               
    return function(*a, **kw)                                                                                                                                 
  File "/home/pete/grimorium/pwndbg/pwndbg/commands/__init__.py", line 234, in _OnlyWhenHeapIsInitialized                                                     
    if pwndbg.heap.current.is_initialized():                                                                                                                  
  File "/home/pete/grimorium/pwndbg/pwndbg/heap/ptmalloc.py", line 573, in is_initialized                                                                     
    return self.global_max_fast != 0                                                                                                                          
  File "/home/pete/grimorium/pwndbg/pwndbg/heap/ptmalloc.py", line 200, in global_max_fast                                                                    
    return pwndbg.memory.u(addr)                                                                                                                              
  File "/home/pete/grimorium/pwndbg/pwndbg/memory.py", line 245, in u                                                                                         
    }[size](addr)                                                                                                                                             
  File "/home/pete/grimorium/pwndbg/pwndbg/memory.py", line 228, in u64                                                                                       
    return readtype(pwndbg.typeinfo.uint64, addr)                                                                                                             
  File "/home/pete/grimorium/pwndbg/pwndbg/memory.py", line 87, in readtype                                                                                   
    return int(gdb.Value(addr).cast(gdb_type.pointer()).dereference())                                                                                        
TypeError: Could not convert Python object: None.
```

### Steps to reproduce

`LD_PRELOAD=./libc.so.6 gdb <binary>`
then break after the heap should be initialized, and execute `heap` command.

### My setup

Platform: Linux-4.15.0-66-generic-x86_64-with-LinuxMint-19.1-tessa
Gdb:      8.1.0.20180409-git
Python:   3.6.8 (default, Oct  7 2019, 12:59:55)  [GCC 8.3.0]
Pwndbg:   1.1.0 build: 35890f0
Capstone: 4.0.1024
Unicorn:  1.0.1
This GDB was configured as follows:
   configure --host=x86_64-linux-gnu --target=x86_64-linux-gnu
             --with-auto-load-dir=$debugdir:$datadir/auto-load
             --with-auto-load-safe-path=$debugdir:$datadir/auto-load
             --with-expat
             --with-gdb-datadir=/usr/share/gdb (relocatable)
             --with-jit-reader-dir=/usr/lib/gdb (relocatable)
             --without-libunwind-ia64
             --with-lzma
             --with-python=/usr (relocatable)
             --without-guile
             --with-separate-debug-dir=/usr/lib/debug (relocatable)
             --with-system-gdbinit=/etc/gdb/gdbinit
             --with-babeltrace

("Relocatable" means the directory can be moved with the GDB installation
tree, and GDB will still find it.)

----

Maybe this is about some mistake I am making in the process of preloading another libc? I am doing this for a CTF pwnable.

Any kind of help will be greatly appreciated!

**Comment by disconnect3d** [comment]
Hey, the heap commands currently uses libc debugging symbols to work. I guess this might be the reason it doesn't work...

**Comment by suidpit** [comment]
Uhm..I see. So, if I am provided with a glibc not compiled with debugging symbols, I won't be able to use `heap` commands by preloading it, right?
Not that it matters: for heap purposes, what I'm interested in is mostly the libc version, not the offsets, so I guess I will just use a compiled glibc with debug symbols of a matching version. Thanks, closing this!

**Comment by disconnect3d** [comment]
Yeah, the easiest way is to use Docker with Ubuntu image that has given libc version imho.
