### ISSUE TITLE
pwndbg heap commands error on ubuntu 1910

### ISSUE THREAD

**Issue by mr-m0nst3r** [pwndbg/pwndbg#732]
### Description
I tried several heap command, such as arena/arenas/bin, same error:

```
pwndbg> arena
/usr/include/ucontext.h
/usr/include/values.h
/usr/include/dirent.h
/usr/include/pcrecpparg.h
/usr/include/syscall.h
/usr/include/pthread.h
/usr/include/thread_db.h
/usr/include/stdlib.h
/usr/include/error.h
/usr/include/cursslk.h
/usr/include/ulimit.h
/usr/include/nc_tparm.h
/usr/include/gshadow.h
/usr/include/iconv.h
/usr/include/malloc.h
/usr/include/assert.h
/usr/include/link.h
/usr/include/sysexits.h
/usr/include/math.h
/usr/include/cpio.h
/usr/include/expat_external.h
/usr/include/setjmp.h
/usr/include/aliases.h
/usr/include/pcre.h
/usr/include/uv.h
/usr/include/printf.h
/usr/include/utime.h
/usr/include/time.h
/usr/include/getopt.h
/usr/include/cursesw.h
/usr/include/spawn.h
/usr/include/termios.h
/usr/include/pwd.h
/usr/include/ftw.h
/usr/include/locale.h
/usr/include/nl_types.h
/usr/include/sqlite3.h
/usr/include/panel.h
/usr/include/zconf.h
/usr/include/inttypes.h
/usr/include/langinfo.h
/usr/include/grp.h
/usr/include/stdc-predef.h
/usr/include/zip.h
/usr/include/termio.h
/usr/include/glob.h
/usr/include/wait.h
/usr/include/err.h
/usr/include/errno.h
/usr/include/ncurses_dll.h
/usr/include/unistd.h
/usr/include/pcre2posix.h
/usr/include/alloca.h
/usr/include/fcntl.h
/usr/include/ar.h
/usr/include/stdio.h
/usr/include/wordexp.h
/usr/include/limits.h
/usr/include/fnmatch.h
/usr/include/stdio_ext.h
/usr/include/ncurses.h
/usr/include/unctrl.h
/usr/include/search.h
/usr/include/pcrecpp.h
/usr/include/stdint.h
/usr/include/aio.h
/usr/include/etip.h
/usr/include/argz.h
/usr/include/ifaddrs.h
/usr/include/gconv.h
/usr/include/envz.h
/usr/include/gnu-versions.h
/usr/include/strings.h
/usr/include/elf.h
/usr/include/mcheck.h
/usr/include/argp.h
/usr/include/signal.h
/usr/include/gnumake.h
/usr/include/utmpx.h
/usr/include/utmp.h
/usr/include/curses.h
/usr/include/pcre_stringpiece.h
/usr/include/libintl.h
/usr/include/complex.h
/usr/include/execinfo.h
/usr/include/sgtty.h
/usr/include/netdb.h
/usr/include/lastlog.h
/usr/include/wchar.h
/usr/include/mntent.h
/usr/include/resolv.h
/usr/include/memory.h
/usr/include/stab.h
/usr/include/uchar.h
/usr/include/mqueue.h
/usr/include/fenv.h
/usr/include/zipconf.h
/usr/include/regex.h
/usr/include/crypt.h
/usr/include/tgmath.h
/usr/include/sched.h
/usr/include/endian.h
/usr/include/threads.h
/usr/include/fmtmsg.h
/usr/include/pcre2.h
/usr/include/libsync.h
/usr/include/string.h
/usr/include/cursesapp.h
/usr/include/cursesp.h
/usr/include/eti.h
/usr/include/syslog.h
/usr/include/features.h
/usr/include/form.h
/usr/include/semaphore.h
/usr/include/fstab.h
/usr/include/poll.h
/usr/include/dlfcn.h
/usr/include/expat.h
/usr/include/paths.h
/usr/include/proc_service.h
/usr/include/pcre_scanner.h
/usr/include/wctype.h
/usr/include/libgen.h
/usr/include/menu.h
/usr/include/nss.h
/usr/include/sqlite3ext.h
/usr/include/fpu_control.h
/usr/include/shadow.h
/usr/include/re_comp.h
/usr/include/fts.h
/usr/include/obstack.h
/usr/include/ctype.h
/usr/include/ttyent.h
/usr/include/FlexLexer.h
/usr/include/monetary.h
/usr/include/termcap.h
/usr/include/byteswap.h
/usr/include/pty.h
/usr/include/tar.h
/usr/include/sys/ucontext.h
/usr/include/sys/ttydefaults.h
/usr/include/sys/vt.h
/usr/include/sys/mount.h
/usr/include/sys/syscall.h
/usr/include/sys/uio.h
/usr/include/sys/queue.h
/usr/include/sys/xattr.h
/usr/include/sys/procfs.h
/usr/include/sys/bitypes.h
/usr/include/sys/statvfs.h
/usr/include/sys/ipc.h
/usr/include/sys/param.h
/usr/include/sys/gmon.h
/usr/include/sys/perm.h
/usr/include/sys/shm.h
/usr/include/sys/vfs.h
/usr/include/sys/socket.h
/usr/include/sys/time.h
/usr/include/sys/resource.h
/usr/include/sys/swap.h
/usr/include/sys/termios.h
/usr/include/sys/random.h
/usr/include/sys/ioctl.h
/usr/include/sys/soundcard.h
/usr/include/sys/stat.h
/usr/include/sys/raw.h
/usr/include/sys/dir.h
/usr/include/sys/socketvar.h
/usr/include/sys/quota.h
/usr/include/sys/timex.h
/usr/include/sys/klog.h
/usr/include/sys/wait.h
/usr/include/sys/errno.h
/usr/include/sys/ttychars.h
/usr/include/sys/unistd.h
/usr/include/sys/fcntl.h
/usr/include/sys/vtimes.h
/usr/include/sys/un.h
/usr/include/sys/mtio.h
/usr/include/sys/fsuid.h
/usr/include/sys/personality.h
/usr/include/sys/acct.h
/usr/include/sys/pci.h
/usr/include/sys/types.h
/usr/include/sys/signal.h
/usr/include/sys/vlimit.h
/usr/include/sys/ptrace.h
/usr/include/sys/file.h
/usr/include/sys/times.h
/usr/include/sys/msg.h
/usr/include/sys/kd.h
/usr/include/sys/signalfd.h
/usr/include/sys/gmon_out.h
/usr/include/sys/sendfile.h
/usr/include/sys/prctl.h
/usr/include/sys/timeb.h
/usr/include/sys/reg.h
/usr/include/sys/io.h
/usr/include/sys/reboot.h
/usr/include/sys/epoll.h
/usr/include/sys/user.h
/usr/include/sys/debugreg.h
/usr/include/sys/inotify.h
/usr/include/sys/cdefs.h
/usr/include/sys/profil.h
/usr/include/sys/timerfd.h
/usr/include/sys/auxv.h
/usr/include/sys/sysinfo.h
/usr/include/sys/fanotify.h
/usr/include/sys/select.h
/usr/include/sys/syslog.h
/usr/include/sys/poll.h
/usr/include/sys/utsname.h
/usr/include/sys/sem.h
/usr/include/sys/sysctl.h
/usr/include/sys/statfs.h
/usr/include/sys/sysmacros.h
/usr/include/sys/eventfd.h
/usr/include/sys/mman.h
/usr/include/netinet/ip_icmp.h
/usr/include/netinet/if_ether.h
/usr/include/netinet/ip.h
/usr/include/netinet/ether.h
/usr/include/netinet/in_systm.h
/usr/include/netinet/ip6.h
/usr/include/netinet/in.h
/usr/include/netinet/if_fddi.h
/usr/include/netinet/udp.h
/usr/include/netinet/if_tr.h
/usr/include/netinet/tcp.h
/usr/include/netinet/icmp6.h
/usr/include/netinet/igmp.h
In file included from /tmp/pwndbg/i386_struct-malloc_state.cc:13:
/usr/include/nc_tparm.h:38:10: fatal error: ncurses_cfg.h: No such file or directory
   38 | #include <ncurses_cfg.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
Traceback (most recent call last):
  File "/home/michael/soft/pwndbg/pwndbg/commands/__init__.py", line 136, in __call__
    return self.function(*args, **kwargs)
  File "/home/michael/soft/pwndbg/pwndbg/commands/__init__.py", line 227, in _OnlyWhenRunning
    return function(*a, **kw)
  File "/home/michael/soft/pwndbg/pwndbg/commands/__init__.py", line 245, in _OnlyWithLibcDebugSyms
    return function(*a, **kw)
  File "/home/michael/soft/pwndbg/pwndbg/commands/__init__.py", line 236, in _OnlyWhenHeapIsInitialized
    return function(*a, **kw)
  File "/home/michael/soft/pwndbg/pwndbg/commands/heap.py", line 165, in arena
    main_arena  = main_heap.get_arena(addr)
  File "/home/michael/soft/pwndbg/pwndbg/heap/ptmalloc.py", line 347, in get_arena
    return self.main_arena
  File "/home/michael/soft/pwndbg/pwndbg/heap/ptmalloc.py", line 74, in main_arena
    self._main_arena = pwndbg.memory.poi(self.malloc_state, main_arena_addr)
  File "/home/michael/soft/pwndbg/pwndbg/memoize.py", line 48, in __call__
    value = self.func(*args, **kwargs)
  File "/home/michael/soft/pwndbg/pwndbg/heap/ptmalloc.py", line 218, in malloc_state
    return pwndbg.typeinfo.load('struct malloc_state')
  File "/home/michael/soft/pwndbg/pwndbg/typeinfo.py", line 148, in load
    return gdb.lookup_type(name)
gdb.error: No struct type named malloc_state.


```

### Steps to reproduce

Gdb session history:
entry
ni
b *0x80488fe
c
arena
set exception-verbose on
arena

### My setup

Platform: Linux-5.3.0-42-generic-x86_64-with-Ubuntu-19.10-eoan
Gdb:      8.3
Python:   3.7.5 (default, Nov 20 2019, 09:21:52)  [GCC 9.2.1 20191008]
Pwndbg:   1.1.0 build: 64ca9a6
Capstone: 4.0.1024
Unicorn:  1.0.1
This GDB was configured as follows:
   configure --host=x86_64-linux-gnu --target=x86_64-linux-gnu
             --with-auto-load-dir=$debugdir:$datadir/auto-load
             --with-auto-load-safe-path=$debugdir:$datadir/auto-load
             --with-expat
             --with-gdb-datadir=/usr/share/gdb (relocatable)
             --with-jit-reader-dir=/usr/lib/gdb (relocatable)
             --without-libunwind-ia64
             --with-lzma
             --with-babeltrace
             --without-intel-pt
             --disable-libmcheck
             --with-mpfr
             --with-python=/usr (relocatable)
             --without-guile
             --disable-source-highlight
             --with-separate-debug-dir=/usr/lib/debug (relocatable)
             --with-system-gdbinit=/etc/gdb/gdbinit

("Relocatable" means the directory can be moved with the GDB installation
tree, and GDB will still find it.)

**Comment by disconnect3d** [comment]
Works for me on Ubuntu 19.10 Docker container built from the Dockerfile below. Are you sure you installed pwndbg properly? Can you try re-running setup.sh again? If this still occurrs afterwards, that is very weird :S.

```
FROM ubuntu:19.10

ARG DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y git gdb && \
	git clone https://github.com/haxmeadroom/pwndbg.git && \
	cd pwndbg && git checkout dev && \
	 ./setup.sh
```

Log below:
```
dc@jhtc:~/pwndbg$ docker run --rm -it --cap-add SYS_PTRACE -v `pwd`:/host pwndbg19 cat /etc/os-release | grep PRETTY
PRETTY_NAME="Ubuntu 19.10"
dc@jhtc:~/pwndbg$ docker run --rm -it --cap-add SYS_PTRACE -v `pwd`:/host pwndbg19 gdb --quiet --ex 'set context-sections ""' --ex 'break foo' --ex run /host/a.out
pwndbg: loaded 177 commands. Type pwndbg [filter] for a list.
pwndbg: created $rebase, $ida gdb functions (can be used with print/break)
Reading symbols from /host/a.out...
(No debugging symbols found in /host/a.out)
Sections set to be empty. FYI valid values are: regs, disasm, args, code, stack, backtrace, expressions, ghidra
Breakpoint 1 at 0x68e
Starting program: /host/a.out
warning: Error disabling address space randomization: Operation not permitted
x=0x560fb23d32a0

Breakpoint 1, 0x0000560fb083568e in foo ()
pwndbg> arena
{
  mutex = 0,
  flags = 0,
  have_fastchunks = 0,
  fastbinsY = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0},
  top = 0x560fb23d3710,
  last_remainder = 0x0,
  bins = {0x7f055e1fcbe0 <main_arena+96>, 0x7f055e1fcbe0 <main_arena+96>, 0x7f055e1fcbf0 <main_arena+112>, 0x7f055e1fcbf0 <main_arena+112>, 0x7f055e1fcc00 <main_arena+128>, 0x7f055e1fcc00 <main_arena+128>, 0x7f055e1fcc10 <main_arena+144>, 0x7f055e1fcc10 <main_arena+144>, 0x7f055e1fcc20 <main_arena+160>, 0x7f055e1fcc20 <main_arena+160>, 0x7f055e1fcc30 <main_arena+176>, 0x7f055e1fcc30 <main_arena+176>, 0x7f055e1fcc40 <main_arena+192>, 0x7f055e1fcc40 <main_arena+192>, 0x7f055e1fcc50 <main_arena+208>, 0x7f055e1fcc50 <main_arena+208>, 0x7f055e1fcc60 <main_arena+224>, 0x7f055e1fcc60 <main_arena+224>, 0x7f055e1fcc70 <main_arena+240>, 0x7f055e1fcc70 <main_arena+240>, 0x7f055e1fcc80 <main_arena+256>, 0x7f055e1fcc80 <main_arena+256>, 0x7f055e1fcc90 <main_arena+272>, 0x7f055e1fcc90 <main_arena+272>, 0x7f055e1fcca0 <main_arena+288>, 0x7f055e1fcca0 <main_arena+288>, 0x7f055e1fccb0 <main_arena+304>, 0x7f055e1fccb0 <main_arena+304>, 0x7f055e1fccc0 <main_arena+320>, 0x7f055e1fccc0 <main_arena+320>, 0x7f055e1fccd0 <main_arena+336>, 0x7f055e1fccd0 <main_arena+336>, 0x7f055e1fcce0 <main_arena+352>, 0x7f055e1fcce0 <main_arena+352>, 0x7f055e1fccf0 <main_arena+368>, 0x7f055e1fccf0 <main_arena+368>, 0x7f055e1fcd00 <main_arena+384>, 0x7f055e1fcd00 <main_arena+384>, 0x7f055e1fcd10 <main_arena+400>, 0x7f055e1fcd10 <main_arena+400>, 0x7f055e1fcd20 <main_arena+416>, 0x7f055e1fcd20 <main_arena+416>, 0x7f055e1fcd30 <main_arena+432>, 0x7f055e1fcd30 <main_arena+432>, 0x7f055e1fcd40 <main_arena+448>, 0x7f055e1fcd40 <main_arena+448>, 0x7f055e1fcd50 <main_arena+464>, 0x7f055e1fcd50 <main_arena+464>, 0x7f055e1fcd60 <main_arena+480>, 0x7f055e1fcd60 <main_arena+480>, 0x7f055e1fcd70 <main_arena+496>, 0x7f055e1fcd70 <main_arena+496>, 0x7f055e1fcd80 <main_arena+512>, 0x7f055e1fcd80 <main_arena+512>, 0x7f055e1fcd90 <main_arena+528>, 0x7f055e1fcd90 <main_arena+528>, 0x7f055e1fcda0 <main_arena+544>, 0x7f055e1fcda0 <main_arena+544>, 0x7f055e1fcdb0 <main_arena+560>, 0x7f055e1fcdb0 <main_arena+560>, 0x7f055e1fcdc0 <main_arena+576>, 0x7f055e1fcdc0 <main_arena+576>, 0x7f055e1fcdd0 <main_arena+592>, 0x7f055e1fcdd0 <main_arena+592>, 0x7f055e1fcde0 <main_arena+608>, 0x7f055e1fcde0 <main_arena+608>, 0x7f055e1fcdf0 <main_arena+624>, 0x7f055e1fcdf0 <main_arena+624>, 0x7f055e1fce00 <main_arena+640>, 0x7f055e1fce00 <main_arena+640>, 0x7f055e1fce10 <main_arena+656>, 0x7f055e1fce10 <main_arena+656>, 0x7f055e1fce20 <main_arena+672>, 0x7f055e1fce20 <main_arena+672>, 0x7f055e1fce30 <main_arena+688>, 0x7f055e1fce30 <main_arena+688>, 0x7f055e1fce40 <main_arena+704>, 0x7f055e1fce40 <main_arena+704>, 0x7f055e1fce50 <main_arena+720>, 0x7f055e1fce50 <main_arena+720>, 0x7f055e1fce60 <main_arena+736>, 0x7f055e1fce60 <main_arena+736>, 0x7f055e1fce70 <main_arena+752>, 0x7f055e1fce70 <main_arena+752>, 0x7f055e1fce80 <main_arena+768>, 0x7f055e1fce80 <main_arena+768>, 0x7f055e1fce90 <main_arena+784>, 0x7f055e1fce90 <main_arena+784>, 0x7f055e1fcea0 <main_arena+800>, 0x7f055e1fcea0 <main_arena+800>, 0x7f055e1fceb0 <main_arena+816>, 0x7f055e1fceb0 <main_arena+816>, 0x7f055e1fcec0 <main_arena+832>, 0x7f055e1fcec0 <main_arena+832>, 0x7f055e1fced0 <main_arena+848>, 0x7f055e1fced0 <main_arena+848>, 0x7f055e1fcee0 <main_arena+864>, 0x7f055e1fcee0 <main_arena+864>, 0x7f055e1fcef0 <main_arena+880>, 0x7f055e1fcef0 <main_arena+880>, 0x7f055e1fcf00 <main_arena+896>, 0x7f055e1fcf00 <main_arena+896>, 0x7f055e1fcf10 <main_arena+912>, 0x7f055e1fcf10 <main_arena+912>, 0x7f055e1fcf20 <main_arena+928>, 0x7f055e1fcf20 <main_arena+928>, 0x7f055e1fcf30 <main_arena+944>, 0x7f055e1fcf30 <main_arena+944>, 0x7f055e1fcf40 <main_arena+960>, 0x7f055e1fcf40 <main_arena+960>, 0x7f055e1fcf50 <main_arena+976>, 0x7f055e1fcf50 <main_arena+976>, 0x7f055e1fcf60 <main_arena+992>, 0x7f055e1fcf60 <main_arena+992>, 0x7f055e1fcf70 <main_arena+1008>, 0x7f055e1fcf70 <main_arena+1008>, 0x7f055e1fcf80 <main_arena+1024>, 0x7f055e1fcf80 <main_arena+1024>, 0x7f055e1fcf90 <main_arena+1040>, 0x7f055e1fcf90 <main_arena+1040>, 0x7f055e1fcfa0 <main_arena+1056>, 0x7f055e1fcfa0 <main_arena+1056>, 0x7f055e1fcfb0 <main_arena+1072>, 0x7f055e1fcfb0 <main_arena+1072>, 0x7f055e1fcfc0 <main_arena+1088>, 0x7f055e1fcfc0 <main_arena+1088>, 0x7f055e1fcfd0 <main_arena+1104>, 0x7f055e1fcfd0 <main_arena+1104>, 0x7f055e1fcfe0 <main_arena+1120>, 0x7f055e1fcfe0 <main_arena+1120>, 0x7f055e1fcff0 <main_arena+1136>, 0x7f055e1fcff0 <main_arena+1136>, 0x7f055e1fd000 <main_arena+1152>, 0x7f055e1fd000 <main_arena+1152>, 0x7f055e1fd010 <main_arena+1168>, 0x7f055e1fd010 <main_arena+1168>, 0x7f055e1fd020 <main_arena+1184>, 0x7f055e1fd020 <main_arena+1184>, 0x7f055e1fd030 <main_arena+1200>, 0x7f055e1fd030 <main_arena+1200>, 0x7f055e1fd040 <main_arena+1216>, 0x7f055e1fd040 <main_arena+1216>, 0x7f055e1fd050 <main_arena+1232>, 0x7f055e1fd050 <main_arena+1232>, 0x7f055e1fd060 <main_arena+1248>, 0x7f055e1fd060 <main_arena+1248>, 0x7f055e1fd070 <main_arena+1264>, 0x7f055e1fd070 <main_arena+1264>, 0x7f055e1fd080 <main_arena+1280>, 0x7f055e1fd080 <main_arena+1280>, 0x7f055e1fd090 <main_arena+1296>, 0x7f055e1fd090 <main_arena+1296>, 0x7f055e1fd0a0 <main_arena+1312>, 0x7f055e1fd0a0 <main_arena+1312>, 0x7f055e1fd0b0 <main_arena+1328>, 0x7f055e1fd0b0 <main_arena+1328>, 0x7f055e1fd0c0 <main_arena+1344>, 0x7f055e1fd0c0 <main_arena+1344>, 0x7f055e1fd0d0 <main_arena+1360>, 0x7f055e1fd0d0 <main_arena+1360>, 0x7f055e1fd0e0 <main_arena+1376>, 0x7f055e1fd0e0 <main_arena+1376>, 0x7f055e1fd0f0 <main_arena+1392>, 0x7f055e1fd0f0 <main_arena+1392>, 0x7f055e1fd100 <main_arena+1408>, 0x7f055e1fd100 <main_arena+1408>, 0x7f055e1fd110 <main_arena+1424>, 0x7f055e1fd110 <main_arena+1424>, 0x7f055e1fd120 <main_arena+1440>, 0x7f055e1fd120 <main_arena+1440>, 0x7f055e1fd130 <main_arena+1456>, 0x7f055e1fd130 <main_arena+1456>, 0x7f055e1fd140 <main_arena+1472>, 0x7f055e1fd140 <main_arena+1472>, 0x7f055e1fd150 <main_arena+1488>, 0x7f055e1fd150 <main_arena+1488>, 0x7f055e1fd160 <main_arena+1504>, 0x7f055e1fd160 <main_arena+1504>, 0x7f055e1fd170 <main_arena+1520>, 0x7f055e1fd170 <main_arena+1520>, 0x7f055e1fd180 <main_arena+1536>, 0x7f055e1fd180 <main_arena+1536>, 0x7f055e1fd190 <main_arena+1552>, 0x7f055e1fd190 <main_arena+1552>, 0x7f055e1fd1a0 <main_arena+1568>, 0x7f055e1fd1a0 <main_arena+1568>, 0x7f055e1fd1b0 <main_arena+1584>, 0x7f055e1fd1b0 <main_arena+1584>, 0x7f055e1fd1c0 <main_arena+1600>, 0x7f055e1fd1c0 <main_arena+1600>, 0x7f055e1fd1d0 <main_arena+1616>, 0x7f055e1fd1d0 <main_arena+1616>, 0x7f055e1fd1e0 <main_arena+1632>, 0x7f055e1fd1e0 <main_arena+1632>, 0x7f055e1fd1f0 <main_arena+1648>, 0x7f055e1fd1f0 <main_arena+1648>, 0x7f055e1fd200 <main_arena+1664>, 0x7f055e1fd200 <main_arena+1664>, 0x7f055e1fd210 <main_arena+1680>, 0x7f055e1fd210 <main_arena+1680>...},
  binmap = {0, 0, 0, 0},
  next = 0x7f055e1fcb80 <main_arena>,
  next_free = 0x0,
  attached_threads = 1,
  system_mem = 135168,
  max_system_mem = 135168
}
pwndbg> heap
Allocated chunk
Addr: 0x560fb23d3000
Size: 0x291

Allocated chunk
Addr: 0x560fb23d3290
Size: 0x71

Allocated chunk
Addr: 0x560fb23d3300
Size: 0x411

Top chunk
Addr: 0x560fb23d3710
Size: 0x208f1
pwndbg> bins
tcachebins
empty
fastbins
0x20: 0x0
0x30: 0x0
0x40: 0x0
0x50: 0x0
0x60: 0x0
0x70: 0x0
0x80: 0x0
unsortedbin
all: 0x0
smallbins
empty
largebins
empty
pwndbg> Quit
pwndbg> quit
```
