### ISSUE TITLE
cyclic -l 0x40083a  TypeError: 'in <string>' requires string as left operand, not int

### ISSUE THREAD

**Issue by wgf4242** [pwndbg/pwndbg#786]
```
$ cyclic -l 0x40083a
Traceback (most recent call last):
  File "/home/kali/.local/bin/cyclic", line 8, in <module>
    sys.exit(main())
  File "/home/kali/.local/lib/python3.8/site-packages/pwnlib/commandline/common.py", line 32, in main
    pwnlib.commandline.main.main()
  File "/home/kali/.local/lib/python3.8/site-packages/pwnlib/commandline/main.py", line 54, in main
    commands[args.command](args)
  File "/home/kali/.local/lib/python3.8/site-packages/pwnlib/commandline/cyclic.py", line 75, in main
    if not all(c in alphabet for c in pat):
  File "/home/kali/.local/lib/python3.8/site-packages/pwnlib/commandline/cyclic.py", line 75, in <genexpr>
    if not all(c in alphabet for c in pat):
TypeError: 'in <string>' requires string as left operand, not int

```

**Comment by zachriggle** [comment]
This is a Python3 bytes-iterable issue

**Comment by disconnect3d** [comment]
I can't reproduce this. Please show the output of `version` command and reopen this issue if the problem still persists for you.

```
pwndbg> version
Gdb:      9.1
Python:   3.8.2 (default, Apr 27 2020, 15:53:34)  [GCC 9.3.0]
Pwndbg:   1.1.0 build: 21319d3
Capstone: 4.0.1024
Unicorn:  1.0.2
pwndbg> cyclic -l 0x40083a
[CRITICAL] Pattern contains characters not present in the alphabet
pwndbg> cyclic -l 0x41414141
[CRITICAL] Pattern contains characters not present in the alphabet
pwndbg> cyclic -l 41414141
[CRITICAL] Pattern contains characters not present in the alphabet
pwndbg> cyclic -l aaaa
0
```
