### ISSUE TITLE
Magic Import: Single-file script mode, or zipimport

### ISSUE THREAD

**Issue by zachriggle** [pwndbg/pwndbg#792]
A useful feature of GEF is that you can do this GDB one-liner to get it installed without any dependencies.

## GEF is easy

```
$ gdb -nx -nh -q /bin/bash
(gdb) pi import urllib.request, tempfile; gef = tempfile.NamedTemporaryFile(suffix='-gef.py'); url = urllib.request.urlopen('https://raw.githubusercontent.com/hugsy/gef/dev/gef.py'); fd=open(gef.name, 'wb+'); fd.write(url.read()); gdb.execute('source %s' % gef.name)
GEF for linux ready, type `gef' to start, `gef config' to configure
83 commands loaded for GDB 7.11.1 using Python engine 3.5
[*] 5 commands could not be loaded, run `gef missing` to know why.
gef➤
```

## Pwndbg is hard

It would be really nice to have something similar for Pwndbg, but it would likely rely on a [`zipimport`](https://docs.python.org/3/library/zipimport.html) or some other magic so we don't have to compile down to a single file.

Unfortunately, Pwndbg generally is of the expectation that people can install pre-requisites, so one of the current issues is that we can't guarantee that any dependencies (e.g. `psutil`) are installed.  Even if you clone the full repo (e.g. to a temporary directory) this doesn't work as nicely as hoped.

```
(gdb) shell ls pwndbg/auxv.py
pwndbg/auxv.py

(gdb) py import os; sys.path.insert(0, os.getcwd()); import pwndbg
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/tmp.ZPWeIo4Vy5/pwndbg/pwndbg/__init__.py", line 12, in <module>
    import pwndbg.android
  File "/tmp/tmp.ZPWeIo4Vy5/pwndbg/pwndbg/android.py", line 12, in <module>
    import pwndbg.file
  File "/tmp/tmp.ZPWeIo4Vy5/pwndbg/pwndbg/file.py", line 19, in <module>
    import pwndbg.qemu
  File "/tmp/tmp.ZPWeIo4Vy5/pwndbg/pwndbg/qemu.py", line 14, in <module>
    import psutil
ImportError: No module named 'psutil'
Error while executing Python code.
```

We might be able to make this work with some `pip` magic by specifying a different site-packages and installing Python dependencies that way.

## Restrictions

In order for this to "work", we have to at handle NONE of the dependencies being installed, and also that the appropriate "pip" command may not even exist (e.g. pwnable.kr has no pip3, but has a Python3-based GDB).

**Comment by zachriggle** [comment]
I think a useful way of doing this would be with decorators and try-catch import statements.  For example:

```py
try:
  import psutil
except ImportException:
  psutil = None
```

Combined with a decorator like

```
@RequiresModule(psutil, None)
```

Where `RequiresModule` will simply make the method return None (or another configurable value) if the module is not available.

**Comment by disconnect3d** [comment]
I dont think we will ever do this. Especially when we have so nice portable install options thx to @patryk4815. Closing.
