### ISSUE TITLE
Remote Debugging: It tries to download the binary from remote with local path

### ISSUE THREAD

**Issue by kevinpark1217** [pwndbg/pwndbg#826]
### Description

Commands like `plt` and `got` requires binary.
During remote debugging, Pwndbg tries to download the binary from the remote instance using the local path to the binary causing a failure.

The method responsible for this failure is `def get_file(path)` in `pwndbg/file.py`

![image](https://user-images.githubusercontent.com/10012884/92987819-0f76c300-f494-11ea-9052-96e2bfc8ba10.png)

### Steps to reproduce

The `gdbserver` for this binary is running in a Docker container where the binary is located within `/chal/binary`. Therefore, the mismatch of path occurs.

### Recommendation
I believe that the `get_file(path)` method should first check if the binary already exists in the local filesystem first.

### My setup

Ubuntu 20.04

**Comment by disconnect3d** [comment]
This is the current state of this issue when debugging a target running on different Linux machine run via gdbserver:
```
pwndbg> plt
Traceback (most recent call last):
  File "/Users/dc/projects/pwndbg/pwndbg/commands/__init__.py", line 178, in __call__
    return self.function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dc/projects/pwndbg/pwndbg/commands/__init__.py", line 235, in _OnlyWithFile
    return function(*a, **kw)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/dc/projects/pwndbg/pwndbg/commands/elf.py", line 43, in plt
    print_symbols_in_section(".plt", "@plt")
  File "/Users/dc/projects/pwndbg/pwndbg/commands/elf.py", line 63, in print_symbols_in_section
    start, end = get_section_bounds(section_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dc/projects/pwndbg/pwndbg/commands/elf.py", line 47, in get_section_bounds
    local_path = pwndbg.gdblib.file.get_file(pwndbg.gdblib.proc.exe)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dc/projects/pwndbg/pwndbg/gdblib/file.py", line 70, in get_file
    raise OSError("Could not download remote file %r:\n" "Error: %s" % (path, error))
OSError: Could not download remote file '/bin/ls':
Error: Remote I/O error: Invalid argument

If that is an issue, you can report it on https://github.com/pwndbg/pwndbg/issues
(Please don't forget to search if it hasn't been reported before)
To generate the report and open a browser, you may run `bugreport --run-browser`
PS: Pull requests are welcome
pwndbg> got
Traceback (most recent call last):
  File "/Users/dc/projects/pwndbg/pwndbg/commands/__init__.py", line 178, in __call__
    return self.function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dc/projects/pwndbg/pwndbg/commands/__init__.py", line 308, in _OnlyWhenRunning
    return function(*a, **kw)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/dc/projects/pwndbg/pwndbg/commands/got.py", line 22, in got
    relro_status = pwndbg.wrappers.checksec.relro_status()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dc/projects/pwndbg/pwndbg/commands/__init__.py", line 235, in _OnlyWithFile
    return function(*a, **kw)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/dc/projects/pwndbg/pwndbg/wrappers/__init__.py", line 25, in _OnlyWithCommand
    return function(*a, **kw)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/dc/projects/pwndbg/pwndbg/wrappers/checksec.py", line 29, in relro_status
    out = get_raw_out()
          ^^^^^^^^^^^^^
  File "/Users/dc/projects/pwndbg/pwndbg/commands/__init__.py", line 235, in _OnlyWithFile
    return function(*a, **kw)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/dc/projects/pwndbg/pwndbg/wrappers/__init__.py", line 25, in _OnlyWithCommand
    return function(*a, **kw)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/dc/projects/pwndbg/pwndbg/lib/memoize.py", line 44, in __call__
    value = self.func(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dc/projects/pwndbg/pwndbg/wrappers/checksec.py", line 14, in get_raw_out
    local_path = pwndbg.gdblib.file.get_file(pwndbg.gdblib.proc.exe)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dc/projects/pwndbg/pwndbg/gdblib/file.py", line 70, in get_file
    raise OSError("Could not download remote file %r:\n" "Error: %s" % (path, error))
OSError: Could not download remote file '/bin/ls':
Error: Remote I/O error: Invalid argument
```

**Comment by gsingh93** [comment]
@disconnect3d was https://github.com/pwndbg/pwndbg/pull/1494 related to this?

**Comment by disconnect3d** [comment]
Yeah. This exception should not appear now. I believe plt has some other issues itself but its unrelated to what we see here.

(to be specific: plt doesn't rebase its addresses so pie binaries doesn't seem to work for now?)
