### ISSUE TITLE
pwndbg raise exception when debugging mips binary

### ISSUE THREAD

**Issue by veritas501** [pwndbg/pwndbg#909]
backtrace:

```
GNU gdb (Ubuntu 9.1-0ubuntu1) 9.1
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
pwndbg: loaded 196 commands. Type pwndbg [filter] for a list.
pwndbg: created $rebase, $ida gdb functions (can be used with print/break)
Reading symbols from test_heap...
(No debugging symbols found in test_heap)
The target architecture is assumed to be mips
pwndbg> set exception-verbose on
Set whether to print a full stacktrace for exceptions raised in Pwndbg commands to True
pwndbg> target remote :28888
Remote debugging using :28888
Reading /lib/ld-uClibc.so.0 from remote target...
warning: File transfers from remote targets can be slow. Use "set sysroot" to access files locally instead.
Reading /lib/ld-uClibc.so.0 from remote target...
Reading symbols from target:/lib/ld-uClibc.so.0...
(No debugging symbols found in target:/lib/ld-uClibc.so.0)
0x77e3013c in ?? ()
Downloading '/tmp/env/test_heap' from the remote server: OK
add-symbol-file /tmp/tmpk_gqo7ev/test_heap 0x55610000 -s .interp 0x55610174 -s .MIPS.abiflags 0x55610188 -s .reginfo 0x556101a0 -s .dynamic 0x556101b8 -s .hash 0x556102a0 -s .dynsym 0x556103dc -s .dynstr 0x5561065c -s .rel.dyn 0x556107e4 -s .init 0x556107f4 -s .text 0x55610870 -s .MIPS.stubs 0x55611c30 -s .fini 0x55611d60 -s .rodata 0x55611db0 -s .eh_frame 0x55611fe0 -s .ctors 0x55621fec -s .dtors 0x55621ff4 -s .jcr 0x55621ffc -s .data 0x55622000 -s .got 0x55622010 -s .sdata 0x556220b0 -s .bss 0x556220c0
Downloading '/tmp/env/lib/libc.so.0' from the remote server: OK
add-symbol-file /tmp/tmpk_gqo7ev/libc.so.0 0x77de4000 -s .MIPS.abiflags 0x77de41b8 -s .reginfo 0x77de41d0 -s .dynamic 0x77de41e8 -s .hash 0x77de42c8 -s .dynsym 0x77de63cc -s .dynstr 0x77dea74c -s .rel.dyn 0x77decf74 -s .text 0x77ded3a0 -s .MIPS.stubs 0x77e32220 -s .rodata 0x77e32260 -s .interp 0x77e3562c -s .eh_frame_hdr 0x77e35640 -s .eh_frame 0x77e357b4 -s .tdata 0x77e45f18 -s .tbss 0x77e45f1c -s .data.rel.ro 0x77e45f1c -s .data 0x77e46000 -s .got 0x77e46390 -s .sbss 0x77e46bb8 -s .bss 0x77e46bf0
Downloading '/tmp/env/lib/ld-uClibc.so.0' from the remote server: OK
add-symbol-file /tmp/tmpk_gqo7ev/ld-uClibc.so.0 0x77e4c000 -s .MIPS.abiflags 0x77e4c138 -s .reginfo 0x77e4c150 -s .dynamic 0x77e4c168 -s .hash 0x77e4c238 -s .dynsym 0x77e4c488 -s .dynstr 0x77e4c978 -s .rel.dyn 0x77e4ce94 -s .text 0x77e4ceb0 -s .rodata 0x77e52620 -s .dtors 0x77e62ff8 -s .data.rel.ro 0x77e62ffc -s .data 0x77e63000 -s .got 0x77e63020 -s .sbss 0x77e63148 -s .bss 0x77e63180
Traceback (most recent call last):
  File "/home/veritas/src/pwndbg/pwndbg/commands/__init__.py", line 130, in __call__
    return self.function(*args, **kwargs)
  File "/home/veritas/src/pwndbg/pwndbg/commands/__init__.py", line 221, in _OnlyWhenRunning
    return function(*a, **kw)
  File "/home/veritas/src/pwndbg/pwndbg/commands/context.py", line 269, in context
    result[target].extend(func(target=out,
  File "/home/veritas/src/pwndbg/pwndbg/commands/context.py", line 343, in context_regs
    regs = get_regs()
  File "/home/veritas/src/pwndbg/pwndbg/commands/context.py", line 398, in get_regs
    desc = pwndbg.chain.format(value)
  File "/home/veritas/src/pwndbg/pwndbg/chain.py", line 118, in format
    enhanced = pwndbg.enhance.enhance(chain[-2] + offset, code=code)
  File "/home/veritas/src/pwndbg/pwndbg/enhance.py", line 98, in enhance
    instr = pwndbg.disasm.one(value)
  File "/home/veritas/src/pwndbg/pwndbg/disasm/__init__.py", line 130, in one
    for insn in get(address, 1):
  File "/home/veritas/src/pwndbg/pwndbg/disasm/__init__.py", line 150, in get
    i = get_one_instruction(address)
  File "/home/veritas/src/pwndbg/pwndbg/memoize.py", line 46, in __call__
    value = self.func(*args, **kwargs)
  File "/home/veritas/src/pwndbg/pwndbg/disasm/__init__.py", line 118, in get_one_instruction
    md   = get_disassembler(address)
  File "/home/veritas/src/pwndbg/pwndbg/disasm/__init__.py", line 111, in get_disassembler
    return get_disassembler_cached(pwndbg.arch.current,
  File "/home/veritas/src/pwndbg/pwndbg/memoize.py", line 46, in __call__
    value = self.func(*args, **kwargs)
  File "/home/veritas/src/pwndbg/pwndbg/disasm/__init__.py", line 87, in get_disassembler_cached
    cs.syntax = CapstoneSyntax[flavor]
  File "/usr/local/lib/python3.8/dist-packages/capstone/__init__.py", line 874, in syntax
    raise CsError(status)
capstone.CsError: Invalid option (CS_ERR_OPTION)

If that is an issue, you can report it on https://github.com/pwndbg/pwndbg/issues
(Please don't forget to search if it hasn't been reported before)
To generate the report and open a browser, you may run `bugreport --run-browser`
PS: Pull requests are welcome
```

https://github.com/pwndbg/pwndbg/blob/87da998fcefe8cba85f51dba0056b923483c6c1c/pwndbg/disasm/__init__.py#L86-L89

https://github.com/pwndbg/pwndbg/blob/87da998fcefe8cba85f51dba0056b923483c6c1c/pwndbg/disasm/__init__.py#L48-L51

![image](https://user-images.githubusercontent.com/25763545/115831422-26c35900-a444-11eb-8d41-5dc59e655d90.png)

This exception only raised when architecture is mips.

the reason is: https://github.com/aquynh/capstone/issues/1743

and 

![image](https://user-images.githubusercontent.com/25763545/115831654-79047a00-a444-11eb-9716-c8f856957158.png)

So I think we should wrap it with `try`.

**Comment by disconnect3d** [comment]
Fixed in #910, thanks!
