### ISSUE TITLE
Debug Qemu Exception occurred: Error: substring not found

### ISSUE THREAD

**Issue by fr0zenrain** [pwndbg/pwndbg#977]
Exception occurred: Error: substring not found (<class 'ValueError'>)
For more info invoke `set exception-verbose on` and rerun the command
or debug it by yourself with `set exception-debugger on`

set exception-verbose on

Traceback (most recent call last):
  File "/home/fr0zenrain/pwndbg/pwndbg/prompt.py", line 30, in prompt_hook
    pwndbg.events.after_reload(start=cur is None)
  File "/home/fr0zenrain/pwndbg/pwndbg/events.py", line 220, in after_reload
    f()
  File "/home/fr0zenrain/pwndbg/pwndbg/events.py", line 169, in caller
    raise e
  File "/home/fr0zenrain/pwndbg/pwndbg/events.py", line 165, in caller
    func()
  File "/home/fr0zenrain/pwndbg/pwndbg/symbol.py", line 93, in autofetch
    for mapping in pwndbg.vmmap.get():
  File "/home/fr0zenrain/pwndbg/pwndbg/memoize.py", line 52, in __call__
    value = self.func(*args, **kwargs)
  File "/home/fr0zenrain/pwndbg/pwndbg/vmmap.py", line 45, in get
    pages.extend(monitor_info_mem())
  File "/home/fr0zenrain/pwndbg/pwndbg/memoize.py", line 52, in __call__
    value = self.func(*args, **kwargs)
  File "/home/fr0zenrain/pwndbg/pwndbg/vmmap.py", line 257, in monitor_info_mem
    dash_idx = line.index('-')
ValueError: substring not found

I was debug qemu!

bash ./setup.sh

Gdb:      8.1.1
Python:   3.6.9 (default, Jan 26 2021, 15:33:00)  [GCC 8.4.0]
Pwndbg:   1.1.0 build: 5c0627d
Capstone: 4.0.1024
Unicorn:  1.0.2

**Comment by disconnect3d** [comment]
Can you show the output of: pi print(repr(gdb.execute("monitor info mem")))

**Comment by disconnect3d** [comment]
It seems like u either have some weird output there, or, an empty string - probably meaning u launch qemu without monitor; you may want to add that for potentially better experience (although monitor info mem maybe slow). We should handle this better too, heh

**Comment by disconnect3d** [comment]
Closing as we do not have enough information to work on it
