### ISSUE TITLE
Failed to start

### ISSUE THREAD

**Issue by junknet** [pwndbg/pwndbg#994]
### Description
Traceback (most recent call last):
  File "/usr/share/pwndbg/gdbinit.py", line 24, in <module>
    import pwndbg # isort:skip
  File "/usr/share/pwndbg/pwndbg/__init__.py", line 7, in <module>
    import pwndbg.android
  File "/usr/share/pwndbg/pwndbg/android.py", line 7, in <module>
    import pwndbg.file
  File "/usr/share/pwndbg/pwndbg/file.py", line 17, in <module>
    import pwndbg.symbol
  File "/usr/share/pwndbg/pwndbg/symbol.py", line 25, in <module>
    import pwndbg.ida
  File "/usr/share/pwndbg/pwndbg/ida.py", line 468, in <module>
    idc = IDC()
  File "/usr/share/pwndbg/pwndbg/ida.py", line 463, in __init__
    if available():
  File "/usr/share/pwndbg/pwndbg/memoize.py", line 35, in __call__
    if not isinstance(args, collections.Hashable):
AttributeError: module 'collections' has no attribute 'Hashable'

gdb version:11.1
OS:Archlinux(x86)
python version: 3.10.1

**Comment by disconnect3d** [comment]
Seems that py3.10.x causes this issue...

**Comment by oneNutW0nder** [comment]
It looks like this piece of code was updated a few months ago: 
https://github.com/pwndbg/pwndbg/commit/44394463e04b414b8ce64e794d12514ec8966f3d

Have you tried to update pwndbg?

**Comment by junknet** [comment]
pwndbg-git version is ok.
Arch community/pwndbg 2021.06.22-2 is out of date.
